twilio-labs/paste

packages/paste-core/utilities/screen-reader-only/package.json
packages/paste-core/utilities/screen-reader-only/rollup.config.js
packages/paste-core/utilities/screen-reader-only/src/index.tsx
packages/paste-core/utilities/screen-reader-only/stories/index.stories.tsx
packages/paste-core/utilities/screen-reader-only/tsconfig.build.json
packages/paste-core/utilities/screen-reader-only/tsconfig.json
packages/paste-design-tokens/formatters/__tests__/d.ts.spec.ts
packages/paste-design-tokens/formatters/__tests__/es6.spec.ts
packages/paste-design-tokens/formatters/__tests__/sketchpalette.spec.ts
packages/paste-design-tokens/types/index.ds.ts
packages/paste-website/gatsby-config.js
packages/paste-website/src/components/table/index.tsx
packages/paste-website/src/components/token-example/index.tsx
packages/paste-website/src/components/tokens-list/index.tsx
packages/paste-website/src/pages/tokens/index.mdx
packages/paste-website/src/utils/color-combos/__test__/index.spec.ts
packages/paste-website/src/utils/color-combos/index.ts
packages/paste-website/src/utils/color-rating/__tests__/index.spec.ts
packages/paste-website/src/utils/color-rating/index.ts
types/index.d.ts
yarn.lock

Add visual indication of the Accessibility rating of the text color tokens for small text.

feat(website): Add text color token accessibility rating to the token page

---

packages/paste-theme-tokens/src/sendgrid/index.ts

I'm removed the borderTypes key from the default theme when I refactored some Box border features, but I forgot to remove it from the SendGrid theme.

fix(theme): remove the borderTypes key from SG theme from a box refactor

---

packages/paste-website/package.json
packages/paste-website/src/components/empty-state/Error404.tsx
packages/paste-website/src/components/empty-state/InDevelopment.tsx
packages/paste-website/src/components/empty-state/NotBuilt.tsx
packages/paste-website/src/components/empty-state/NotFound.tsx
packages/paste-website/src/pages/404/index.mdx
yarn.lock

This PR adds a 404 page that renders content based on the URL you landed on.
If you landed on a component that is planned and not completed, it will say "not built"
If you landed on an unplanned page, it will say "not found"
--- 
---

feat: 404 page and empty states

---

packages/paste-design-tokens/tokens/global/box-shadow.yml
packages/paste-design-tokens/tokens/global/font-size.yml
packages/paste-design-tokens/tokens/global/index.yml
packages/paste-design-tokens/tokens/global/line-height.yml
packages/paste-design-tokens/tokens/themes/sendgrid/global/font-size.yml
packages/paste-design-tokens/tokens/themes/sendgrid/global/index.yml
packages/paste-design-tokens/tokens/themes/sendgrid/global/line-height.yml
packages/paste-theme-tokens/src/default/index.ts
packages/paste-theme-tokens/src/sendgrid/index.ts
packages/paste-website/src/components/breadcrumb/index.tsx
packages/paste-website/src/components/paste-mdx-provider/index.tsx
packages/paste-website/src/components/tokens-example/index.tsx
packages/paste-website/src/pages/tokens/index.mdx

Adding some missing tokens:
- Focus ring box-shadow should ideally be the same style across all focusable elements. This is currently just using the one we use for Button (and the yet to be built new Input design by Sarah) 
- Line height tokens. These are tightly coupled to the font-size due to our use of unit less line-height values. I think this is fine. Using the font-size*1.5 to the nearest 4 rule that came out of the Typography work recently. @two24studios double check you're OK with the values for SendGrid based on that calculation
- Fix some references to the old font size token naming convention

feat(tokens): Add box-shadow and line-height tokens

---

now.json
yarn.lock

The prod site isn't correctly redirecting to our Gatsby 404 page.  
**Test plan:** view this branch's deployment and hit a non-existent page (i.e.: https://paste-git-fix-404.twilio-dsys.now.sh/a/spinner vs https://paste.twilio.design/a)

fix: attempting to fix 404 pages on zeit's now

---

packages/paste-website/src/components/codeblock/index.tsx
packages/paste-website/src/components/component-overview-table/index.tsx
packages/paste-website/src/components/empty-state/Error404.tsx
packages/paste-website/src/components/empty-state/InDevelopment.tsx
packages/paste-website/src/components/sidebar/Navigation.tsx
packages/paste-website/src/pages/404/index.mdx
packages/paste-website/src/pages/components/index.mdx
packages/paste-website/src/pages/getting-started/engineering.mdx

fix(website): empty state / 404, component overview tweaks

---

packages/paste-design-tokens/tokens/global/border-color.yml
packages/paste-design-tokens/tokens/themes/sendgrid/global/border-color.yml

Fixes the issue reported here https://github.com/twilio-labs/paste/issues/53

fix(design-tokens): typo on word `borderr`

---

packages/paste-website/src/pages/components/anchor/index.mdx

Fix a missing link to the button component from the anchor component page.
Capitalized Button because Anchor was capitalized on the opposite end of this link.

fix(website): fix missing link in anchors page

---

packages/paste-website/src/components/component-overview-table/index.tsx
packages/paste-website/src/components/shortcodes/component-header/index.tsx
packages/paste-website/src/pages/components/anchor/index.mdx
packages/paste-website/src/pages/components/button/index.mdx
packages/paste-website/src/pages/components/index.mdx
packages/paste-website/src/pages/utilities/box/index.mdx
packages/paste-website/src/pages/utilities/index.mdx

Fixes ComponentOverviewTable and ComponentHeader to work with `utility` components. I add ComponentHeader into the Box documentation page to test it out.
Fixes https://github.com/twilio-labs/paste/issues/61

fix(website): component header and overview with utilities

---

packages/paste-website/src/pages/index.tsx
packages/paste-website/src/pages/migrate/index.mdx

Home page and Migration Guide page:
- Replaced text: `Frame Elements for Flex` to `Flex UI Docs`
- Replaced link for this text from https://zpl.io/2yOZ0Dy to https://www.twilio.com/docs/flex/flex-overview-ui-programmability
Migration Guide page:
- Swapped out `<a>` tags with `Anchor`

fix(website): update flex docs links

---

packages/paste-website/src/components/icons/TwilioIcon.tsx
packages/paste-website/src/components/sidebar/Header.tsx
packages/paste-website/src/components/site-wrapper/SiteFooter.tsx

Error was occurring because a div is used in `TwilioIcon`.
Changed the `p` tag in the footer to use `Text` and changed `TwilioIcon` to use a `span` instead of a `div`. I also added a `display` prop to `TwilioIcon`.

fix(website): changed p to Text

---

packages/paste-website/src/components/Heading.tsx
packages/paste-website/src/components/shortcodes/live-preview/index.tsx
packages/paste-website/src/pages/components/anchor/index.mdx
packages/paste-website/src/pages/components/button/index.mdx

Fixes https://github.com/twilio-labs/paste/issues/83

fix(website): tidy up the button and anchor docs

---

packages/paste-icons/package.json
packages/paste-icons/tsconfig.build.json

Icons doesn't need the `paste-theme-tokens` peerDependency.  This also fixes the issue where `paste-theme-tokens` was being built directly into the src folder hopefully 😕 
To test, please run `yarn clearn` and a couple `yarn build`s locally and see if you still get the dump of `js` files in the wrong place.

chore(icons): remove unnecessary peerDependency

---

.vscode/settings.json

VSCode has a neat little feature where you can define suggested extensions to make it easier to work on a project.  I added some I find helpful when working in this repo for fun.  [Read more about the feature](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)

chore: add suggested vscode extensions

---

packages/paste-icons/package.json

No changes in this repo, but wanting to keep our versions in sync with the `svg-to-react` repo.
The `svg-to-react` had a major version change because I modified the default template in that lib, which doesn't affect this repo since we provide a custom template.

chore(icons): bump svg-to-react version

---

packages/paste-core/components/anchor/src/index.tsx
packages/paste-core/components/anchor/src/types.ts

fix(anchor): set children as non-nullable, remove child null error

---

packages/paste-website/gatsby-config.js
packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
packages/paste-website/tsconfig.json
tsconfig.json
yarn.lock

This makes it so that the version number visible on the doc site is pulled directly from the package.json file.  Couldn't figure out [how to || if there was any benefit to] using the GraphQL system to pull this info. This seemed like a reasonable approach so I went with it.  Open to corrections :D

fix(website): automatically update website version from package

---

package.json
yarn.lock

The pre-push check on branches seems redundant because CircleCI runs the same tests, so forcing it to happen on every push was tedious.  I've modified our pre-push husky hook to only run on the `master` branch for safety there, but otherwise you can still run it manually if you want to.

chore(monorepo): only do pre-push validation on master branch

---

.jest/setupFilesAfterEnv.js
package.json
packages/paste-design-tokens/formatters/__tests__/d.ts.spec.ts
packages/paste-design-tokens/formatters/__tests__/es6.spec.ts
packages/paste-design-tokens/formatters/__tests__/sketchpalette.spec.ts
yarn.lock

Add back in emotion in the serializer to fix the tests. 
Also, throw so the tests actually fail when it errors next time.

chore: fix the token formatter tests

---

packages/paste-design-tokens/package.json
packages/paste-theme/package.json
packages/paste-website/gatsby-config.js
packages/paste-website/package.json
packages/paste-website/src/components/ThemeObjectDisplay.tsx
packages/paste-website/src/components/codeblock/index.tsx
packages/paste-website/src/components/shortcodes/component-header/index.tsx
packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx
packages/paste-website/src/constants.ts
packages/paste-website/src/pages/tokens/design-tokens-package.mdx
packages/paste-website/src/pages/tokens/how-to-compose-custom-ui-with-tokens.mdx
packages/paste-website/src/pages/tokens/theme-package.mdx
yarn.lock

Add a page for each of the Design Token package and Theme package, with install instructions and how to use. Similar to a component or utility page.

feat: design token and theme package documentation

---

packages/paste-website/src/pages/getting-started/design.mdx

- Added information people asked questions about from the Abstract demo brown bag into their appropriate sections. Didn't add any info related to collections, reviews, and other design tooling since that isn't covered in this guide yet.
- Fixed a few typos

feat: add info from brown bag questions

---

packages/paste-website/src/pages/getting-started/design.mdx

Adding spaces around "Font tester.sketch" link.

fix(website): adding spaces around font tester file link

---

packages/paste-website/src/pages/getting-started/engineering.mdx

Wrap the body of the Engineering Guidelines page in a content tag so it no longer spans the width of the page. The page now has consistent padding with the rest of the content across the site.
Before:
After:

fix(website): add wrapper to engineering guidelines

---

.jest/resolver.js

I had cleared my monorepo pre-test cache and was getting an obscure error while trying to run tests.  This PR adds a human readable error message if that situation were to occur.  
It's an unlikely scenario, but it might save future contributors some time.

chore(jest): throw error if missing package cache

---

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx

This PR addresses the nesting issue for the Principles sidenav link (#119).
Before:
After:

fix(website): correct nesting for principles sidenav link

---

packages/paste-core/utilities/box/__tests__/__snapshots__/box.test.tsx.snap
packages/paste-core/utilities/box/__tests__/box.test.tsx
packages/paste-website/package.json
yarn.lock

Just adding a few snapshot tests for Box.  You can observe from the tests that `width` isn't being set correctly to token values, as this is a current bug with styled system v4: 
Will be fixed in the v5 upgrade and this test will catch that improvement.

test(box): adding snapshot tests

---

packages/paste-types/src/style-props/spacing.ts

Allows the value "auto" for marginLeft and marginRight typings

fix: allow 'auto' for marginLeft and marginRight

---

packages/paste-website/src/components/breadcrumb/index.tsx

The slashes on breadcrumbs shouldn't be `aside`, `span` at best

fix(website): change breadcrumb slash from aside to span

---

packages/paste-core/components/anchor/src/styles.ts
packages/paste-website/src/components/SiteLink.tsx
packages/paste-website/src/components/breadcrumb/index.tsx
packages/paste-website/src/components/component-overview-table/index.tsx
packages/paste-website/src/components/shortcodes/component-header/index.tsx
packages/paste-website/src/pages/index.tsx

I attempted to use Anchor `as` Link, but that caused conflicts with the `href` and `to` props respectively. If we used this method, we also lost the prefetching Gatsby provides with Link. This being one of the larger benefits we get get with Gatsby, and makes for a faster user experience on the site.
I decided the best path forward was to create a styled component that wrapped Link and used the token styles from Anchor.
I also found a minor bug where we're not using the `shadowFocus` token in Anchor and Button. Anchor is fixed, and I've created a ticket to fix Button since that has more complex styles.

feat(website): SiteLink Component, replace Link with SiteLink

---

README.md

Most `README.md` files have a license section and this repo didn't have one. I know this might not be big deal but now the documentation looks better.

Added the License section to README.md

---

packages/paste-core/components/button/src/styles.ts
yarn.lock

Because we have now fixed the contrast of the button hover and focus states with the outline color, we can now remove the text underline. 
Fixes https://github.com/twilio-labs/paste/issues/54

fix: remove the underline from button states

---

packages/paste-types/src/style-props/backgroundColor.ts
packages/paste-website/src/components/tokens-example/index.tsx

Fixes #74. Transitioned to use of `ColorBox` (from `BorderBox`) to display Border Color examples, improving readability.

fix(tokens): updates border color to use color box

---

package.json
packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
packages/paste-website/tsconfig.json

Change the version number that the website uses to display from the website package version number to the mono repo package.json version number.

fix: change the version number the website displays

---

.circleci/config.yml
yarn.lock

For applitools to run correctly, it apparently has to come last due to a limitation with their implementation. For every build/job, it thinks a regression test is run, but it's not for us. 
it's annoying as it pushes the build time out a little.
To fix that, I've made applitools dependent on prettier, attaches to the workspace, and removed the website build from 'build' as it's not necessary as Now does this check for us effectively

chore(ci): correct applitools vrt run

---

packages/paste-core/components/button/src/styles.ts

We updated the regular button to a semibold font-weight but forgot to update the small button.

fix(button): add font-weight semibold to small buttons

---

packages/paste-theme/src/themeProvider.tsx
yarn.lock

Body styles from global styles not rendered based on props not being passed in,
so there was no theme object to get the token values from.

fix: global styles by passing props

---

package.json
yarn.lock

Prettier ran fine on my machine but fails on master in CI. Trying to lock the version to see if that helps CI. 
Also, notice changes happen over time on certain PRs where the formatting suddenly needs to change.

fix: lock prettier version for more predictable builds

---

packages/paste-types/package.json

Box props (and others) aren't typed correctly.  Hover over the `marginBottom` on line 17 here https://codesandbox.io/s/paste-starter-kit-rj7yy
Cmd + click it, then hover.  CMD click all the way until you get to `Space`.  Even that is typed as `any`.  `ThemeShape` is correctly typed, but `ResponsiveValue` is not typed at all.  
I'm not sure why `ResponsiveValue` isn't being typed correctly. My hunch is that we need to move `styled-system` as a dependency.  Any other advice is appreciated.  If no one has a better guess, I'd be willing to push this out to test and see if it fixes anything.

fix(types): add @types/styled-system dependency

---

packages/paste-core/components/anchor/__tests__/__snapshots__/anchor.test.tsx.snap
packages/paste-core/components/anchor/src/styles.ts
yarn.lock

Update the anchor component for hover state to use the color-text-link-darker token. The text should darken on hover in addition to the underline disappearing.

fix(anchor): fix hover color

---

.storybook/addons.js
.storybook/config.js
package.json
yarn.lock

Add a plugin for a11y that we should have added a long time ago for quick checks
also give in storybook colorblindness simulation.

chore: add the accessibilty plugin to storyboook

---

packages/paste-core/components/button/__tests__/__snapshots__/button.test.tsx.snap
packages/paste-core/components/button/src/styles.ts
packages/paste-core/components/button/stories/index.stories.tsx
packages/paste-core/components/spinner/stories/index.stories.tsx
packages/paste-design-tokens/tokens/global/sizing.yml
packages/paste-theme-tokens/src/default/index.ts
packages/paste-theme-tokens/src/sendgrid/index.ts

- Correct the button heights by dropping the line-height by one
- Introduce a new icon size so the default icon makes a button the correct height

fix: correct button heights add new default icon size

---

packages/paste-website/src/pages/components/card/index.mdx

formatting and spacing wasn't inline with what we have already.
Tweaked it slighly to be less roomy

fix: card code example spacing and formatting

---

packages/paste-core/components/spinner/src/index.tsx

Each component should export it's prop types so a consumer can extend them or use them in dynamic prop setting situations.

fix(spinner): export the prop types with the component

---

packages/paste-website/src/components/tokens-example/index.tsx

Realised we were displaying "light" text colors on the brand background instead of the actual inverse background color as intended in real life.
Fixed

fix(website): display text tokens on the correct inverse bg color

---

packages/paste-design-tokens/tokens/themes/sendgrid/global/text-color.yml

fix(SG): change `color-text-weak` to `gray-80` for a11y

---

packages/paste-core/components/heading/stories/index.stories.tsx
packages/paste-website/src/pages/components/heading/index.mdx

Noticed we were missing examples to be checked for visual regression for the heading component, just adding some here.

chore(heading): add storybook examples for VRT

---

packages/paste-core/utilities/flex/package.json

fix: add prop-types package, add description, bump types

---

packages/paste-website/src/pages/components/card/index.mdx

Make some minor updates to card examples to better showcase using the components:
- Use `Paragraph` in first example
- Use `Text` as div for text align styles rather than inline styles on a div

docs(card): make some updates to card examples

---

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx
packages/paste-website/src/pages/roadmap/index.mdx

Update the roadmap page with new version numbering system.
Hide the changelog item from the sidebar for now

chore(website): update the roadmap and remove changelog item

---

packages/paste-core/components/button/stories/index.stories.tsx

Currently, our VRT tests keep failing on every PR because Applitools Eyes is capturing a screenshot of the Button story page at different times.  This causes the spinner icon to be visually different on each test, even if the test is a few miliseconds off.  
The current recommended approach to solve the issue is to check if we're in the testing environment and modifying the behavior: https://github.com/applitools/eyes-storybook#dealing-with-dynamic-data
This change only modifies the story, so production code doesn't have to carry the burden.  I think ideally, the VRT tools could provide the reduced motion media query and we can leverage that on animations.  Until then, to regain our sanity, this is a hack fix.

fix(storybook): fix vrt on loading button

---

packages/paste-core/core-bundle/src/index.tsx
packages/paste-core/core-bundle/tools/generate.js

When building the core package, as part of the generation step the package.json file is generated with no ending new line. 
This causes uncommitted changes to be created for the package.json file due to it being committed with a newline by prettier already. By adding a new line upon generation, we should remove this.
This makes it possible to do continual deployment.

chore(core): prevent uncommitted changes when building core package

---

packages/paste-website/src/pages/icon-system/how-to-add-an-icon.mdx

Fix typo in "Formatting an icon" 1.1. Changes "SHIFT" to "OPTION"

fix: "SHIFT" to "OPTION" in "Formatting an icon"

---

packages/paste-core/utilities/grid/src/Grid.tsx

Found a React hook error in `Grid`, because we used `useTheme()` inside `useMemo()`. This moves `useTheme()` to a const in order to fix the issue.

fix(grid): set useTheme as const to fix hook error

---

packages/paste-design-tokens/tokens/themes/sendgrid/global/background-color.yml
packages/paste-design-tokens/tokens/themes/sendgrid/global/border-color.yml

The current colors for disabled buttons in the SG theme are not nearly as light as the Console version, so the the buttons don't look disabled. Adjusted the values the tokens use for the SendGrid theme so they are more obviously disabled.

fix(tokens): update tokens for sg disabled buttons

---

packages/paste-core/utilities/grid/__tests__/grid.test.tsx
packages/paste-core/utilities/grid/src/Column.tsx
packages/paste-core/utilities/grid/src/helpers.tsx

Currently the `Column`'s aren't setting the padding value correctly. It's coming through as the token value, i.e. `space20`. I've added a function to process the token value into the correct padding values.
Tested locally via the website.

fix(grid): add getColumnGutters function to process token value

---

packages/paste-core/utilities/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/utilities/grid/__tests__/grid.test.tsx
packages/paste-core/utilities/grid/src/Column.tsx
packages/paste-core/utilities/grid/src/types.ts
packages/paste-core/utilities/grid/stories/index.stories.tsx

@SiTaggart discovered we were using `flex` improperly in `Column`. `Flex` was interfering with children `block` elements an not allowing them to be full width. The `flex` styles are unnecessary because we're calculating a width for each `Column`.
This removes the `Column` `flex` styles, which allows children `block` elements to be 100% width.

fix(grid): remove column flex styles

---

packages/paste-core/utilities/flex/__tests__/__snapshots__/flex.test.tsx.snap
packages/paste-core/utilities/flex/__tests__/flex.test.tsx
packages/paste-core/utilities/flex/src/index.tsx
packages/paste-core/utilities/flex/stories/index.stories.tsx
packages/paste-core/utilities/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/utilities/grid/__tests__/grid.test.tsx
packages/paste-core/utilities/grid/src/Column.tsx
packages/paste-core/utilities/grid/src/Grid.tsx
packages/paste-core/utilities/grid/src/types.ts
packages/paste-core/utilities/grid/stories/index.stories.tsx
packages/paste-website/src/pages/utilities/flex/index.mdx

In creating these alignment examples https://codesandbox.io/s/vertical-alignment-with-text-using-paste-t1bpn it dawned on me that you need the ability to change the element type to be able to create valid semantic markup.
In the example it would have been handy to change the rendered div of `Flex` to be a span so it can be nested in a heading correctly.
Decided to apply the same to `Grid` as I can see you may need to play with the rendered element to create valid HTML in your compositions

feat: add as support to flex and grid

---

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/utilities/media-object/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/utilities/media-object/__tests__/index.spec.tsx
packages/paste-core/utilities/media-object/src/index.tsx
packages/paste-core/utilities/media-object/stories/index.stories.tsx

In creating these alignment examples https://codesandbox.io/s/vertical-alignment-with-text-using-paste-t1bpn it dawned on me that you need the ability to change the element type to be able to create valid semantic markup.
For example you can't nest a `div` inside a heading element. By pass as down to box, you can now change the markup as you desire to support valid HTML. I also set the default to a span as it's the one element that will work in the most places.
Also adding support for setting margin top and bottom to the outer element

feat(media-object): add support for the as prop and margin top and bottom

---

packages/paste-core/components/heading/__tests__/__snapshots__/heading.test.tsx.snap
packages/paste-core/components/heading/__tests__/heading.test.tsx
packages/paste-core/components/heading/src/index.tsx
packages/paste-core/components/heading/stories/index.stories.tsx
packages/paste-website/src/pages/components/heading/index.mdx

Based on a conversation in Slack, a use case was presented where removing the bottom margin on the `Heading` component would be useful.
This can be use when placing headings in contained areas or on top of other components with bounding boxes such as tables.
This PR introduces the `noMargin` prop, which removes margin from a rendered `Heading`

feat(heading): add marginBottom prop to remove margin

---

packages/paste-core/components/button/package.json
packages/paste-core/components/card/package.json
packages/paste-core/components/heading/package.json
packages/paste-core/components/input/package.json
packages/paste-core/components/list/package.json
packages/paste-core/components/paragraph/package.json
packages/paste-core/components/spinner/package.json
packages/paste-core/primitives/box/package.json
packages/paste-core/primitives/text/package.json
packages/paste-core/utilities/absolute/package.json
packages/paste-core/utilities/aspect-ratio/package.json
packages/paste-core/utilities/flex/package.json
packages/paste-core/utilities/grid/package.json
packages/paste-core/utilities/media-object/package.json
packages/paste-core/utilities/screen-reader-only/package.json
packages/paste-core/utilities/truncate/package.json

Add missing peer deps from some of our packages.
It was causing Grid and Aspect-ration to not compile correctly. The other were but I think that's only by accident due to the monorepo effect
The minimum I'm expecting every package to need is 
- react
- react-dom
- emotion/styled
- styled-system

Fix: missing peer deps

---

packages/paste-website/src/pages/icon-system/how-to-add-an-icon.mdx

Adding a missing `yarn install` step

chore(website): add missing install step to instructions

---

packages/paste-website/package.json
packages/paste-website/src/pages/primitives/modal-dialog-primitive/ModalDemo.tsx
packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx

Adds documentation to our doc site for the new modal dialog primitive component.
Things to note:
- I played around with the page structure a bit.  For example, `API` doesn't wrap everything in `Usage Guide` like it does elsewhere. 
Before:
After: 
- I added two sections for props, one for each exported component.  
- Guidelines is fairly simple because this is a primitive, the bulk of the docs fall under the Usage guidelines.
- I give credit to `reach-ui` a few times so this doesn't read like blatant theft 😟 
- The `LivePreview` component doesn't work with Modals.  No biggie, I link to Storybook.

feat(website): new modal dialog primitive docs

---

.storybook/addons.js
.storybook/config.js
package.json
yarn.lock

We shouldn't have needed to add the two deps for the website, but for some reason that fixes the build. Not really sure why.

feat(storybook): add storybook viewport add on

---

package.json
packages/paste-core/components/alert/package.json
packages/paste-core/components/button/package.json
packages/paste-core/components/card/package.json
packages/paste-core/core-bundle/package.json
packages/paste-core/primitives/box/__tests__/__snapshots__/box.test.tsx.snap
packages/paste-core/primitives/box/__tests__/box.test.tsx
packages/paste-core/primitives/box/package.json
packages/paste-core/primitives/box/src/PseudoPropStyles.ts
packages/paste-core/primitives/box/src/index.tsx
packages/paste-core/primitives/box/stories/index.stories.tsx
packages/paste-core/utilities/absolute/package.json
packages/paste-core/utilities/aspect-ratio/package.json
packages/paste-core/utilities/grid/package.json
packages/paste-core/utilities/media-object/package.json
packages/paste-theme-tokens/src/console/index.ts
packages/paste-theme-tokens/src/default/index.ts
packages/paste-theme-tokens/src/sendgrid/index.ts
packages/paste-types/package.json
packages/paste-website/package.json
packages/paste-website/src/pages/primitives/box/index.mdx
yarn.lock

Inspired from [Chakra-UI's PseudoBox](https://chakra-ui.com/pseudobox).
This component makes Box much more versatile by allowing consumers to use the token props on CSS pseudo-selectors.

feat(box): allow passing tokens via pseudo-class props

---

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.styles.ts

I made a small change in trying to fix something our typing issues with upgrading emotion, but forgot to remove it.
This undos that change and fixes a regression.

fix(website): fix regression in sidebar nav

---

now-build.sh
package.json
packages/paste-core/components/alert/package.json
packages/paste-core/components/anchor/package.json
packages/paste-core/components/button/package.json
packages/paste-core/components/card/package.json
packages/paste-core/components/form/package.json
packages/paste-core/components/heading/package.json
packages/paste-core/components/list/package.json
packages/paste-core/components/paragraph/package.json
packages/paste-core/components/spinner/package.json
packages/paste-core/primitives/box/package.json
packages/paste-core/primitives/modal-dialog/package.json
packages/paste-core/primitives/text/package.json
packages/paste-core/utilities/absolute/package.json
packages/paste-core/utilities/aspect-ratio/package.json
packages/paste-core/utilities/flex/package.json
packages/paste-core/utilities/grid/package.json
packages/paste-core/utilities/media-object/package.json
packages/paste-core/utilities/screen-reader-only/package.json
packages/paste-core/utilities/truncate/package.json
packages/paste-icons/package.json
packages/paste-style-props/package.json

I moved the props-gen build from the main `yarn build` command because it makes my builds take ages to complete.  Instead, it's now isolated in its own `yarn build:props` command which I added to the now config.

chore: remove the prop build from the main build command

---

.github/workflows/publish.yml

Package prop building is now a separate task but we publish the output with the package.
We should run this before publishing our packages still.

chore: add prop building to release task

---

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/alert/src/index.tsx
packages/paste-core/components/alert/stories/index.stories.tsx
packages/paste-core/components/button/__tests__/__snapshots__/button.test.tsx.snap
packages/paste-core/components/card/__test__/__snapshots__/card.test.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formInput.test.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formTextarea.test.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formhelptext.test.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formlabel.test.tsx.snap
packages/paste-core/layout/flex/__tests__/__snapshots__/flex.test.tsx.snap
packages/paste-core/layout/flex/src/index.tsx
packages/paste-core/layout/flex/stories/index.stories.tsx
packages/paste-core/layout/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/layout/grid/stories/index.stories.tsx
packages/paste-core/layout/media-object/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/layout/media-object/src/index.tsx
packages/paste-core/layout/media-object/stories/index.stories.tsx
packages/paste-core/primitives/box/__tests__/__snapshots__/box.test.tsx.snap
packages/paste-core/primitives/box/src/index.tsx

Box having a default `min-width:0` property was causing undesirable effects when flex children were collapsing their containers.
Removing it as a default and only setting it when needed it a safer, more intentional fix.
TODO:

fix(box): removing min-width

---

packages/paste-core/components/form/__tests__/__snapshots__/formInput.test.tsx.snap
packages/paste-core/components/form/src/shared/FieldWrapper.tsx

Fix is in `FieldWrapper` and fixes both `FormInput` and `FormTextArea`

fix(form): change hover for disabled and readonly input and textarea

---

packages/paste-core/components/form/__tests__/__snapshots__/formTextarea.test.tsx.snap
packages/paste-core/components/form/package.json
packages/paste-core/components/form/src/FormTextArea.tsx
yarn.lock

Adding resizing to the textarea component via react-autosize-textarea.
I have not added any tests here as enzyme doesn't seem to detect that styles applied by the library in the style prop. We have to rely on the fact that we're just directly using the library directly and that should have it's own tests. It's annoying, I'm getting annoyed with enzyme.

feat(form): add autoresizing to the textarea component

---

packages/paste-core/components/form/__tests__/formInput.test.tsx
packages/paste-core/components/form/__tests__/formTextarea.test.tsx
packages/paste-core/components/form/src/FormInput.tsx
packages/paste-core/components/form/src/FormTextArea.tsx
packages/paste-core/components/form/src/shared/Utils.tsx

We spread props to the input and textarea. We might block you from doing so in typescript, but I can ignore those and if I'm not using typescript I don't get a warning.
In all cases where we spread props we must manually pluck those banned props from the consumer provided props.
I'm also not convinced about the use of `never` as the props still appear in the auto completion suggestions, only for typescript to then tell you, you can't use it. It's a little confusing.

fix(form): enable safely spreading props to form controls

---

packages/paste-style-props/src/proptypes/layout.ts

The width options given to the style props proptypes for sizing are wrong due to a minor syntax error.
Object.keys on an array will return the indices.

fix(style-props): correct width options in the style props proptypes

---

packages/paste-website/src/pages/components/alert/index.mdx

We fixed it.
Removed this callout from the Alert docs page:
> A note about Icon Sizing
> Heads up! We're making some changes to Icon sizing which will reduce the size of the close action that dismisses alerts. You may still proceed to use this component, as the Icon update will not be a breaking change.
https://paste-git-fix-alert-icon-sizing.twilio-dsys.now.sh/components/alert#dismissible

fix: remove "close icon" sizing note on Alert docs

---

packages/paste-website/src/components/DoDont.tsx

fix(website): add overflow-y to do/dont Box

---

packages/paste-website/src/pages/form-elements/input/index.mdx
packages/paste-website/src/pages/form-elements/textarea/index.mdx

There are still a few places we're referring to help text as "helper" instead of "help"
- Input: https://paste-git-fixdocs-form-helper-text.twilio-dsys.now.sh/form-elements/input/
- Textarea: https://paste-git-fixdocs-form-helper-text.twilio-dsys.now.sh/form-elements/textarea/

fix(docs): Change instances of "helper" to "help" on form components

---

packages/paste-website/src/pages/roadmap/index.mdx

Update Roadmap after completion of April 7, 2020 release with targets for next release (May 19, 2020) and the future release (June 20, 2020).

docs(website): roadmap update for next release (May 2020)

---

packages/paste-website/src/pages/components/modal/index.mdx

In the Modal docs Anatomy section:
- Swapped alias names for tokens
- Swapped heading anatomy with Heading component used
https://paste-git-fixmodal-docs-swap-aliases-in-anatomy.twilio-dsys.now.sh/components/modal#anatomy

fix(modal docs): swap alias names in Anatomy with token

---

packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx

Added a callout to modal docs, given that there may be confusion between choosing primitive or component

docs(web): add callout to modal in modal primitive

---

packages/paste-core/components/heading/package.json
packages/paste-core/components/list/package.json
packages/paste-core/components/paragraph/package.json
packages/paste-core/components/spinner/package.json
packages/paste-core/primitives/box/package.json
packages/paste-core/primitives/text/package.json

Update the following components to `production` status since teams are using them:
- List
- Heading
- Paragraph
- Text Primitive
- Box Primitive
- Spinner

feat(components): promote text components, spinner and primitive to prod

---

packages/paste-website/src/pages/icon-system/how-to-add-an-icon.mdx

Removed mention of 16px and 20px icon templates.

fix: remove mention of old Sketch icon templates

---

packages/paste-website/src/components/shortcodes/live-preview/index.tsx

Change the code block example background from grey to white to make the components easier to see.

fix(website): change codeblock background to white for visibility

---

packages/paste-core/layout/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/layout/grid/src/Grid.tsx
packages/paste-core/layout/grid/stories/index.stories.tsx

fix(grid): add flex wrap style

---

packages/paste-core/components/heading/src/index.tsx
packages/paste-website/src/pages/components/card/index.mdx
packages/paste-website/src/pages/components/heading/index.mdx
packages/paste-website/src/pages/layout/grid/index.mdx

fix(heading): set variant as required, remove default variant

---

packages/paste-website/src/pages/components/alert/index.mdx

Updated icon colors in Alert docs Anatomy section (based on icon update in previous PR):
- Error: color-text-error-dark --> color-text-error
- Warning: color-text-warning-dark --> color-text-warning

feat(alert docs): update color tokens in Anatomy

---

packages/paste-website/src/component-examples/CheckboxExamples.ts
packages/paste-website/src/component-examples/RadioGroupExamples.ts

- Checkbox docs: "mor" --> "more"
- Radio docs: "netowrk" --> "network"

fix(checkbox docs): typo in live example

---

packages/paste-website/src/pages/components/button/index.mdx

feat(website): add reset button example to button doc page

---

.github/workflows/chromatic.yml

was incorrectly fetching gith history for the action to do comparisons

chore: correctly get the full git history for chromatic

---

packages/paste-core/components/button/__tests__/button.test.tsx
packages/paste-core/components/button/src/index.tsx
packages/paste-core/components/button/src/types.ts
packages/paste-core/components/button/stories/index.stories.tsx
packages/paste-website/src/pages/components/button/index.mdx

Fixes https://github.com/twilio-labs/paste/issues/368

fix(button): allow html button attributes

---

packages/paste-website/src/pages/components/paragraph/index.mdx

margin-bottom in paragraph uses space-70, not space-60

fix(paragraph docs): margin-bottom typo in Anatomy

---

packages/paste-website/src/pages/form-elements/checkbox/index.mdx

"When to use an Checkbox and Checkbox Group" --> "When to use a Checkbox and Checkbox Group"

feat(checkbox docs): typo in "when to use" heading

---

packages/paste-website/src/pages/components/paragraph/index.mdx

Updated Anatomy section in Paragraph docs to show margin-bottom is modifiable

feat(Paragraph docs): change Anatomy to show margin-bottom is modifiable

---

packages/paste-website/src/pages/components/modal/index.mdx

Add guideline to Composition Notes about using h4 in Modal Body
https://paste-git-featmodal-docs-use-h4-in-body.twilio-dsys.now.sh/components/modal/#composition-notes

feat(Modal docs): add guideline about using h4 in Modal Body

---

packages/paste-website/src/pages/index.tsx

fix(docs): homepage typo

---

packages/paste-style-props/src/proptypes/layout.ts
packages/paste-style-props/src/types/layout.ts
packages/paste-website/src/components/site-wrapper/SiteBody.tsx
packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
packages/paste-website/src/components/site-wrapper/SiteMain.tsx
packages/paste-website/src/components/site-wrapper/SiteThemeProvider.tsx
packages/paste-website/src/components/site-wrapper/constants.ts
packages/paste-website/src/constants.ts

Screen capture showing responsive top bar: https://share.getcloudapp.com/E0uz5pNy

fix(website): setup responsive friendly structure

---

packages/paste-website/src/pages/components/modal/index.mdx

Modal page was using the separator change log. Updating the package name to fix it.

docs(modal): fix the link to the modal changelogs

---

.jest/setupFilesAfterEnv.js
packages/paste-libraries/animation/src/useReducedMotion.tsx

Fixes https://github.com/twilio-labs/paste/issues/499
Adds a guard for matchMedia where it's used and removes the Jest shim in our codebase to make this more widely applicable.

fix(animation-library): add window.matchMedia guard

---

packages/paste-core/components/modal/src/Modal.tsx
packages/paste-core/components/modal/src/utils/consoleUtils.ts
packages/paste-core/components/modal/stories/index.stories.tsx
packages/paste-website/src/pages/components/modal/index.mdx

Fixes an issue specific to Twilio's Console application which causes the page to shift upwards by 80px when the modal opens. This happens because of styling set on the app which clashes with the scroll-lock functionality of reach's modal. This prop is the least worst solution to a problem currently blocking adoption on the Modal component.

fix(modal): add '__console_patch' prop to fix bug in Console

---

packages/paste-website/src/pages/components/list/index.mdx

We had a typo in the list example. Fixed.

docs(list): fix typo in example

---

packages/paste-website/src/pages/primitives/box/index.mdx

Box had an example using `sizes10` instead of `size10` as a token, breaking the example

docs(box): fix typo in example

---

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formlabel.test.tsx.snap
packages/paste-core/components/form/src/FormLabel.tsx
packages/paste-core/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
packages/paste-core/primitives/box/src/BoxPropTypes.ts
packages/paste-core/primitives/box/src/index.tsx
packages/paste-core/primitives/text/src/TextPropTypes.ts
packages/paste-core/primitives/text/src/index.tsx

Resolves https://github.com/twilio-labs/paste/issues/497
Explicitly sets `text-transform: none` to guard against bootstrap.css overriding label and legend styles.
This PR also enables the `textTransform` prop on our Box component.

chore(form): guard against 'text-transform: uppercase' on FormLabel

---

packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/menu/src/index.tsx

Updates:
- Changed default fontColor for menuitem to colorText from colorTextLink
- Updated minWidth to the smallest token (sketch had a smaller value :/)
- Updated zIndex to the 20 value. For any overlay type component I think 20 is a safer default value because developer code can occasionally use zIndex10.

chore(menu): updated font color, width, and zindex styles

---

package.json
packages/paste-core/components/alert/package.json
packages/paste-core/components/anchor/package.json
packages/paste-core/components/combobox/package.json
packages/paste-core/components/list/package.json
packages/paste-core/components/menu/package.json
packages/paste-core/components/modal/package.json
packages/paste-core/components/paragraph/package.json
packages/paste-core/components/popover/package.json
packages/paste-core/components/typography/package.json
packages/paste-core/core-bundle/package.json
packages/paste-core/primitives/combobox/package.json
packages/paste-core/primitives/disclosure/package.json
packages/paste-core/primitives/menu/package.json
packages/paste-core/primitives/modal-dialog/package.json
packages/paste-core/primitives/non-modal-dialog/package.json
packages/paste-core/primitives/tabs/package.json
packages/paste-design-tokens/package.json
packages/paste-libraries/dropdown/package.json
packages/paste-libraries/reakit/package.json
packages/paste-libraries/styling/package.json

Since local builds have been rather slow on my machine, I took a little time to research ways to improve that DX. This PR does a couple things:
1. It fixes the `build:dev` command by removing the `w` in the `rollup -cw` part of every package. The `w` makes rollup startup a watcher, which basically pauses the build on the first package. We've never really used it since our dev cycle involves storybook which operates on the src files anyways, so we won't miss this.
2. It adds the lerna `--since HEAD` flag (https://github.com/lerna/lerna/issues/2211#issuecomment-535943543) which makes lerna only build packages with changes. There are one gotcha with this flag that I'm aware of:
1. You can get into a weird state if you exclusively run `yarn build:dev` where, some of your packages might have …

chore: improve build:dev command

---

packages/paste-website/src/pages/getting-started/engineering/index.mdx

Package @twilio-paste/styling-library seems to have been missing from getting started script.

docs(getting-started): add missing dependency in yarn add

---

packages/paste-website/src/pages/components/tooltip/index.mdx

The guidance we provide for using a tooltip could be more explicit to foster the desired outcome in product.
Updating the language about what elements must be used to place a tooltip on, and explicitly what  you must not do.

docs(tooltip): update accessibility guidelines

---

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/form/__tests__/__snapshots__/formlabel.test.tsx.snap
packages/paste-core/components/form/src/FormLabel.tsx

Resolves: https://github.com/twilio-labs/paste/issues/556

fix(form): add border-bottom-width rule for bootstrap override

---

packages/paste-core/components/popover/src/Popover.tsx
packages/paste-core/components/tooltip/src/index.tsx

Resolves: https://github.com/twilio-labs/paste/issues/548

fix(tooltip): move arrow to StyedBase to prevent line-height override

---

packages/paste-website/src/pages/components/menu/index.mdx

I wasn't sure at the time how useful these would be to document. In hindsight, very.

docs(menu): add missing state props

---

packages/paste-core/layout/aspect-ratio/stories/index.stories.tsx
packages/paste-website/src/pages/components/card/index.mdx
packages/paste-website/src/pages/components/combobox/index.mdx
packages/paste-website/src/pages/components/disclosure/index.mdx
packages/paste-website/src/pages/components/menu/index.mdx
packages/paste-website/src/pages/components/modal/index.mdx
packages/paste-website/src/pages/components/popover/index.mdx
packages/paste-website/src/pages/components/tabs/index.mdx

Missed this layout component when I changed components to use `colorBorderLighter`. Also updated the doc site anatomy tables.

chore(aspect-ratio): update border color to colorBorderLighter

---

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx

Our design guidelines were not linked in nav, adding it now

feat(web): add design guidelines back to nav

---

packages/paste-core/components/form/__tests__/radio.test.tsx
packages/paste-core/components/form/src/Radio.tsx
packages/paste-core/components/form/src/RadioContext.tsx
packages/paste-core/components/form/src/RadioGroup.tsx
packages/paste-core/components/form/stories/radio.stories.tsx
packages/paste-core/primitives/box/src/index.tsx
packages/paste-style-props/src/types/border.ts

Fixes https://github.com/twilio-labs/paste/discussions/535

fix(radio): allow passing disable to individual radio in radioGroups

---

packages/paste-core/components/combobox/__tests__/index.spec.tsx
packages/paste-core/components/combobox/package.json
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/combobox/src/ComboboxListboxGroup.tsx
packages/paste-core/components/combobox/src/ComboboxListboxOption.tsx
packages/paste-core/components/combobox/stories/index.stories.tsx
packages/paste-website/src/component-examples/ComboboxExamples.ts
packages/paste-website/src/components/search/index.tsx
packages/paste-website/src/pages/components/combobox/index.mdx
yarn.lock

This PR introduces the ability to create options groups and use Combobox as a controlled input.
- Add the ability to create options groups within the Combobox Listbox.
- Add necessary props to use Combobox as a controlled component.
- Document options groups and controlled component

feat:(combobox):  option groups and controlled input

---

packages/paste-website/src/components/ContactUsMenu.tsx

Removed `/new` from Discussions links to solve bug for login.
@SiTaggart Can you file a bug with discussions about this? At the same time, will be great to know if they support templates in discussions

fix(web): fix 404 links to github when logging in

---

packages/paste-core/components/button/src/ResetButton.tsx
packages/paste-core/components/button/stories/index.stories.tsx

With an update to the reset variant of button we accidentally regressed our roadmap page.
This PR applies a small fix to the reset variant that puts it back to original behavior, but also inherits weight and color. This places the reset variant back to its original intended purpose; use in compositions.
I also noticed we don't actually regression test a pretty common use case for buttons, icon next to text. Adding for regression purposes.
**Code includes:**
- inherit font size, weight and color on reset variants of button
- add story examples to cover those use cases so we catch future regressions
- add missing button examples text with icon for regression purposes
**N.B.** I get it that ideally we'd just replace the roadmap custom disclosures with the _real_, since released Disclosure …

fix(button): reset variant should inherit type styles

---

packages/paste-core/components/combobox/__tests__/index.spec.tsx
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/combobox/src/index.tsx
packages/paste-core/components/combobox/src/types.ts
packages/paste-core/components/combobox/stories/index.stories.tsx
packages/paste-core/primitives/combobox/src/index.tsx
packages/paste-website/src/component-examples/ComboboxExamples.ts
packages/paste-website/src/pages/components/combobox/index.mdx

When using the Combobox there are sometimes needs where you need that little bit of extra control, for example clearing a selection based on some application logic. 
Currently we don't provide a good enough means to clear the selection and input value together as they are not explicitly tied to each other, and a combobox can get into a strange state once a selection has been made.
By exposing the internal state hook provided by Downshift, and allowing a consumer to pass the returned state props to the component as `state` we allow the consumer to use some of the action methods provided by downshift, such as `reset`.
This PR introduces the ability to provide Combobox a state override by using the state hook.

fix(combobox): provide a means to use action methods from state hook

---

packages/paste-website/src/pages/form-elements/input/index.mdx

- "lable" --> "label"
- "assicated" --> "associated"

fix(input docs): typo in accessibility section

---

packages/paste-website/src/pages/components/card/index.mdx

Original example is kind of weird and when we made the icons display block we broke the layout.
Just removing the icon seems to be the most sensible thing to do.

docs(card): remove icon from example

---

packages/paste-website/src/pages/components/combobox/index.mdx

- Remove extra period in [useCombobox state hook heading](https://paste.twilio.design/components/combobox#usecombobox-state-hook)

fix(combobox docs): typo in useCombobox state hook heading

---

packages/paste-website/src/components/site-wrapper/SiteBody.tsx
packages/paste-website/src/components/site-wrapper/SiteHeader.tsx

Prevents Combobox, Menu, and Popover from overlapping the top bar area of the docs site.
**QUESTION:**
Does not fix the Tooltip overlap. We intentionally set tooltip to have our highest zIndex token. So tooltips will always overlap. Should we change the Tooltip zIndex?
**ANSWER:**
No, this feels very intentional and expected behaviour.

fix(website): fix topbar zIndex

---

packages/paste-core/components/button/__tests__/button.test.tsx
packages/paste-core/components/button/src/index.tsx

fix(button): remove unnecessary link error

---

packages/paste-website/src/pages/components/disclosure/index.mdx

"`[Paste Heading](/components/heading)`" --> Anchor component
https://paste-git-fixdisclosure-docs-broken-link-in-first-paragraph.twilio-dsys.vercel.app/components/disclosure/

fix(disclosure docs): broken link in first paragraph

---

packages/paste-core/components/form/src/fieldwrapper/DefaultFieldWrapper.tsx
packages/paste-core/components/form/src/fieldwrapper/InverseFieldWrapper.tsx

When I was working on the Anchor variants, I noticed the display names for the FieldWrapper variants were wrong.

chore(form): fix FieldWrapper display names

---

packages/paste-libraries/dropdown/package.json
yarn.lock

BREAKING CHANGE:
The upgrade to downshift has introduced some breaking changes to the typings of certain properties
but none to the API itself.
Please follow the release notes from downshift for more information: https://github.com/downshift-js/downshift/releases/tag/v6.0.0

chore(dropdown-library): upgrade downshift to v6

---

packages/paste-core/components/form/src/Checkbox.tsx
packages/paste-core/components/form/src/shared/BaseRadioCheckbox.tsx

Replace the css after and before elements for the check and indeterminate states with an icon

fix(checkbox): replace check and dash with icons

---

packages/paste-website/src/pages/index.tsx

Fixes the components card on the homepage to style the h2 as heading20 to match the other two cards.

Update components card to use heading20 variant

---

packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx

- fix(combobox): handling refs in downshift v6 is different
- docs(combobox-primitive): update to reflect v6 of downshift

chore: updates to combobox and primitive docs

---

README.md

You must `yarn` before doing anything in the repo.

fix: update the readme for first time installers

---

packages/paste-website/src/pages/getting-started/working-guide/index.mdx

https://paste-git-featdocs-add-office-hours-sign-up-sheet.twilio-dsys.vercel.app/getting-started/working-guide

feat(docs): add office hours sign-up sheet link

---

packages/paste-website/src/components/callout/index.tsx

Adjusts Callout to use Stack instead of a top margin on CalloutText so that Callouts without CalloutHeading don't have uneven spacing.

fix(website): adjust callout to use stack

---

packages/paste-website/gatsby-config.js
packages/paste-website/src/components/ContactUsMenu.tsx
packages/paste-website/src/components/ThemeSwitcher.tsx
packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
packages/paste-website/src/pages/index.tsx

- Theme switcher
- Contact menu items
- Github link
- Home page code sandbox link

chore(website): add event tracking examples

---

packages/paste-core/components/modal/src/Modal.tsx

The Modal component has some jittering in console because our hack to fix the paddingTop on the page body is getting removed before the modal close animation completes.
Currently react-spring v9 doesn't have a mechanism to tap into `onDestroyed` like v8 had (https://github.com/pmndrs/react-spring/issues/1114#issuecomment-675076537). To be fair, this is a pretty hacky fix on our part anyways, so this shouldn't be an issue that comes up frequently.
That said, the experience is suboptimal on Console so I've gone ahead and disabled the animation on Modal close if the patch is applied.  This removes the jank at not much visual cost, since the Modal still animates in.

fix(modal): fix console-patch jank by removing animation on modal close

---

packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-libraries/dropdown/package.json
yarn.lock

Conditionally passing in controlled values didn't account for empty values. Checking for null instead will correctly pass an empty string from a piece of controlled state and not cause a switch from uncontrolled to controlled error.

fix(combobox): correctly handle passed in values to state

---

packages/paste-core/components/modal/src/Modal.tsx
packages/paste-core/components/modal/src/utils/consoleUtils.ts

The previous patch wasn't using the `useEffect` unmount mechanism by returning a function, instead relying on a re-render which only fired occasionally.  This hopefully addresses that to make the fix more versatile.

fix(modal): a possibly better console_patch fix

---

examples/create-react-app/package.json
packages/paste-core/core-bundle/package.json
packages/paste-core/core-bundle/tools/generate.js

Having to install `react-uid` manually when using only `@twilio-paste/core` is not an ideal DX. I hardcode it as a dependency for now as a fast-follow to the unbarrel PR, and in the future we will wrap the implementation with our own `@twilio-paste/uid` library package which will automatically address this issue.

fix(core-bundle): make react-uid a dependency for easier usage

---

babel.config.js
package.json
packages/paste-libraries/animation/babel.config.json
packages/paste-libraries/animation/rollup.config.js
yarn.lock

Fixes: https://github.com/twilio-labs/paste/issues/810.
Seems like the babel.config.js in our repo root isn't being picked up by our rollup-babel plugin. This fix only applies to the animation package. I plan to roll this out (and other improvements) elsewhere soon.

fix(animation-library): make sure babel is run correctly

---

packages/paste-website/gatsby-config.js

Anonymizes data sent to Google analytics and doesn't load it at all if browser has the Do Not Track flag on.
https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/#anonymize

chore(website): anonymize data sent to GA and respect DNT

---

packages/paste-core/components/list/src/index.tsx

We weren't forwarding refs to these list components, so I wrapped them in forwardRef calls. See https://github.com/twilio-labs/paste/discussions/841#discussioncomment-98397

fix(list): forward refs to component exports

---

packages/paste-core/components/combobox/__tests__/index.spec.tsx
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/combobox/src/types.ts

Due to the way groups of options are rendered, that start at a fresh index meaning you get duplicate ids across groups.
Ensure that this doesn't happen and write a test to make sure it never happens again.

fix(combobox): ensure listbox optionn ids in groups are always unique

---

lerna.json

We merged a tiny change in a *.md file and our CI published a bunch of packages (:lol:). This will prevent publishing on MD file changes.

chore: don't publish on *.md file changes

---

packages/paste-theme/src/themeProvider.tsx

Adds a prop to the Theme.Provider to manually disable animations. Useful in testing environments.

feat(theme): add prop to manually disable animations

---

.eslintignore
.gitignore
.prettierignore
packages/paste-codemods/README.md
packages/paste-codemods/__tests__/tools.spec.tsx
packages/paste-codemods/bin/cli.js
packages/paste-codemods/bin/paste-codemod.js
packages/paste-codemods/package.json
packages/paste-codemods/tools/create-package-mappings.js
packages/paste-codemods/tools/generatePackageExportsMap.js
packages/paste-codemods/transforms/__testfixtures__/barreled-to-unbarreled.input.ts
packages/paste-codemods/transforms/__testfixtures__/barreled-to-unbarreled.output.ts
packages/paste-codemods/transforms/__tests__/barreled-to-unbarreled.spec.tsx
packages/paste-codemods/transforms/barreled-to-unbarreled.js
packages/paste-core/core-bundle/tools/constants.js
packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx
packages/paste-website/src/pages/libraries/codemods/index.mdx
tsconfig.json
yarn.lock

We have added a system to allow downstream teams to run automatic code updates, called "codemods". Learn more about them here https://github.com/facebook/codemod#background
This PR creates a new `paste-codemods` folder in our monorepo that publishes the `@twilio-paste/codemods` package.
The package is structured to contain multiple "transforms", which are jscodeshift functions we can write to transform code.  The first and only transform included is the `barreled-to-unbarreled` transform, which converts imports from paste-core to the new unbarreled style (`@twilio-paste/core/button`).
The package also includes a `bin` field in the package json which points to a CLI nodejs script to make running this package easy and ergonomic for folks. This is heavily inspired (read: copied) from the …

feat(codemods): add barreled-to-unbarreled codemod

---

packages/paste-core/components/tooltip/stories/index.stories.tsx

These two tooltip stories diff everytime in chromatic. The default doesn't even include a screenshot of the tooltip, and extending the timeout before the capture to hopefully iron out the positioning differences.

chore: extend the tooltip story timeouts

---

.github/workflows/vrt_main.yml
.github/workflows/vrt_pull_request.yml
applitools.config.js

At some point applitools stopped naming batches based on branches. I wondered if it was due to the job being moved to it's own workflow, but they have also pushed out a change to how batches work. Trying to debug which broke it.

fix: applitools batches

---

packages/paste-core/layout/flex/src/index.tsx
packages/paste-core/layout/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/layout/grid/__tests__/grid.test.tsx
packages/paste-core/layout/grid/package.json
packages/paste-core/layout/grid/src/Column.tsx
packages/paste-core/layout/grid/src/Grid.tsx
packages/paste-core/layout/grid/src/types.ts
packages/paste-core/layout/grid/stories/index.stories.tsx
packages/paste-core/layout/grid/tsconfig.build.json
packages/paste-website/src/pages/layout/grid/index.mdx

Pass `equalColumnHeight` to grid to use Flexbox to stretch align content it's columns, and the columns content.
Has limitations that only a single child will work in a column, and `display: flex` collapses the child's width.

feat(grid): add ability to create equal height columns

---

packages/paste-customization/package.json
packages/paste-theme/package.json

I have no idea how the Theme package was publishing without this. The build broke for customization package publishing.
- fix(customization): add public access for npm publish
- fix(theme): add public access for npm publish

fix: missing publish access settings for npm

---

packages/paste-website/src/components/tokens-list/index.tsx

Token list on website is sorted correctly now. Before `-10` `-100` `-20`, now `-10` `20` ...`-100`

chore(website): improve token list sorting

---

packages/paste-website/src/components/tokens-list/index.tsx

Sorting font-weight tokens by value instead of name

chore(website): sort font-weight tokens by value

---

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/help-text/src/HelpText.tsx

fix(help-text): align error icon to top of text

---

.changeset/cold-chefs-cover.md
.changeset/seven-worms-return.md
.eslintrc.js
packages/paste-core/components/disclosure/__tests__/disclosure.test.tsx
packages/paste-core/components/disclosure/package.json
packages/paste-core/components/disclosure/src/Disclosure.tsx
packages/paste-core/components/disclosure/src/DisclosureContent.tsx
packages/paste-core/components/disclosure/src/DisclosureContext.tsx
packages/paste-core/components/disclosure/src/DisclosureHeading.tsx
packages/paste-core/components/disclosure/src/PropTypes.ts
packages/paste-core/components/disclosure/src/constants.ts
packages/paste-core/components/disclosure/src/index.tsx
packages/paste-core/components/disclosure/src/types.ts
packages/paste-core/components/disclosure/src/utils.ts
packages/paste-core/components/disclosure/stories/index.stories.tsx
packages/paste-website/src/pages/components/disclosure/index.mdx

chore(disclosure): update styles, add tests, promoto to beta

---

.changeset/strong-schools-draw.md
packages/paste-nextjs-template/tsconfig.json

When we use the NextJs template for the PR codesandbox build, the tsconfig was trying to inherit from the monorepo root tsconfig which didn't exist. So it broke.
This provides it's own isolated tsconfig for Codesandbox purposes

fix: pull request codesandboxes need their own tsconfig

---

packages/paste-website/src/pages/illustrations/index.mdx

- Add IT request instructions next to the link to the illustration library.
- Update external anchors to use showExternal prop
closes #1182

feat(website): add illustration library access instructions

---

packages/paste-website/src/pages/components/menu/index.mdx
packages/paste-website/src/pages/components/table/index.mdx

- Table examples: `<Th scrope="row">` --> `<Th scope="row">`
- Menu: fix Button URL (closes #1199 )

fix(website): typos on Table and Menu pages

---

packages/paste-website/src/pages/components/table/index.mdx

Removed font-family-code style from some Table examples so folks don't take that as the recommendation for showing numbers in a table (since Inter has monospace numbers already).

chore(website): remove code style from numeric Table examples

---

.changeset/brave-starfishes-agree.md
packages/paste-core/primitives/box/src/index.tsx

Adds missing datetime prop typing to box as per https://github.com/twilio-labs/paste/discussions/661

fix(box): add datetime typing

---

.changeset/cyan-radios-shop.md
.changeset/lucky-months-cheer.md
.changeset/modern-camels-deny.md
.changeset/strong-rules-deliver.md
.changeset/wise-mangos-appear.md
.vscode/settings.json
packages/paste-core/components/checkbox/src/Checkbox.tsx
packages/paste-core/components/input/src/Input.tsx
packages/paste-core/components/radio-group/src/Radio.tsx
packages/paste-core/components/radio-group/src/RadioGroup.tsx
packages/paste-core/components/select/__tests__/select.test.tsx
packages/paste-core/components/select/src/Select.tsx
packages/paste-core/components/select/stories/select.stories.tsx
packages/paste-core/components/textarea/src/TextArea.tsx
packages/paste-core/components/textarea/stories/textarea.stories.tsx
packages/paste-website/src/pages/components/checkbox/index.mdx
packages/paste-website/src/pages/components/input/index.mdx
packages/paste-website/src/pages/components/radio-group/index.mdx
packages/paste-website/src/pages/components/select/index.mdx
packages/paste-website/src/pages/components/textarea/index.mdx

Changes to form components that allow components to work with hook form libraries like: https://github.com/vnguyen94/react-hook-form-paste

fix(input): allow input to work with hook form library

---

.changeset/moody-pianos-poke.md
packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/components/button/__tests__/button.test.tsx
packages/paste-core/components/button/package.json
packages/paste-core/components/button/src/index.tsx
packages/paste-core/components/button/stories/index.stories.tsx

fix(button): improve Button handling of link behavior

---

.changeset/warm-hats-serve.md
packages/paste-core/components/paragraph/__tests__/paragraph.test.tsx
packages/paste-core/components/paragraph/src/index.tsx

Allow all global HTML attributes to be passed down to the underlying paragraph DOM element

fix(paragraph): allow global HTML attributes to be passed to p element

---

.changeset/nervous-moles-sleep.md
.changeset/stupid-zebras-wave.md
.changeset/two-humans-press.md
packages/paste-core/components/checkbox/src/CheckboxGroup.tsx
packages/paste-core/components/form/stories/form.stories.tsx
packages/paste-core/components/inline-control-group/src/InlineControlGroup.tsx
packages/paste-core/components/inline-control-group/stories/inline-control-group.stories.tsx
packages/paste-core/components/radio-group/src/RadioGroup.tsx

Taking over from https://github.com/twilio-labs/paste/pull/941
Using stack to create the spacing and general tidy up. Also adding stories to verify no regressions.

fix(inline-control-group): remove bottom spacing from last child control

---

.changeset/twenty-parrots-care.md
packages/paste-core/components/avatar/src/index.tsx
packages/paste-core/components/avatar/src/types.ts

- Fixed the size prop to make it optional
- Created a default variable for the size's default value to use in Avatar and AvatarContents components.

fix(avatar): make size optional and have default size

---

.gitignore
packages/paste-theme-designer/package.json

Netlify next build plugin requires next v10.0.6, but we use 10.0.4.
If I upgrade some weird error occurs on build and refresh of pages in dev mode. I've spent half a day trying to figure it out, but as we don't rely on SSR we can safely just statically export the site for hosting purposes.
We can address the build issues later when we start working on it again.

chore: configure netlify next support

---

.changeset/happy-phones-bow.md

Having an unescaped component in markdown means it doesn't render in the GitHub UI and breaks our website when we try to render it.
Escaping it with backticks should solve for this.

chore: escape component from changelog using markdown backticks

---

.changeset/fifty-roses-brake.md
packages/paste-core/components/avatar/src/index.tsx
packages/paste-core/components/avatar/src/types.ts
packages/paste-website/src/pages/components/avatar/index.mdx

- Added union type to AvatarProps to only allow for either `src` OR `icon` prop
- Added check for presence of both `src` AND `icon` to catch javascript users
- Fixed Avatar.propTypes and <AvatarContents /> to satisfy typescript
- Updated docs to reflect changes

chore(avatar): allow for only icon OR src prop

---

.changeset/itchy-countries-attend.md
.changeset/many-flowers-jump.md
packages/paste-core/components/combobox/stories/index.stories.tsx
packages/paste-core/components/input/__tests__/__snapshots__/input.test.tsx.snap
packages/paste-core/components/input/__tests__/input.test.tsx
packages/paste-core/components/input/src/Input.tsx
packages/paste-core/components/input/stories/input.stories.tsx
packages/paste-core/components/textarea/__tests__/textarea.test.tsx
packages/paste-core/components/textarea/src/TextArea.tsx
packages/paste-core/components/textarea/stories/textarea.stories.tsx
packages/paste-libraries/styling/src/css-function/css.ts

Fixes: https://github.com/twilio-labs/paste/issues/1305

fix(input): fixed the color of disabled input values

---

.storybook/main.js

* Resolves issue where locally referenced package dependencies (ala, "@twilio-paste/label") weren't re-building in Storybook
* Reinstates the `directory-named-webpack-plugin` in Storybook's webpack config to resolve this issue. This was dropped in our previous Storybook version migration.

fix(storybook-hot-reload): fix hot reloading for local named packages

---

.changeset/rich-poems-worry.md
packages/paste-core/primitives/box/src/index.tsx
packages/paste-core/primitives/text/src/index.tsx
packages/paste-style-props/package.json
packages/paste-style-props/src/constants.ts
packages/paste-style-props/src/proptypes/background.ts
packages/paste-style-props/src/proptypes/border.ts
packages/paste-style-props/src/proptypes/index.ts
packages/paste-style-props/src/proptypes/shadow.ts
packages/paste-style-props/src/proptypes/typography.ts
packages/paste-website/src/components/tokens-list/index.tsx
packages/paste-website/src/pages/tokens/index.mdx
tsconfig.json
yarn.lock

Filter out the deprecated design tokens from the list page.
- I tried doing this by filtering the GraphQL so I wouldn't have to do this, but for whatever reason I just can't get it to filter the date
In terms of trying to add autocomplete annotations, we can deprecate methods, arguments or props, but not specific values of those things. I even tried with a conditional  type using JSDoc syntax but it just wouldn't infer the annotation based on value.

chore(website): filter out deprecated design tokens from list

---

packages/paste-website/src/components/homepage/HomeHero.tsx
packages/paste-website/src/pages/components/anchor/index.mdx

Add a guideline about not using "click here" (from the Button vs. Anchor page) to the Anchor page.

chore(website): add "click here" guidelines to anchor doc and update "New" banner

---

.changeset/bright-pillows-kiss.md
packages/paste-core/components/checkbox/src/Checkbox.tsx
packages/paste-website/src/component-examples/CheckboxExamples.ts
packages/paste-website/src/pages/components/checkbox/index.mdx

When checked state is changed via interaction the checked prop isn't
changed, so we can't rely on it to set the color. If you do rely only on
the checked prop, you can't see the check mark when you interact with
the control.

fix(checkbox): checkmark should always have a color

---

.changeset/poor-insects-repeat.md
.storybook/preview.js
packages/paste-core/components/disclosure/src/DisclosureContent.tsx

To address this discussion topic https://github.com/twilio-labs/paste/discussions/1320
Add a background color to the disclosure content so that you can see it on a background that is not the body color.
Also add story layout for VRT to at least display each component of a background that is not the body.

fix(disclosure): add a background color to disclosure content

---

.changeset/giant-beers-draw.md
.changeset/tender-icons-obey.md
packages/paste-core/components/modal/__tests__/index.spec.tsx
packages/paste-core/components/modal/src/Modal.tsx
packages/paste-core/primitives/modal-dialog/package.json
packages/paste-libraries/animation/package.json
yarn.lock

chore(modal-dialog-primitive): upgrade reach dialog

---

.changeset/cool-actors-itch.md
packages/paste-core/components/combobox/__tests__/index.spec.tsx
packages/paste-core/components/combobox/src/Combobox.tsx

Fixes: https://github.com/twilio-labs/paste/issues/1472

fix(combobox): pass required prop to textbox

---

.changeset/beige-icons-think.md
packages/paste-core/components/disclosure/src/DisclosureHeading.tsx
packages/paste-core/components/disclosure/stories/index.stories.tsx

This PR removes the wrapper around the `{children}` in the DisclosureHeading. Generally speaking, having `flexGrow=1` on a `display block` element leads to all kinds of wacky behavior. We generally shouldn't be trying to position the children either, because developers may be attempting all kinds of things and we end up in a game of whack a mole with CSS. 
This change _should_ not have any breaking changes and makes it possible to position/layout the children any which way the developers want.

fix(disclosure): remove wrapping box around heading content

---

.changeset/fluffy-moose-remain.md
.changeset/kind-experts-unite.md
.changeset/purple-monkeys-refuse.md
.codesandbox/ci.json
packages/paste-core/components/date-picker/__tests__/index.spec.tsx
packages/paste-core/components/date-picker/build.js
packages/paste-core/components/date-picker/package.json
packages/paste-core/components/date-picker/src/DatePicker.tsx
packages/paste-core/components/date-picker/src/index.tsx
packages/paste-core/components/date-picker/src/utils.ts
packages/paste-core/components/date-picker/stories/index.stories.tsx
packages/paste-core/components/date-picker/tsconfig.json
packages/paste-core/components/form/src/shared/types.ts
packages/paste-core/components/input-box/src/InputBox.tsx
packages/paste-core/components/input-box/src/types.ts
packages/paste-core/components/input/__tests__/__snapshots__/input.test.tsx.snap
packages/paste-core/components/input/src/Input.tsx
packages/paste-core/core-bundle/.gitignore
packages/paste-core/core-bundle/package.json
packages/paste-core/core-bundle/src/date-picker.tsx
packages/paste-core/core-bundle/src/index.tsx
yarn.lock

- Added date-picker package
- Added `type="time"` to Input, Input-box, Form
- Wrote tests for Date Picker and `returnDateFormatter` func

feat(date-picker): create package

---

packages/paste-website/src/pages/components/list/index.mdx
packages/paste-website/src/pages/getting-started/design/index.mdx
packages/paste-website/src/pages/patterns/create/index.mdx
packages/paste-website/src/pages/patterns/delete/index.mdx
packages/paste-website/src/pages/patterns/empty-states/index.mdx
packages/paste-website/src/pages/patterns/index.mdx
packages/paste-website/src/pages/patterns/notifications/index.mdx
packages/paste-website/src/pages/patterns/object-details/index.mdx
packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx

There were a few broken links on the website, this PR fixes them to point to the correct paths.
Hide whitespace changes in Github to remove prettier lines:

fix(website): fix broken links

---

.changeset/tricky-spiders-matter.md
packages/paste-core/components/alert/stories/index.stories.tsx
packages/paste-core/components/disclosure/stories/index.stories.tsx
packages/paste-core/components/table/stories/index.stories.tsx
packages/paste-core/components/toast/stories/index.stories.tsx
packages/paste-core/components/truncate/src/index.tsx
packages/paste-core/components/truncate/stories/index.stories.tsx
packages/paste-core/layout/flex/stories/index.stories.tsx
packages/paste-core/layout/grid/stories/index.stories.tsx
packages/paste-core/layout/media-object/stories/index.stories.tsx
packages/paste-website/src/components/icons-list/IconTile.tsx
packages/paste-website/src/pages/components/table/index.mdx
packages/paste-website/src/pages/components/truncate/index.mdx

Added a required title `prop` to the `Truncate` component API, intended to represent the full truncated text.

chore(truncate): add required title prop to Truncate

---

packages/paste-website/src/components/ProductBadge.tsx
packages/paste-website/src/components/shortcodes/package-status-legend/index.tsx
packages/paste-website/src/components/shortcodes/pattern-header/index.tsx
packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx
packages/paste-website/src/pages/patterns/create/index.mdx
packages/paste-website/src/pages/patterns/delete/index.mdx
packages/paste-website/src/pages/patterns/empty-states/index.mdx
packages/paste-website/src/pages/patterns/notifications-and-feedback/index.mdx
packages/paste-website/src/pages/patterns/object-details/index.mdx
packages/paste-website/src/utils/types.ts

Using the system Airtable, define product suitability for certain patterns. 
Which products are a pattern suitable to be used in? Not all patterns are created equally. Not all products should use all patterns. 
This PR adds a small products callout to the patterns header to clearly indicate where a Pattern could be leveraged.
Added a 'pattern' option to the System Hierarchy column, and added a "Product Suitability" column with a multi select to the Airtable

feat(website): add product suitability to the patterns header

---

cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-website/src/components/component-overview-table/index.tsx

fix(website): conditionally render overview links if doc exists

---

.changeset/clean-owls-perform.md
.changeset/gentle-ears-sip.md
.changeset/ten-donkeys-begin.md
.codesandbox/ci.json
cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-core/components/date-picker/__tests__/index.spec.tsx
packages/paste-core/components/date-picker/src/utils.ts
packages/paste-core/components/form/src/shared/types.ts
packages/paste-core/components/input-box/src/InputBox.tsx
packages/paste-core/components/input-box/src/index.tsx
packages/paste-core/components/input-box/src/types.ts
packages/paste-core/components/input/src/Input.tsx
packages/paste-core/components/time-picker/__tests__/index.spec.tsx
packages/paste-core/components/time-picker/build.js
packages/paste-core/components/time-picker/package.json
packages/paste-core/components/time-picker/src/TimePicker.tsx
packages/paste-core/components/time-picker/src/index.tsx
packages/paste-core/components/time-picker/src/utils.ts
packages/paste-core/components/time-picker/stories/index.stories.tsx
packages/paste-core/components/time-picker/tsconfig.json
packages/paste-core/core-bundle/.gitignore
packages/paste-core/core-bundle/package.json
packages/paste-core/core-bundle/src/index.tsx
packages/paste-core/core-bundle/src/time-picker.tsx

✅ created a Time Picker package
✅ wrote tests for Time Picker
✅ made stories for Time Picker

feat(time-picker): create package

---

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx

* Runs 'Primitives' section of the doc site nav through filteredComponents fn to filter out unwanted page links.

fix(site-nav): Hide Sibling Box from site left nav

---

.github/CODEOWNERS

To set up PR auto assignment we need some teams and codeowners.
This should do the following:
- Any changes to design tokens gets a product designer and tech lead reviewer
- Any changes to any packages gets a engineer and a tech lead reviewer
- Anything else gets a tech lead reviewer

chore: first codeowners iteration

---

.changeset/cold-impalas-decide.md
.changeset/gold-mugs-float.md
packages/paste-core/components/tabs/src/TabPanel.tsx
packages/paste-core/primitives/box/__tests__/box.test.tsx
packages/paste-core/primitives/box/src/PseudoPropStyles.ts

fix(tabs): adjust TabPanel focus state

---

cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-website/src/pages/components/help-text/index.mdx
packages/paste-website/src/pages/components/input/index.mdx
packages/paste-website/src/pages/components/select/index.mdx
packages/paste-website/src/pages/components/textarea/index.mdx

Add docs page for `HelpText` component.

docs(help-text): add helptext docs page

---

.changeset/seven-moons-shop.md
packages/paste-core/components/tooltip/__test__/index.spec.tsx
packages/paste-core/components/tooltip/src/index.tsx

When cloning the child wrapped by the tooltip, we are not mixing in the child props that are provided by the consumer.
This means there can be cases where provided props are not called on the trigger element when wrapped in a tooltip as
they no longer exist when we clone it.
Spreading the children props on the tooltip before we clone means they are present when we clone using the referenceProps

fix(tooltip): prevent child props being overridden/swallowed by tooltip

---

.changeset/orange-jeans-destroy.md
.changeset/short-taxis-shout.md
packages/paste-core/components/alert-dialog/package.json
packages/paste-core/components/time-picker/__tests__/index.spec.tsx
packages/paste-core/components/time-picker/package.json

While I was working on the `pnpm` spike, I noticed we missed a dependency on `AlertDialog` and `TimePicker`. This adds those.

fix(alert-dialog): added missing date-fns dependency

---

packages/paste-website/src/pages/patterns/index.mdx

I found a typo on the patterns page.

chore(website): fix typo on patterns page

---

.github/CODEOWNERS

Setting the `@twilio-labs/design-systems-pd` team as a code owner of the SVGs means that any PRs opened that change any of the SVGs will automatically get a product designer as a required reviewer

chore: ensure changes to icon svgs are reviewed by a designer

---

packages/paste-website/src/components/homepage/HomeHero.tsx
packages/paste-website/src/pages/components/truncate/index.mdx

Updates the Truncate docs to be less strict on use cases. Addresses https://github.com/twilio-labs/paste/discussions/1695

docs(website): update truncation use case guidelines

---

packages/paste-website/functions/opengraph.ts

This PR should hopefully fix the `Invalid Request` preview cards in production.
I had this set to `2` because of Netlify's custom widget on preview deploy URLs. On prod, it is now taking screenshots too quickly and we want to wait until the page is fully loaded.

fix(website): waits longer for opengraph card previews

---

.changeset/tall-phones-rescue.md
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/combobox/src/types.ts

Address https://github.com/twilio-labs/paste/discussions/1631 where input events might be out of sync with Downshift internal state.
Because downshift isn't handling the events passed by the consumer, the data stored in e.target.value is out of sync with the internal state of Combobox. Meaning the value is the last value not, the current value.

fix(combobox): let Downshift handle all props to fix out of sync events

---

packages/paste-website/src/pages/components/label/index.mdx

Add a missing prop to the prop table

docs(label): add missing as attribute in props table

---

.changeset/lazy-pumas-reflect.md
.changeset/nervous-dingos-unite.md
packages/paste-core/primitives/box/__tests__/StyleFunctions.test.tsx
packages/paste-core/primitives/box/src/StyleFunctions.ts
packages/paste-core/primitives/text/__tests__/StyleFunctions.spec.tsx
packages/paste-core/primitives/text/src/StyleFunctions.ts

When a component was setting a variant that was not present on the element object, it would throw an error as it was trying to merge an object into undefined.
This simply checks that there is a matching variant on the element object, before it merges the styles.

fix(box): correctly handle variants that are not on the element object

---

.changeset/brave-clouds-press.md
.codesandbox/ci.json
cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-core/components/display-pill-group/__tests__/index.spec.tsx
packages/paste-core/components/display-pill-group/build.js
packages/paste-core/components/display-pill-group/package.json
packages/paste-core/components/display-pill-group/src/DisplayPill.tsx
packages/paste-core/components/display-pill-group/src/DisplayPillGroup.tsx
packages/paste-core/components/display-pill-group/src/index.tsx
packages/paste-core/components/display-pill-group/stories/index.stories.tsx
packages/paste-core/components/display-pill-group/tsconfig.json
packages/paste-core/core-bundle/.gitignore
packages/paste-core/core-bundle/package.json
packages/paste-core/core-bundle/src/display-pill-group.tsx
packages/paste-core/core-bundle/src/index.tsx

Adds a new Paste component called "DisplayPillGroup". This is the pill group component intended to be used outside of forms, for visual purposes.  Another PR will be coming soon with the "FormPillGroup" component package. 
**Why did we split these up?**
- To keep the API clear and composable; it's more obvious to use the FormPillGroup variant when within forms, than if we had named it something else.
- To reduce the bundle size when not using pills in forms.
- For accessibility; each component has different keyboard controls and semantics for screenreaders

feat(display-pill-group): add package

---

.changeset/happy-moons-unite.md
package.json
packages/paste-core/primitives/combobox/__tests__/useMultiSelectPrimitive.test.tsx
packages/paste-core/primitives/combobox/package.json
packages/paste-core/primitives/combobox/src/index.tsx
packages/paste-core/primitives/combobox/stories/index.stories.tsx
packages/paste-website/src/component-examples/ComboboxPrimitiveExamples.ts
packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx
yarn.lock

feat(combobox-primitive): expose multiple selection hook

---

.changeset/orange-brooms-applaud.md
.codesandbox/ci.json
cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-core/components/form-pill-group/__tests__/index.spec.tsx
packages/paste-core/components/form-pill-group/build.js
packages/paste-core/components/form-pill-group/package.json
packages/paste-core/components/form-pill-group/src/FormPill.tsx
packages/paste-core/components/form-pill-group/src/FormPillGroup.tsx
packages/paste-core/components/form-pill-group/src/PillCloseIcon.tsx
packages/paste-core/components/form-pill-group/src/index.tsx
packages/paste-core/components/form-pill-group/src/useFormPillState.tsx
packages/paste-core/components/form-pill-group/stories/index.stories.tsx
packages/paste-core/components/form-pill-group/tsconfig.json
packages/paste-core/core-bundle/.gitignore
packages/paste-core/core-bundle/package.json
packages/paste-core/core-bundle/src/form-pill-group.tsx
packages/paste-core/core-bundle/src/index.tsx

The second pill group package ([see the first package PR here](https://github.com/twilio-labs/paste/pull/1800)).
The FormPillGroup is intended to be used within form elements.
**Why did we split these up?**
- To keep the API clear and composable; it's more obvious to use the FormPillGroup variant when within forms, than if we had named it something else.
- To reduce the bundle size when not using pills in forms.
- For accessibility; each component has different keyboard controls and semantics for screenreaders

feat(form-pill-group): add package

---

.changeset/many-dryers-punch.md
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/select/src/Select.tsx
packages/paste-core/components/textarea/src/TextArea.tsx

- fix(combobox): must have a default element name
- fix(select): must have a default element name
- fix(textarea): must have a default element name
- chore: combobox, select and textarea changeset

fix: default prop types for element name in combobox, select and textarea

---

.changeset/smart-stingrays-sit.md
.storybook/preview.js
packages/paste-core/components/skeleton-loader/__tests__/index.spec.tsx
packages/paste-core/components/skeleton-loader/src/index.tsx
packages/paste-core/components/skeleton-loader/stories/index.stories.tsx

Enable skeleton loader customization via the customization provider

feat(skeleton-loader): add ability to customize

---

.changeset/cool-cats-fly.md
packages/paste-core/components/tabs/__tests__/tabs.test.tsx
packages/paste-core/components/tabs/src/Tab.tsx
packages/paste-core/components/tabs/src/TabList.tsx
packages/paste-core/components/tabs/src/TabPanel.tsx
packages/paste-core/components/tabs/src/TabPanels.tsx
packages/paste-core/components/tabs/src/Tabs.tsx
packages/paste-core/components/tabs/src/TabsContext.tsx
packages/paste-core/components/tabs/src/utils.ts
packages/paste-core/components/tabs/stories/index.stories.tsx

Add `element` to the tab package components, to allow for customization.

feat(tabs): add element customization

---

.changeset/rotten-parrots-hug.md
.changeset/tame-rabbits-collect.md
packages/paste-core/components/card/src/index.tsx
packages/paste-core/components/disclosure/__tests__/disclosure.test.tsx
packages/paste-core/components/disclosure/src/Disclosure.tsx
packages/paste-core/components/disclosure/src/DisclosureContent.tsx
packages/paste-core/components/disclosure/src/DisclosureHeading.tsx
packages/paste-core/components/disclosure/src/PropTypes.ts
packages/paste-core/components/disclosure/src/types.ts
packages/paste-core/components/disclosure/stories/index.stories.tsx

Added customization capability to the disclosure package. Lingering question of why testing for backgroundColor doesn't seem to be working, which is commented out of the test file.

feat(disclosure): add element customization

---

.changeset/clean-planets-provide.md
packages/paste-core/components/modal/__tests__/customization.spec.tsx
packages/paste-core/components/modal/__tests__/index.spec.tsx
packages/paste-core/components/modal/src/Modal.tsx
packages/paste-core/components/modal/src/ModalBody.tsx
packages/paste-core/components/modal/src/ModalFooter.tsx
packages/paste-core/components/modal/src/ModalFooterActions.tsx
packages/paste-core/components/modal/src/ModalHeader.tsx
packages/paste-core/components/modal/src/ModalHeading.tsx
packages/paste-core/components/modal/stories/customization.stories.tsx

feat(modal): customization

---

.github/workflows/publish.yml
package.json

Yarn 3 has a slightly different lockfile behaviour where internal peer dependencies are now listed in the lockfile.
So when `changset version` runs and bumps the version numbers of packages based on the changes, the lockfile is now out of date. This means any `yarn install --immutable` will fail in all CI runs after you merge in the "version" PR and prevent the release from happening.
This adds a custom version command, which after versioning the packages, runs `yarn install --mode=update-lockfile` which will only update the lockfile. Which can then be committed in the Versions PR.
Also bumped Yarn to latest version, because why not. 🤷🏼

fix: changeset publish script needs to commit lockfile

---

.changeset/giant-ladybugs-promise.md
packages/paste-core/components/data-grid/src/DataGrid.tsx
packages/paste-core/components/data-grid/src/DataGridContext.tsx
packages/paste-core/components/data-grid/src/table/Tr.tsx
packages/paste-core/components/data-grid/stories/components/ComposableCellsDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/KitchenSinkDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/LoadingDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/PaginatedDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/PlainDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/SelectableRowsDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/SortableColumnsDataGrid.tsx
packages/paste-website/src/component-examples/DataGridExamples.ts
packages/paste-website/src/pages/components/data-grid/index.mdx

Previously the `striped` prop wasn't doing anything. This fixes the `striped` prop and updates the docs so it works correctly on Data Grid.
Updated the Loading story to use `striped={false}` so we can VRT it on one of our existing examples.

fix(data grid): make 'striped' prop work

---

cypress.json

Prevents cypress from sending google analytics events by blocking the host.  
In the future, we can change this to test the events are firing correctly by [stubbing or intercepting](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__google-analytics).   For now however, let's just keep our data sane.

test(website): block google analytics requests in cypress test

---

.changeset/stale-guests-repeat.md
packages/paste-core/components/popover/src/PopoverContainer.tsx

Fixes https://github.com/twilio-labs/paste/discussions/1978 and https://github.com/twilio-labs/paste/discussions/2006 and https://github.com/twilio-labs/paste/discussions/1870
Removes the wrapping Box in PopoverContainer. PopoverContainer is simply a context provider, like Theme.Provider, and that wrapping Box just added styling issues.

fix(popover): remove popovercontainer Box wrapper

---

cypress/integration/e2e/link-checker/index.spec.ts
packages/paste-website/src/components/Roadmap/Roadmap.tsx

This PR fixes broken links on the Roadmap page due to a missing `#` character that would route the user to a broken page rather than a page hash.
I also improve the broken link checker, providing the calling route to the HTTP header object so we can see from which file the error originated:
Additionally, I removed the contents of the IGNORE_LIST in the broken link checker since that list is now stale.

fix(website): broken roadmap link

---

.github/workflows/on_merge_to_main.yml

Merges to main were failing, looks like a typo in the recent changes

fix: typo in prerelease script in ci

---

packages/paste-website/src/components/customization-landing-page/image-slider/ImageSlider.tsx

Currently when interacting with the Image Slider component, when selection pushes past the boundaries of the container, a text selection effect will appear over the images.
This change prevents image selection while user interacts with the Image Slider component.

fix(slider-select): fix inadvertent image selection when interacting with the Image Slider

---

.changeset/eight-cars-breathe.md
packages/paste-core/components/data-grid/src/DataGridCell.tsx
packages/paste-core/components/data-grid/stories/components/PlainDataGrid.tsx
packages/paste-website/src/pages/components/data-grid/index.mdx

Fixing inability to right-align data grid cells from https://github.com/twilio-labs/paste/discussions/2019

feat(data-grid): add textAlign prop to DataGridCell

---

.github/workflows/on_merge_to_main.yml

Was overly protective on the merge to main workflow steps. We actually only want to prevent versioning merge commits running Chromatic. 
The other steps should still run.

fix: only prevent chromatic running on version merge commits

---

packages/paste-website/src/pages/patterns/empty-states/index.mdx
packages/paste-website/src/pages/patterns/object-details/index.mdx
packages/paste-website/src/pages/patterns/status/index.mdx

Fixing inconsistent and missing quotes on website's pattern import codeblocks. If copy pasted (which is the intended use), can be confusing to debug.

fix(website): component import codeblock missing quotes

---

.changeset/nine-pugs-work.md
packages/paste-design-tokens/__tests__/__snapshots__/index.test.tsx.snap
packages/paste-design-tokens/tokens/themes/dark/global/text-color.yml

Changed the alias that Dark mode's color-text-icon points to from gray-10 to gray-60 to allow for hover state differentiation when used concurrently w/ color-text.

chore(tokens): change color-text-icon in Dark mode

---

.changeset/perfect-countries-speak.md
packages/paste-core/components/badge/__tests__/index.spec.tsx
packages/paste-core/components/badge/src/BadgeWrapper.tsx
packages/paste-core/components/badge/src/hooks.tsx
packages/paste-core/components/badge/src/index.tsx
packages/paste-core/components/badge/src/styles.ts
packages/paste-core/components/badge/src/types.ts
packages/paste-core/components/badge/src/utils.ts
packages/paste-core/components/badge/stories/index.stories.tsx

If the Badge is focusable, the ref is passed to the wrapper component instead of the span.
Also export the BadgeProps type.

Badge ref fix

---

.changeset/little-meals-thank.md
packages/paste-core/components/button/__tests__/button.test.tsx
packages/paste-core/components/button/src/DestructiveIconButton.tsx
packages/paste-core/components/button/src/PrimaryIconButton.tsx
packages/paste-core/components/button/src/SecondaryIconButton.tsx
packages/paste-core/components/button/src/index.tsx
packages/paste-core/components/button/src/proptypes.ts
packages/paste-core/components/button/src/types.ts
packages/paste-core/components/button/stories/index.stories.tsx
packages/paste-website/src/pages/components/button/index.mdx

Added icon-specific variants. Working on the docs changes now.

feat(button): add icon-specific variants

---

packages/paste-website/src/components/site-wrapper/SiteBody.tsx
packages/paste-website/src/html.tsx

* Our scrolling element was lacking a declaration of position: relative, leaving certain focus events tied into the body in Chrome, and causing rendering issues.
* This change introduces that css declaration. It also removes a previous attempt to fix this bug by suppressing overflow on the site body.

fix(site-layout): add position relative on scrolling container

---

tools/utils/runCmd.js

fix: typo in runCmd command description

---

tools/build/esbuild.js

I'm not sure if this will actually be any better, but if possible log the error we get in esBuild to help identify the root of this intermittent build bug.

chore: log build errors to help debug intermittant issue

---

.changeset/eleven-pets-applaud.md
packages/paste-core/components/alert/src/index.tsx
packages/paste-core/components/modal/src/ModalHeader.tsx
packages/paste-core/components/popover/src/Popover.tsx
packages/paste-core/components/toast/__tests__/toaster.spec.tsx
packages/paste-core/components/toast/src/Toast.tsx

[Ticket](https://issues.corp.twilio.com/browse/DSYS-2269)

chore: replace close icon with `secondary_icon` variant in Alert, Modal, Popover, Toast

---

packages/paste-website/src/components/CopyButton.tsx
packages/paste-website/src/components/icons-list/IconCard.tsx
packages/paste-website/src/components/shortcodes/live-preview/CodeBlockOverlayShadow.tsx
packages/paste-website/src/components/shortcodes/live-preview/index.tsx
packages/paste-website/src/components/site-wrapper/sidebar/SidebarAnchor.tsx
packages/paste-website/stories/LivePreview.stories.tsx

This change improves the codeblocks on our website by starting the code portion closed, adding a view/hide code button, and adding a copy button. This also improves the general styling.

feat(website): update website codeblocks design

---

.changeset/tricky-rules-wonder.md
packages/paste-core/components/label/src/Label.tsx

For the label component - when the label has `as="legend"` and it is not `disabled`, the cursor should be default.

fix(label): default cursor when label is a legend

---

packages/paste-website/src/components/shortcodes/live-preview/index.tsx

This PR fixes a recently introduced bug on the doc site that would prevent code examples from overflowing the preview container (video attached).
https://user-images.githubusercontent.com/1592327/144492980-b9a6d6b9-8832-4826-bf15-e7dddd83647d.mov
For some reason, the `overflow-x` CSS rule is applying a un-overwriteable `overflow-y: hidden`, and I can't quite work it out at this time. By removing the `overflow-x`, I revert the recent improvement of having a horizontal scrollbar (like for the tables examples), but I restore the old expected behavior.

fix(website): fix overflow on codeblocks, revert overflowX fix

---

.changeset/fluffy-beers-help.md
packages/paste-color-contrast-utils/src/utils.ts
packages/paste-color-contrast-utils/tsconfig.json

Taking over from https://github.com/twilio-labs/paste/pull/2106, thanks for the contribution @stanlemon
This is so all the tests runs and checks pass that are dependent on secrets.

fix: default imports for JSON for webpack 5 compatibility

---

.changeset/serious-bulldogs-cheer.md
packages/paste-core/components/heading/src/PropTypes.ts
packages/paste-core/components/heading/src/index.tsx
packages/paste-core/components/heading/src/types.ts
packages/paste-website/src/components/Heading.tsx
packages/paste-website/src/components/Roadmap/Roadmap.tsx
packages/paste-website/src/pages/components/heading/index.mdx
packages/paste-website/stories/AnchoredHeading.stories.tsx

Changes the link on the page section headers from the "#" character to the LinkIcon icon.

chore(website): change page section link to icon

---

.changeset/pretty-turkeys-decide.md
packages/paste-style-props/src/constants.ts
packages/paste-style-props/tsconfig.json
tsconfig.json

* Following #2106 / #2107, we noticed there was one more instance of a JSON default import in the style-props package.
* This change addresses that remaining instance, updating the import and the tsconfig to allow esModuleInterop

Fix: style props default import

---

packages/paste-website/src/components/icons/PasteIcon.tsx
packages/paste-website/src/components/icons/PasteIconPride.tsx
packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderLogo.tsx

* Makes full Paste logo on the website clickable
* Adds hover effect for logo swapping
* Updates logo UI to match Figma design

feat(logo-link): make entire logo clickable, add hover

---

.changeset/little-bottles-scream.md
.danger/changesets-that-need-core-check.ts
packages/paste-core/core-bundle/tsconfig.json

Taking over from #2062, thanks for the contribution @abereghici
This is so all the tests runs and checks pass that are dependent on secrets.

chore(core-bundle): fix incorrect tsconfig extend path

---

packages/paste-website/src/pages/introduction/for-designers/design-guidelines/index.mdx

Because the design guidelines page moved in the IA updates, the image paths broke (see: https://paste.twilio.design/introduction/for-designers/design-guidelines/)
Checked all the other pages with images and their paths are still correct.

fix(website): image paths

---

packages/paste-website/src/pages/components/textarea/index.mdx

Removed duplicated props from site documentation for TextArea component

fix: remove duplicated onChange props from textarea example

---

.changeset/afraid-dancers-confess.md
packages/paste-core/components/breadcrumb/__tests__/breadcrumb.spec.tsx
packages/paste-core/components/breadcrumb/src/index.tsx
packages/paste-website/src/pages/components/breadcrumb/index.mdx

In Breadcrumb:
- Before: props were spread onto the Box as list item element. 
- In this PR: props are spread onto either the Anchor or Text element inside of the Box list item. This was done to match the component's presentation: BreadcrumbItem looks like an Anchor, so a data-testid on BreadcrumbItem should map onto the Anchor component.
Docs site:
- Section added to the Breadcrumb docs to indicate how to use routing, which is analogous to Anchor routing. Along these same lines, there's a link to a codesandbox that uses Breadcrumb alongside React Router. Would love eyes on this codesanbox, since the one for Anchor routing has had like +11k views 👀 
Open questions

fix(breadcrumb): spread props on child Anchor or Text element

---

packages/paste-website/src/components/site-wrapper/index.tsx

This PR changes the graphql query for Patterns that are rendered to the sidenav on the website. Previously we were querying for all Patterns not "in development" and I added the filter "has documentation: true" so that pages will only appear on the side nav once that column is marked in the Airtable.

chore: only query patterns with docs

---

packages/paste-website/src/component-examples/PrivacyPatternExamples.tsx
packages/paste-website/src/pages/patterns/privacy/index.mdx

Fixes a bug that Lee found, I removed the link from the do/don't text because it won't render.

fix(website): remove link from dodont

---

.github/opened-pr-labeler.yml
.github/workflows/on_pull_request_open.yml
.kodiak.toml

Enable the kodiak merge queue.
Add a `🚀 merge it!` label to add a pr to the queue once you are happy with it.
Add `Status: WIP` or `Status: Do Not Merge` to block / override.
For the future, I've added a rule for dependencies via Renovate

chore: enable kodiak merge queue

---

.github/workflows/on_merge_to_main.yml
.github/workflows/on_pull_request.yml

Changsets is complaining about not having a version set, after they released v1.
When tracking render perf, we are currently using the wrong commit sha. So it doesn't match the commit in the PR commit history, which makes looking up the data per commit, very difficult as it's stored under a completely different sha

chore: pin changeset version. set correct pr commitsha

---

.changeset/fluffy-sheep-try.md
packages/paste-core/components/toast/__tests__/index.spec.tsx
packages/paste-core/components/toast/src/Toast.tsx
packages/paste-core/components/toast/src/propTypes.ts
packages/paste-core/components/toast/src/types.ts
packages/paste-core/components/toast/stories/index.stories.tsx
packages/paste-website/src/component-examples/ToastExamples.tsx
packages/paste-website/src/pages/components/toast/index.mdx

feat(toast): add i18n props

---

.changeset/chilly-insects-smell.md
.changeset/hungry-clocks-count.md
.changeset/itchy-lions-switch.md
packages/paste-core/components/alert/__tests__/index.spec.tsx
packages/paste-core/components/alert/src/index.tsx
packages/paste-core/components/data-grid/__tests__/index.spec.tsx
packages/paste-core/components/data-grid/src/DataGridHeaderSort.tsx
packages/paste-core/components/data-grid/stories/components/I18nDataGrid.tsx
packages/paste-core/components/data-grid/stories/components/constants.ts
packages/paste-core/components/data-grid/stories/index.stories.tsx
packages/paste-core/components/toast/__tests__/index.spec.tsx
packages/paste-core/components/toast/src/Toast.tsx
packages/paste-website/src/pages/components/data-grid/index.mdx

feat(Data Grid): add i18n props

---

.changeset/thin-mangos-report.md
packages/paste-core/components/badge/src/index.tsx

Took out the specificity of the icon color for the error counter variant; it now inherits its color.

fix(badge): adjust error counter icon color

---

.changeset/curvy-hounds-yawn.md
packages/paste-core/components/select/src/Select.tsx

Updates the background color of Select to `colorBackgroundBody` so that the Select doesn't look disabled. Updates a change from PR #2242 to fix an issue found in Discussion #2305.

chore(select): set background color

---

.changeset/mean-starfishes-share.md
packages/paste-core/components/spinner/src/index.tsx

When up dating the spinner title requirements we forgot to update the prop types to go with it.
It is hard to tell when prop types don't match types as we don't explicitly check them anywhere.
This became visible in the newer jest setup.

fix(spinner): match title prop types to types

---

.changeset/spotty-lobsters-impress.md

Right now, because styling library is still a v0.x.x, a minor update will cause a range mismatch, and trigger a major version bump for everything down the dependency tree. This is a little bit of a limitation of changesets versioning approach to peer dependencies. If it was a v1.x.x this wouldn't happen with a minor.
Ideally, we wouldn't trigger a major version bump just for that right now.  see https://github.com/twilio-labs/paste/pull/2314
We can address all non-alpha packages, not being v1.x.x in a later PR to prevent further instances of this.

chore: adjust styling library changeset to prevent sweeping major versions

---

.changeset/loud-bags-jog.md
packages/paste-codemods/tools/.cache/mappings.json
packages/paste-core/components/combobox/__tests__/index.spec.tsx
packages/paste-core/components/combobox/src/Combobox.tsx

Issue reported: [Issue 2308](https://github.com/twilio-labs/paste/issues/2308)
**tl;dr** Adds a conditional guard to a side effect hook that syncs virtual scroll position with current highlighted index when the combobox has grouped items.
Grouped comboboxes are not yet virtualized because we cannot yet do so accessibly. The main component ([Combobox.tsx](https://github.com/twilio-labs/paste/pull/2335/files#diff-22b2d509777ec919245d83593056eb5d0c5ac23808f3b543b288425b985cb360L106)) was running a side effect (`useEffect`) that syncs the virtualized list position according to the highlighted index. This caused increasingly erratic scrolling behavior (with continued scrolling) because the scrolling function is not "calibrated" correctly for the non-virtualized grouped list.
To resolve this …

fix(combobox): grouped combobox scroll

---

.changeset/eleven-mice-repair.md
packages/paste-core/components/alert/src/index.tsx
packages/paste-core/components/modal/src/ModalHeader.tsx
packages/paste-core/components/popover/src/Popover.tsx
packages/paste-core/components/toast/src/Toast.tsx

Hover states for the close icons on our components weren't showing up; as conjectured in the ticket, this is because they were being overwritten by color props in the CloseIcon components that were left behind from the previous implementation (before the `secondary_icon` variant in button). Taking those props out fixes this.

fix: correct close icon hover state

---

.storybook/main.js
package.json
packages/paste-core/components/alert/stories/index.stories.tsx
packages/paste-core/components/anchor/stories/index.stories.tsx
packages/paste-core/components/card/stories/index.stories.tsx
packages/paste-core/components/heading/stories/index.stories.tsx
packages/paste-core/components/input/stories/input.stories.tsx
packages/paste-core/components/select/stories/select.stories.tsx
packages/paste-core/components/skeleton-loader/stories/index.stories.tsx
packages/paste-core/components/spinner/stories/index.stories.tsx
packages/paste-core/components/textarea/stories/textarea.stories.tsx
packages/paste-core/components/tooltip/stories/index.stories.tsx
packages/paste-core/layout/aspect-ratio/stories/index.stories.tsx
packages/paste-core/layout/flex/stories/index.stories.tsx
packages/paste-core/layout/grid/stories/index.stories.tsx
packages/paste-core/layout/media-object/stories/index.stories.tsx
packages/paste-core/layout/stack/stories/index.stories.tsx
packages/paste-core/primitives/box/stories/index.stories.tsx
packages/paste-core/primitives/modal-dialog/stories/index.stories.tsx
packages/paste-core/primitives/text/stories/index.stories.tsx
packages/paste-icons/stories/index.stories.tsx
tools/plop-templates/component-stories.hbs
yarn.lock

* Removes deprecated Storybook knobs from dependencies, config, and all stories that had been using them.
* In certain cases (eg: Alert, Heading, Input), we removed stories which were built to be primarily used with Knobs controls.
* In other cases (eg: Anchor, Card), we simply removed the Knobs controlled variables and replaced the values with the declared defaults.
* Removes Knobs references from plop template.
* PR also removes the Knobs addon from the Storybook config, and the Knobs dependency in our package.json.

chore(remove-knobs): Remove Storybook Knobs

---

.github/workflows/track-workflow-metrics.yml

Track some event data in PRs about their workflow jobs and step in GH actions when:
- A workflow completes
- PR open or closed
- Commit pushed
It should be noted the data pushed to Datadog, differs per event type as they are tracking different things. https://github.com/int128/datadog-actions-metrics#metrics-for-workflow_run-event
**NOTE:** I'm not seeing workflow data being posted to DD yet, because of this caveat on the workflow_run event in the Github docs:
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
So, until this is merged, no workflow data. Frustrating

chore: track github actions metrics

---

.changeset/fifty-snails-end.md
packages/paste-core/components/tabs/src/Tab.tsx
packages/paste-core/components/tabs/src/TabList.tsx
packages/paste-core/components/tabs/src/Tabs.tsx

Setting orientation to undefined for Reakit's keyboard control (https://reakit.io/docs/tab/#usetabstate)

fix(tabs): enable left right arrows on vertical tabs

---

packages/paste-website/src/components/homepage/HomeHero.tsx

Quick fix to the job add url, because we reposted it and the url changed.

fix: incorrect url to the designer role after reposting

---

packages/paste-website/src/pages/core/libraries/index.mdx

Due to our temporary HAP we are not able to pick up the work of adding a copy to clipboard pattern to our docs website. This(these) commit(s) add a link to the library source code, along with some brief context on how we use it.
> <img width="842" alt="Screen Shot 2022-05-25 at 3 14 21 PM" src="https://user-images.githubusercontent.com/18120906/170359330-e715d437-1db3-40d3-a030-acc7fc3e66aa.png">

chore(website): add link to our copy-to-clipboard library to website

---

packages/paste-website/src/component-examples/ComboboxExamples.ts
packages/paste-website/src/pages/components/combobox/index.mdx

Fix a minor issue with our combobox examples referencing the overall lodash package.

fix: combobox examples using a missing lodash dep

---

.changeset/itchy-poems-promise.md
packages/paste-core/components/avatar/src/index.tsx
packages/paste-core/components/avatar/src/types.ts
packages/paste-website/src/pages/components/avatar/index.mdx

Made for: https://github.com/twilio-labs/paste/discussions/2437
We want to allow users to pass both src and icon so that they can display one or the other depending on if the image loads correctly.
This PR includes:
* updated AvatarProps
* updated Avatar prop types
* note on the docs site that if both src and icon are passed, the avatar will display the icon

chore(avatar): allow both src and icon prop to be passed

---

packages/paste-website/src/pages/components/textarea/index.mdx

I spelled resizable wrong on the website 🤦🏽  Wanted to fix it before sharing the link in the newsletter.

chore: fix resizable spelling

---

.changeset/odd-pumpkins-count.md
packages/paste-core/components/truncate/src/index.tsx
packages/paste-core/components/truncate/stories/index.stories.tsx

Currently, there is a bug where if you put a Truncate component where it pushes the container its in down and it makes it look like there's extra padding. 
Before:
After:
* sets `verticalAlign: 'bottom'` to fix how the Truncate contents are aligned
* sets `textDecoration: 'inherit'` because I noticed that the Anchor text isn't underlined when it is truncated
* adds a `TruncateInAnchor` story
When you set `display: 'inline-block'`, `verticalAlign` defaults to `'baseline'` [which behaves differently between HTML elements and browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#values_for_inline_elements) and can end up looking weird.
Instead, I set it to `'bottom'`, which aligns the content to the bottom of the entire line. To confirm this was correct, I checked that …

chore(truncate): fix alignment

---

packages/paste-style-props/__tests__/propValidator.test.ts
packages/paste-style-props/__tests__/responsivePropValidator.test.ts

Currently, one of the `ResponsivePropValidator` is missing unit tests. This prop validator takes a prop type and then makes the prop type either one instance of that type or an array of that type.
Example:
* the width prop can either be a string or number
* the responsive width prop can be a string, number, or an array of strings/numbers
Creates `isDeprecatedTheme.spec.ts` file which tests that the validator allows and throws errors correctly.
The test mocks `console.error` and checks that it has been called the right amount of times after each time `checkPropTypes` runs. 
* danger says I need a changeset, but I disagree because this is just adding a test
> All third-party contributors acknowledge that any contributions they provide will be made under the same …

chore: add responsivePropValidator test

---

.changeset/smart-files-kiss.md
packages/paste-core/components/chat-log/__tests__/chatLog.spec.tsx
packages/paste-core/components/chat-log/src/ChatLog.tsx
packages/paste-core/components/chat-log/src/ChatMessage.tsx
packages/paste-core/components/chat-log/src/index.tsx
packages/paste-core/components/chat-log/stories/index.stories.tsx

The ChatLog package doesn't actually have a ChatLog component !!
* add a ChatLog component and relevant types
* replace <Box as="ul"> in kitchen sink story and accessibility tests with the chatLog
* add a ScrollingChatLog story that is the same as kitchen sink but with a maxHeight and overflowY='scroll'
* add chatLog tests and customization tests
* update ChatMessage so the last one in the log has no padding on the bottom

feat: add ChatLog component

---

packages/paste-website/src/pages/components/spinner/index.mdx

Issue: Spinner is using `color-text` and `icon-size-20`, but the [doc site wording](https://paste.twilio.design/components/spinner#default) makes it sound like it's using `color-text-icon`.
Change from:
> The default Spinner settings are using the default icon size and color, which is designed to match our default text size and color.
to
> The default Spinner uses the default text color (`color-text`) and icon size (`icon-size-20`), which is meant to be paired with our default text size.
Preview: https://deploy-preview-2516--paste-docs.netlify.app/components/spinner#default

fix(Spinner docs): reword default icon size and color docs

---

.vscode/extensions.json

* Removes deprecated "Bracket Pair Colorizer" extension from VS Code extensions list.
* Stops VS Code from giving the deprecated warning when opening Paste.
* Per [their repo](https://github.com/CoenraadS/BracketPair#readme), this functionality is now native to VSCode.

chore: remove deprecated VSCode extension

---

packages/paste-design-tokens/formatters/__tests__/__snapshots__/common.ts.spec.ts.snap
packages/paste-design-tokens/formatters/__tests__/common.ts.spec.ts
packages/paste-design-tokens/formatters/__tests__/gatsby.json.spec.ts

This PR adds a snapshot test for common.ts. It's taken directly from the test for es6.
- should this test and other formatter tests be changed to reflect that they are now ts files?
-  the [ticket](https://issues.corp.twilio.com/browse/DSYS-3382) this work is taken from specifies adding a snapshot for the gatsby.json formatter as well, but that one was already present. Wanted this to be known in case it was supposed to be something else?

chore: add snapshot test for formatter

---

packages/paste-website/src/pages/components/button/index.mdx

Improve the `rounded_small` size example on the Button page to be more realistic and provide more clarity on when these buttons should be used.

chore(website): improve small_rounded button example

---

packages/paste-website/src/components/tokens-list/index.tsx
packages/paste-website/src/components/tokens-list/token-card/index.tsx

chore(website): token list performance improvements

---

packages/paste-website/src/components/tokens-list/token-card/token-example/index.tsx

* Cancels default border radius on the square sizing token examples (the small ones looked like circles)

feat(tokens-page): remove border-radius from square size token examples

---

packages/paste-website/src/components/tokens-list/token-card/token-example/BoxExample.tsx
packages/paste-website/src/components/tokens-list/token-card/token-example/index.tsx

* Introduces ability to set a height prop on the Token BoxExample
* Sets shorter height for pill radius token to make it look more pill-like

feat(tokens-page): make pill radius example more pill like

---

.changeset/sour-buckets-care.md
packages/paste-core/components/form-pill-group/src/FormPill.styles.ts

One liner fix for this issue: https://www.loom.com/share/3eb7d0c6b68c4846a4407fc1e3aa52e7
-____-

fix: text color of deafult variant when selected + hover

---

.github/workflows/on_pull_request_cypress.yml

To be able to create a branch protection rule ensuring cypress VRT is run before merge, give it a unique name so it can be targetted.
- Makes sure the cypress group name is different from the non-vrt group name `Paste Actions with VRT Parallel`

chore: name cypress vrt job uniquely so it can be a required check

---

.github/CODEOWNERS
.github/workflows/on_pull_request_open.yml

This PR does the following things:
- Ensures the group @twilio-labs/design-systems-pd is assigned as a reviewer on any content changes.
- Ensures the group @twilio-labs/design-systems-pd is only assigned as a review when the design token values are changed in the yaml file, not everything in the design token directory which include engineering tasks.
- Corrects the base review assignee as the engineering group, based on a typo.
- Auto assigns the author as the assignee when a PR is created.

chore: code owners improvement, auto assignee

---

cypress/integration/token-list/index.spec.ts
packages/paste-website/src/components/tokens-list/token-card/index.tsx
packages/paste-website/stories/TokenCard.stories.tsx

[[DSYS-3447](https://issues.corp.twilio.com/browse/DSYS-3447)] This PR affects the layout within the Token Card in the Tokens List page. Changes include:
- Set up two more break points for `TokenCardValue` component. This change allows for the right hand side nav to be used in more window sizes. You can see the new behavior from this change [in this video](https://www.loom.com/share/8edca1b57ca7421d9dc3e2eb28e7b452).
- Added a `maxWidth` to the Box surrounding the token values. Without a maxWidth value, some token's values that were extremely long (mainly font-family tokens) pushed the token name text to be much too small. 
The `maxWidth` value is currently set to `size20`. Originally I chose `size30`, but certain screen widths still made font-family token names too squished. Now at …

chore(website): add breakpoints, maxWidth

---

.changeset/beige-plums-wonder.md
packages/paste-core/primitives/box/__tests__/box.test.tsx
packages/paste-core/primitives/box/src/SafelySpreadProps.ts
packages/paste-core/primitives/box/src/index.tsx
packages/paste-core/primitives/box/src/types.ts
packages/paste-style-props/src/grid.ts
packages/paste-style-props/src/index.ts
packages/paste-style-props/src/types/grid.ts
packages/paste-style-props/src/types/index.ts

Adds CSS Grid to the Style Props and Box packages.
Since we already have `rowGap` and `columnGap` defined in the `space` category for Flex usage, I didn't bother adding them or moving them into `Grid`. The old version of those CSS rules were `grid-row/column-gap` but modern browsers all omit the `grid` prefix so this works out anyways.

feat(box, style-props): enable css grid style props

---

packages/paste-website/src/components/tokens-list/ScrollToTopLink.tsx
packages/paste-website/src/components/tokens-list/index.tsx

[[DSYS-3177]](https://issues.corp.twilio.com/browse/DSYS-3177)
Scroll to top link (styled as overlayed secondary variant button [per the figma spec](https://www.figma.com/file/gHnoNWHbAKjMSjM02T8R3f/Design-Tokens?node-id=274%3A31954))
https://user-images.githubusercontent.com/109178184/186449442-953b4a89-4057-4300-8d23-7343710fb060.mov

feat(tokens-page): add ScrollToTopLink UI

---

packages/paste-website/src/components/homepage/HomeHero.tsx

Update the homepage link to point to the correct page

fix: link to tokens list on homepage

---

internal-docs/engineering/developing-locally.md

Changes:
1. The nested list items needed 4 spaces because the last nested item wouldn't nest with only 3 spaces.
2. Swapped NVM installation instructions to link to https://github.com/nvm-sh/nvm#installing-and-updating
3. Added "Connecting to Github with SSH" as a prerequesite: https://docs.github.com/en/authentication/connecting-to-github-with-ssh
4. Minor punctuation and text formatting.

chore(internal docs): adding more prerequisites to the developing locally doc

---

.changeset/olive-peas-end.md
packages/paste-core/components/help-text/src/HelpText.tsx
packages/paste-core/components/help-text/stories/input.stories.tsx
packages/paste-website/src/pages/components/help-text/index.mdx

[DSYS-3469](https://issues.corp.twilio.com/browse/DSYS-3469)
Adds `warning` and `success` variants to the Help Text component. Also updates the docs and stories.
Out of scope: update Switch, Radio, and Checkbox to accept help text variants other than default. Will address when requested.

feat(help-text): add success and warning variants

---

.changeset/old-paws-relate.md
packages/paste-core/components/combobox/src/Combobox.tsx
packages/paste-core/components/combobox/src/extractPropsFromState.tsx
packages/paste-core/components/combobox/src/types.ts
packages/paste-core/components/combobox/stories/index.stories.tsx
packages/paste-website/src/component-examples/ComboboxExamples.ts
packages/paste-website/src/pages/components/combobox/index.mdx

This is a super annoying bug in Downshift that's been open for 2 years. https://github.com/downshift-js/downshift/issues/1108
They actually, kind of allude to it here in the Github docs https://github.com/downshift-js/downshift#oninputvaluechange, where they link to some old issue and some hints towarsds a fix.
Basically, we're doing it wrong. If you're trying to use the combobox in a controlled mannor, you should be using `defaultInputValue`, not `inputValue`, and let Downshift manage the internal state afterwards. We re-map `inputValue` to `defaultInputValue` to address this. This should have no detrimental impact to the consumer and should just "fix the problem" with no code changes.
For folks using the hook, we're doing it wrong again. You want to set the _initial_ value and selected …

fix(combobox): controlled autocomplete cursor placement onInputValueChange bug

---

.changeset/tall-falcons-occur.md

fix: escape jsx in a changeset

---

packages/paste-website/src/pages/components/button/index.mdx
packages/paste-website/src/pages/components/inline-code/index.mdx

- Broken GitHub link on Button (URL is case-sensitive)
- Broken Storybook link on Inline Code (linked to a non-existent story)

fix(website): github and storybook links

---

.changeset/ninety-islands-type.md
packages/paste-core/components/avatar/__tests__/__snapshots__/avatar.test.tsx.snap
packages/paste-core/components/avatar/src/index.tsx
packages/paste-core/components/avatar/src/types.ts
packages/paste-core/components/avatar/stories/index.stories.tsx
packages/paste-website/src/pages/components/avatar/index.mdx

In this PR:
* add variant prop which has the options: 'user', 'entity'. It defaults to 'user'
* add color prop which has the options: 'default', 'decorative10', 'decorative20', 'decorative30', 'decorative40'. It defaults to 'default'
* update snapshot tests
* updates the website content to include color and variant props

feat(avatar): add new variant and color props

---

.changeset/six-frogs-destroy.md
packages/paste-core/components/avatar/__tests__/__snapshots__/avatar.test.tsx.snap
packages/paste-core/components/avatar/src/index.tsx
packages/paste-core/components/display-pill-group/stories/index.stories.tsx

Jira ticket: [DSYS-3449](https://issues.corp.twilio.com/browse/DSYS-3449)
This PR removes the extra underline from Avatars inside of Anchors or linked Display Pills.
Old:
Now:

chore(avatar): remove underline on avatars in anchors

---

.storybook/main.js
package.json
packages/paste-core/components/menu/__tests__/customization.spec.tsx
packages/paste-core/components/menu/stories/customization.stories.tsx
yarn.lock

Fixes Storybook hot reloading of Paste imports.  Hot reloading worked when importing relative source files (i.e.: `import {Button} from '../src';` but failed when importing named packages (i.e.: `import {Button} from '@twilio-paste/button'`).  This made it tedious to iterate quickly.
Loom video of my debugging process: 
https://www.loom.com/share/9fcfbf7d5526457a926a5890fe02df2d

fix: storybook hot reloading on paste imports

---

cypress/integration/sitemap-vrt/constants.ts
packages/paste-website/src/component-examples/ButtonGroupExamples.ts
packages/paste-website/src/pages/components/button-group/index.mdx

Adds a documentation page for the ButtonGroup component.

docs: add website docs for ButtonGroup

---

.changeset/nice-laws-divide.md
packages/paste-core/components/file-picker/__tests__/index.spec.tsx
packages/paste-core/components/file-picker/src/FilePicker.tsx
packages/paste-core/components/file-picker/stories/index.stories.tsx
packages/paste-website/src/component-examples/FilePickerExamples.ts
packages/paste-website/src/pages/components/file-picker/index.mdx

Fixes a couple bugs in the File Picker package. It was missing the `name` prop (which is important for form elements and someone asked about it for using the file picker with react-forms) and the `onChange` prop wasn't being passed down to the input element.

feat(file-picker): add onChange and name props

---

packages/paste-website/src/pages/customization/creating-a-custom-theme.mdx
packages/paste-website/src/pages/customization/customization-provider.mdx

using uppercase baseTheme breaks the CustomizationProvider.  Discussion https://github.com/twilio-labs/paste/discussions/2740

docs(website): fix baseTheme default/dark casing

---

.changeset/gold-avocados-relax.md
packages/paste-theme/src/types/GenericThemeShape.ts

Add missing `Partial<>` around iconSizes in theme typings

fix(theme): add missing Partial around iconSizes bucket

---

packages/paste-core/components/alert-dialog/__tests__/index.spec.tsx
packages/paste-core/components/button-group/__tests__/index.spec.tsx
packages/paste-core/components/combobox/__tests__/GrowingInput.spec.tsx
packages/paste-core/components/file-picker/__tests__/index.spec.tsx
packages/paste-website/src/__tests__/tokenCard.test.tsx

Currently, the customization tests use `toHaveStyle` instead of `toHaveStyleRule`. If you change the value, `toHaveStyle` always passes - only `toHaveStyleRule` actually works for our components. For example, there was currently a typo in the `toHaveStyle` rule and the test still passed.

fix(ButtonGroup): customization tests 

---

packages/paste-website/src/pages/core/upgrade-guide.mdx

Broken links in upgrade guide for v9, 10 and 11
On the upgrade guide page, update the links to the v9, v10, and v11 docs.

fix: links to v9, v10, and v11 docs on upgrade guide

---

.changeset/chilly-lizards-dress.md
packages/paste-core/components/chat-composer/src/ChatComposer.tsx
packages/paste-core/components/chat-composer/src/styles.ts

This PR fixes the global styles required by Lexical for our `ChatComposer` component. See this [PR comment for a demonstration of the issue](https://github.com/twilio-labs/paste/pull/2852#discussion_r1036270046)

fix(ChatComposer): fix Lexical global styles

---

cypress/integration/sitemap-vrt/constants.ts
packages/paste-website/src/component-examples/ChatComposerExamples.ts
packages/paste-website/src/pages/components/chat-composer/index.mdx

This PR adds a [new documentation website page for the `<ChatComposer />` component](https://deploy-preview-2852--paste-docs.netlify.app/components/chat-composer)

[DSYS-3301]: add Chat Composer documentation website page

---

.changeset/cold-nails-wonder.md
packages/paste-icons/build.js

This PR adds build targets for `@twilio-paste/icons` to avoid logical assignment syntax

build: add build targets to @twilio-paste/icons

---

.changeset/large-apples-reply.md
.eslint/__tests__/no-invalid-module-paths.test.js
.eslint/rules/no-invalid-module-paths.js
packages/paste-core/components/callout/src/Callout.tsx
packages/paste-core/components/menu/src/MenuGroup.tsx
packages/paste-website/src/components/shortcodes/package-status-legend/index.tsx

This PR introduces a new eslint rule to prevent invalid module paths within import/export/require statements for `@twilio-paste` packages.

build: add no-invalid-module-paths eslint rule

---

packages/paste-libraries/reakit/src/Portal/Portal.tsx
packages/paste-libraries/reakit/src/Tooltip/Tooltip.tsx
packages/paste-libraries/reakit/src/Tooltip/__globalState.tsx
packages/paste-libraries/reakit/src/index.tsx

We realised that Tooltip component was failing when using Nextjs 13 (React 18).
We found these two GitHub issue:
- [https://github.com/ariakit/ariakit/issues/656](https://github.com/ariakit/ariakit/issues/656)
- [https://github.com/ariakit/ariakit/issues/844](https://github.com/ariakit/ariakit/issues/844) 
There's a linked PR to the first one but it is still a draft: [https://github.com/ariakit/ariakit/pull/802](https://github.com/ariakit/ariakit/pull/802)
We managed to reproduce that PR fix on [codesandbox](https://codesandbox.io/p/sandbox/heuristic-knuth-lk4m55) changing the dependency in the package.json to that commit:
```json
"reakit": "https://pkg.csb.dev/reakit/reakit/commit/b6285795/reakit"
```
This PR aims to integrate those changes into @twilio-paste/reakit-library, using the …

fix: react 18 - fix reakit ssr issues with portals

---

packages/paste-cra-template/template.json

Using react 18 and react-router-dom @ 6.2.1 in the CRA template

chore: "upgrade" react and react-router-dom in cra template

---

packages/paste-website/src/__tests__/genericHeader.test.tsx
packages/paste-website/src/__tests__/packageStatusLegend.test.tsx

`yarn type-check` marks those react imports as unused but when running the tests they fail if no react import is there.
Decided today to ignore the tsx check on those imports.

chore: ignore tsx check on react import

---

packages/paste-website/src/pages/foundations/content/content-checklist/index.mdx
packages/paste-website/src/pages/foundations/content/index.mdx

Removed a hard-coded name. Responsibilities shift, and specifying a person directly isn't a good long term solution.

chore: remove name

---

.changeset/selfish-trains-attack.md
packages/paste-core/components/list/src/List.tsx
packages/paste-core/components/list/src/OrderedList.tsx
packages/paste-core/components/list/src/UnorderedList.tsx
packages/paste-core/components/list/src/types.ts

Found in this issue: https://github.com/twilio-labs/paste/issues/2954
Explicitly set the list style type on the list component so it doesn't get overriden.

fix: add list style type to List component

---

packages/paste-core/primitives/box/package.json
packages/paste-core/primitives/disclosure/package.json
packages/paste-core/primitives/text/package.json
packages/paste-website/src/pages/primitives/box/index.mdx
packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx
packages/paste-website/src/pages/primitives/disclosure-primitive/index.mdx
packages/paste-website/src/pages/primitives/index.mdx
packages/paste-website/src/pages/primitives/menu-primitive/index.mdx
packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx
packages/paste-website/src/pages/primitives/non-modal-dialog-primitive/index.mdx
packages/paste-website/src/pages/primitives/tabs-primitive/index.mdx
packages/paste-website/src/pages/primitives/text/index.mdx
packages/paste-website/src/pages/primitives/tooltip-primitive/index.mdx

converts all primitive pages except the listbox page, see this thread for context: https://twilio.slack.com/archives/C04L4C4E51D/p1674761782898869

chore: convert primitive pages except listbox

---

packages/paste-website/src/pages/core/changelog.mdx
packages/paste-website/src/pages/core/libraries/codemods/index.mdx
packages/paste-website/src/pages/core/libraries/data-visualization/index.mdx
packages/paste-website/src/pages/core/libraries/index.mdx
packages/paste-website/src/pages/core/libraries/uid-library/index.mdx
packages/paste-website/src/pages/core/upgrade-guide.mdx

This PR migrates the `src/pages/core` dir to use NextJS patterns.
The six pages migrated are broken apart [by commit in this PR:](https://github.com/twilio-labs/paste/pull/2997/commits)
* https://paste.twilio.design/core/changelog
* https://paste.twilio.design/core/upgrade-guide
* https://paste.twilio.design/core/libraries
* https://paste.twilio.design/core/libraries/uid-library
* https://paste.twilio.design/core/libraries/codemods
* https://paste.twilio.design/core/libraries/data-visualization

Migrate core pages to Nextjs

---

.danger/__tests__/missing-changesets-check.spec.ts
.danger/__tests__/utils.spec.ts
.danger/utils.ts

We missed a changeset for a design token change, due to the dangerJS check not correctly identifying design token files
We naively only checked for changes in `src` which works for every package except design tokens.
This PR makes sure we detect the unique design tokens file structure for changes that need to be published in the dangerJS check

fix: dangerJS check now correctly detects missing design token changes

---

.changeset/sixty-chefs-cover.md
packages/paste-design-tokens/tokens/global/text-color.yml
packages/paste-design-tokens/tokens/themes/dark/aliases/box-shadow.yml
packages/paste-design-tokens/tokens/themes/dark/aliases/offset.yml
packages/paste-design-tokens/tokens/themes/dark/global/text-color.yml
packages/paste-design-tokens/tokens/themes/evergreen/aliases/box-shadow.yml
packages/paste-design-tokens/tokens/themes/evergreen/aliases/offset.yml
packages/paste-design-tokens/tokens/themes/evergreen/global/text-color.yml
packages/paste-design-tokens/tokens/themes/twilio-dark/global/text-color.yml
packages/paste-design-tokens/tokens/themes/twilio/aliases/box-shadow.yml
packages/paste-design-tokens/tokens/themes/twilio/global/box-shadow.yml
packages/paste-design-tokens/tokens/themes/twilio/global/text-color.yml
packages/paste-website/src/__tests__/tokenAccessiblePairs.test.tsx
packages/paste-website/src/__tests__/tokenCard.test.tsx
packages/paste-website/src/components/tokens-list/helpers.tsx
packages/paste-website/src/components/tokens-list/index.tsx
packages/paste-website/src/components/tokens-list/token-card/AccessiblePairing.tsx
packages/paste-website/src/components/tokens-list/token-card/index.tsx
packages/paste-website/src/components/tokens-list/token-card/token-example/index.tsx
packages/paste-website/src/components/tokens-list/types.ts
packages/paste-website/stories/TokenCard.stories.tsx

- feat(website): show text color accessible background pairings
- feat(website): story and swap the chevron icon

feat(website): show text color token pairings

---

.changeset/brown-yaks-heal.md
packages/paste-core/components/side-modal/__tests__/customization.spec.tsx
packages/paste-core/components/side-modal/__tests__/index.spec.tsx
packages/paste-core/components/side-modal/src/SideModal.tsx
packages/paste-core/components/side-modal/src/SideModalContainer.tsx
packages/paste-core/components/side-modal/src/index.tsx

Currently passing  an `animated` prop to the `useSideModalState` hook does not allow the modal to close. [See this bug reproduction](https://codesandbox.io/s/new-pine-83hx99?file=/src/index.tsx)
Originally reported via discussion here: https://github.com/twilio-labs/paste/discussions/2839
Let's animate the SideModal ourselves instead so it leverages prefers-reduced-motion properly.

chore: animate SideModal component

---

packages/paste-design-tokens/tokens/aliases/color.yml

Add new secondary brand colors: https://www.twilio.com/brand/elements/colorresources#Secondary_palette
Amaranth already exists, and paper exists as orange-05. This PR adds only saffron, mint, and sky

feat(aliases): add new secondary brand colors

---

.changeset/thirty-games-protect.md
package.json
packages/paste-core/components/avatar/__tests__/__snapshots__/avatar.test.tsx.snap
packages/paste-core/components/separator/__tests__/__snapshots__/index.spec.tsx.snap
packages/paste-core/layout/grid/__tests__/__snapshots__/grid.test.tsx.snap
packages/paste-core/primitives/box/src/index.tsx
packages/paste-core/primitives/sibling-box/__tests__/__snapshots__/siblingBox.test.tsx.snap
packages/paste-core/primitives/text/__tests__/__snapshots__/text.spec.tsx.snap
packages/paste-core/primitives/text/src/index.tsx
tools/build/esbuild.js
yarn.lock

It's difficult to debug consuming applications, especially when folks find dependency management so hard. By injecting the version number of Core into the DOM we can see and prove what version of core the application is really resolving too.
It's static string replacement at compile time using an esbuild plugin.

chore: inject core version into the DOM

---

.github/workflows/on_pull_request.yml
.vscode/extensions.json

When we change the lockfile we cause the test runner tests to break, becuase we try to find out the version number of playwright before its installed and there is no cache. Install first, and then theoretically there should always be a version number regardless of cache invalidation.
The MDX extension we recommend is deprecated in favour of the official one, swap in our code base.

chore: replace deprecated extension and call playwright cache after install

---

.changeset/sharp-walls-wash.md
packages/paste-libraries/styling/src/index.tsx
packages/paste-theme/package.json
packages/paste-theme/stories/cacheProvider.stories.tsx
yarn.lock

Expands types on `@twilio-paste/styling-library`, and in turn `@twilio-paste/them` for cacheProviderProps such that a `container` key may be passed so Emotion styles can be injected within certain elements, like in shadow-dom.
Resolves https://github.com/twilio-labs/paste/discussions/3196

feat(styling-library): expand types for cacheProvider

---

.changeset/two-teachers-walk.md
.github/workflows/on_pull_request.yml
.storybook/main.ts
.storybook/preview.tsx
package.json
packages/paste-codemods/tools/.cache/mappings.json
packages/paste-core/components/alert-dialog/stories/index.stories.tsx
packages/paste-core/components/chat-log/stories/components/UseChatLogger.stories.tsx
packages/paste-core/components/combobox/stories/Combobox.stories.tsx
packages/paste-core/components/modal/stories/index.stories.tsx
packages/paste-core/components/side-modal/stories/index.stories.tsx
packages/paste-core/components/sidebar/__tests__/index.spec.tsx
packages/paste-core/components/sidebar/src/SidebarHeader.tsx
packages/paste-core/components/sidebar/src/SidebarHeaderIconButton.tsx
packages/paste-core/components/sidebar/src/SidebarHeaderLabel.tsx
packages/paste-core/components/sidebar/src/index.tsx
packages/paste-core/components/sidebar/stories/customization.stories.tsx
packages/paste-core/components/sidebar/stories/overlay.stories.tsx
packages/paste-core/components/sidebar/stories/push.stories.tsx
packages/paste-core/components/topbar/stories/topbar.stories.tsx

feat(sidebar): split up SidebarHeader into subcomponents and fix axe flakes

---

nx.json

Noticed that Netlify builds may fail when it relies on a cached build, i.e. nothing changed so it grabs the local cache. It then fails saying it can't find the contents of `.next` and I think that means it didn't actually pull anything from the cache, and that's because we don't tell nx there's anything there to cache.
This should fix it. 🤞🏼

fix: tell nx that the .next directory is a cachable output for netlify build

---

.changeset/short-gifts-glow.md
packages/paste-core/components/data-grid/src/DataGridRow.tsx
packages/paste-core/components/data-grid/src/table/Td.tsx
packages/paste-core/components/data-grid/src/table/Th.tsx
packages/paste-core/components/data-grid/src/table/Tr.tsx
packages/paste-core/components/table/src/proptypes.ts
packages/paste-core/components/table/src/types.ts

Improves TS typings and proptypes on DataGrid and Table's Tr, Td, and Th elements.
Based on discussions that happened here: https://github.com/twilio-labs/paste/pull/2597

fix(data-grid): improve ts typings and react proptypes

---

packages/paste-core/components/sidebar/stories/overlay.stories.tsx
packages/paste-core/components/sidebar/stories/push.stories.tsx
packages/paste-website/src/components/paste-mdx-provider/index.tsx
packages/paste-website/src/components/shortcodes/StoryPreview.tsx
packages/paste-website/src/pages/components/sidebar/index.mdx

A quick way to display a story in docs and add a code snippet underneath for component examples that can't be inlined

fix: sidebar examples by iframing in storybook story

---

.changeset/real-geese-bake.md
packages/paste-core/components/sidebar/src/navigation/SidebarNavigation.tsx
packages/paste-core/components/sidebar/src/navigation/SidebarNavigationDisclosureHeading.tsx
packages/paste-core/components/sidebar/src/navigation/SidebarNavigationItem.tsx

* Do a lil spike on janky animation when compact nav collapses and words wrap 
* Make scrollbar narrower, so collapsed Flex nav doesn’t have scrollbar covering items 
* Put 4-8px above scrollbar so it doesn’t touch the Sidebar Header border.

chore(sidebar): improve animation and scrollbar styles

---

.changeset/moody-impalas-rescue.md
.storybook/preview-head.html
internal-docs/engineering/fonts.md
packages/paste-cra-template/template/public/index.html
packages/paste-theme/src/styles/fonts.ts
packages/paste-token-contrast-checker/public/index.html
packages/paste-website/src/pages/_document.tsx
packages/paste-website/src/pages/components/heading/index.mdx
packages/paste-website/src/pages/introduction/for-engineers/manual-installation/index.mdx
packages/paste-website/src/pages/theme/changing-theme.mdx

fix(theme): update inter font to support number emojis

---

packages/paste-website/src/components/site-wrapper/SiteMain.tsx

In the switch to the new nav UI kit, the main element that was wrapping the main content was dropped by accident. This broke the Algolia indexing as the selector is dependent on the main element being there. It's also just good practice to have one.

fix: site search indexing by Algolia

---

.storybook/preview.tsx
packages/paste-core/components/spinner/stories/index.stories.tsx
packages/paste-core/components/status/stories/StatusMenu.stories.tsx
packages/paste-core/components/status/stories/StatusMenuCustomization.stories.tsx
packages/paste-core/components/tooltip/stories/index.stories.tsx
packages/paste-libraries/data-visualization/stories/index.stories.tsx

Fixes common chromatic flakes.
I had to disable some story tests, it was the only way. DataVis tokens are snapshot tested, so no point VRTing the renders. Highcharts shouldnt break unless we update it, and if we update it we surely will have the clarity of mind to review the examples on storybook.
Some customization stories flaked. I just removed them since they still have customization jest tests. Basically any popover that appears is at risk of flaking due to sub-pixel positioning issues. The flakes are much too noisy, worth losing those tests.

fix: chromatic flakes

---

packages/paste-website/package.json
packages/paste-website/src/pages/components/anchor/index.mdx
packages/paste-website/src/pages/components/aspect-ratio/index.mdx
packages/paste-website/src/pages/core/libraries/codemods/index.mdx
packages/paste-website/src/pages/introduction/for-designers/design-guidelines/index.mdx
packages/paste-website/src/pages/introduction/for-engineers/manual-installation/index.mdx
packages/paste-website/src/pages/introduction/for-engineers/quickstart/index.mdx
packages/paste-website/src/pages/theme/index.mdx
yarn.lock

We moved to types being a peer dep but didn't update the install guide.
I feel like I removed it by accident, but maybe that was another website
For codeblocks, we only allow certain syntax, and prop types was doing what it should and telling us we did it wrong

chore: update the install guides to mention types peer deps

---

.changeset/blue-phones-battle.md
.changeset/olive-lizards-enjoy.md
cypress/integration/sitemap-vrt/constants.ts
packages/paste-core/components/meter/__tests__/index.spec.tsx
packages/paste-core/components/meter/package.json
packages/paste-core/components/meter/src/Meter.tsx
packages/paste-core/components/meter/src/MeterLabel.tsx
packages/paste-core/components/meter/stories/index.stories.tsx
packages/paste-website/package.json
packages/paste-website/src/component-examples/MeterExamples.ts
packages/paste-website/src/pages/components/meter/index.mdx
packages/paste-website/src/pages/components/slider/index.mdx
yarn.lock

- Meter designs
- Meter docs
- Update Slider docs
```
<MeterLabel htmlFor={meterId} valueLabel="49GB">
Storage space used
</MeterLabel>
<Meter value={49} minValue={0} maxValue={64} minLabel="0GB" maxLabel="64GB" id="meterId" />
```
Design and API are as closely aligned as possible. Any aria values present in the DOM can be displayed on the Meter. The value label is set on the MeterLabel component using the `valueLabel` prop. Min and max value labels are optional and set on the Meter using `minLabel` and `maxLabel` props. This allows the consumer to have full control, using a string rather than a number.

chore(meter): add docs, update designs

---

.vscode/settings.json
biome.json
packages/paste-core/core-bundle/tools/utils.ts

Formatter tries to format compiled storybook source
If you build core, it'll tell you the generated files are incorrect.

chore: ignore generated storybook docs from format and format generated core bundle files

---

.github/workflows/on_discussion_create.yml
package.json
tools/github/autoresponder.ts

Uses our specially prompted ChatGPT4 endpoint to attempt rapid responses to incoming Github discussions. This doesn't mean we won't respond. A human will follow-up with more context or by affirming the bot response. This is in order to help people get answers they need, faster.

chore: add github discussion auto-responder

---

packages/paste-website/src/component-examples/page-templates/ObjectDetailsExamples.ts
packages/paste-website/src/component-examples/page-templates/ObjectsListExamples.ts
packages/paste-website/src/component-examples/page-templates/SettingsExamples.ts
packages/paste-website/src/pages/page-templates/object-details/index.mdx
packages/paste-website/src/pages/page-templates/objects-list/index.mdx
packages/paste-website/src/pages/page-templates/settings/index.mdx
packages/paste-website/stories/PageTemplates.stories.tsx
tools/github/autoresponder.ts

chore: add page templates stories

---

.changeset/thirty-dots-reply.md
packages/paste-core/components/description-list/src/DescriptionList.tsx
packages/paste-core/components/description-list/src/DescriptionListSet.tsx

Possible visual breaking change so it's marked as a minor with clear instructions. Removes top and bottom margin from `<dl>` and replaces the `<dd>` last of type bottom margin with a bottom margin on the `DescriptionListSet` as long as it's not the last one in the `<dl>`.

chore: remove description list vertical margin

---

.changeset/dirty-bottles-shop.md
packages/paste-core/components/data-grid/src/DataGrid.tsx
packages/paste-core/components/data-grid/type-docs.json

feat(data-grid): add ability to set role to treegrid

---

.changeset/slow-humans-peel.md
packages/paste-core/components/in-page-navigation/__tests__/vertical.spec.tsx
packages/paste-core/components/in-page-navigation/src/InPageNavigation.tsx
packages/paste-core/components/in-page-navigation/src/InPageNavigationContext.tsx
packages/paste-core/components/in-page-navigation/src/InPageNavigationItem.tsx
packages/paste-core/components/in-page-navigation/src/types.ts
packages/paste-core/components/in-page-navigation/stories/vertical.stories.tsx

Add vertical option to InPageNavigation. Includes stories and tests.
Looks like Tabs mostly:
Further design refinement coming in a follow up PR.

feat(in-page-navigation): add vertical

---

.changeset/early-frogs-applaud.md
packages/paste-core/components/progress-bar/package.json
packages/paste-core/components/progress-bar/src/ProgressBar.tsx
packages/paste-core/components/progress-bar/src/ProgressBarLabel.tsx
packages/paste-core/components/progress-bar/stories/index.stories.tsx
yarn.lock

[ProgressBar] Added new features and updated the design.
The ProgressBarLabel component has the following new props:
- `valueLabel` which displays a plain text value on the right side of the label.
- `disabled` which applies disabled styling on the label.
The ProgressBar component has updated styling and the following new props:
- `hasError` which displays error styling.
- `disabled` which displays disabled styling.

feat(progress-bar): add new props and refine styles

---

.changeset/wild-oranges-unite.md
packages/paste-core/components/heading/__tests__/heading.test.tsx
packages/paste-core/components/heading/src/Heading.tsx

Changes bottom margins for H2 and H4 so they're on an 8px scale to match our layout guidelines.

feat(Heading): update bottom margin for H2 and H4

---

packages/paste-website/src/pages/api/ai.ts
tools/github/autoresponder.ts

chore: improve github autoresponder

---

.changeset/late-mirrors-rule.md
packages/paste-core/components/input/src/Input.tsx
packages/paste-core/components/input/stories/input.stories.tsx

Fixes https://github.com/twilio-labs/paste/discussions/3721

fix(input): correctly display decrement arrow

---

.changeset/khaki-doors-cheer.md
packages/paste-customization/src/types/CustomizationProvider.ts
packages/paste-theme/src/themeProvider.tsx
packages/paste-theme/stories/themeProvider.stories.tsx

[ThemeProvider, CustomizationProvider] You can now style the ThemeProvider directly as you would style Box.
This is helpful in scenarios where ThemeProvider isn't wrapping your app root, but instead is nested in your DOM tree.
Resolves https://github.com/twilio-labs/paste/discussions/3118

feat(theme): allow styling themeprovider like box

---

packages/paste-theme/stories/themeProvider.stories.tsx

It fails on dark themes because the story has to reset a theme provider to the default theme. This is not a real use case and it's not worth fixing it.

fix: disable a11y test for theme provider in style test

---

apps/backend/README.md
apps/backend/supabase/migrations/20240129215251_top_searches.sql
apps/backend/supabase/schema.gen.ts
packages/paste-website/package.json
packages/paste-website/src/pages/api/post-to-slack.ts
packages/paste-website/src/pages/api/share-search-usage.ts
packages/paste-website/vercel.json
yarn.lock

Simple API route to post an update to a Slack channel
Via a vercel cron job that will run once a week and post the usage of the docsite search to a slack channel

feat: ability to post slack upates

---

.changeset/shaggy-geese-dress.md
packages/paste-core/components/data-grid/__tests__/index.spec.tsx
packages/paste-core/components/data-grid/src/table/Td.tsx
packages/paste-core/components/data-grid/src/table/Th.tsx
packages/paste-core/components/data-grid/stories/components/PlainDataGrid.tsx
packages/paste-core/components/data-grid/type-docs.json
packages/paste-core/components/summary-detail/type-docs.json
packages/paste-core/components/table/__tests__/index.spec.tsx
packages/paste-core/components/table/src/Td.tsx
packages/paste-core/components/table/src/Th.tsx
packages/paste-core/components/table/src/types.ts
packages/paste-core/components/table/type-docs.json
packages/paste-website/src/pages/components/table/index.mdx

Resolves https://github.com/twilio-labs/paste/discussions/2405

feat(table,datagrid): allow passing whiteSpace style prop

---

.changeset/strange-spoons-hear.md
packages/paste-core/components/select/src/Select.tsx

New PR to patch v15
Addresses https://github.com/twilio-labs/paste/discussions/2909
Changes in this PR:
Control background color of options
In windows we need to explicitly set the background color of options, otherwise in dark mode its white on white bg
(cherry picked from commit ac5a84407c1305ebb60fa317dd98fb8c99332d81)

fix(select): background color in dark mode on windows

---

apps/backend/package.json
apps/backend/supabase/migrations/20240201004610_top_searches_filtering.sql
apps/backend/supabase/schema.gen.ts
cypress/integration/api/discussions-search.spec.ts
cypress/integration/api/docs-search.spec.ts
cypress/integration/api/paste-assistant-message.spec.ts
cypress/integration/site-search/index.spec.ts
yarn.lock

Helps tidy up these by only testing with one string 
Changes the places where we test the search to use the single string

chore: better filtering of test search queries for more accurate data

---

.changeset/new-laws-mix.md
packages/paste-core/components/data-grid/__tests__/index.spec.tsx
packages/paste-core/components/data-grid/src/table/Td.tsx
packages/paste-core/components/data-grid/src/table/Th.tsx
packages/paste-core/components/data-grid/stories/components/PlainDataGrid.tsx
packages/paste-core/components/table/__tests__/index.spec.tsx
packages/paste-core/components/table/src/Td.tsx
packages/paste-core/components/table/src/Th.tsx

Resolves https://github.com/twilio-labs/paste/discussions/3753

fix(table,datagrid): noWrap prop regression

---

packages/paste-website/scripts/fetch-data.mjs

We were seeing confusing error on website builds:
These try/catches help us assess more clearly where the failure lies. Returns something like:
```
AirtableError {
error: 'AUTHENTICATION_REQUIRED',
message: 'You should provide valid api key to perform this operation',
statusCode: 401
}
```
---
When reviewing, toggle whitespaces to see a simpler view

chore: wrap try/catch around airtable data fetch for better debugging

---

packages/paste-website/src/pages/components/pagination/index.mdx

Replaces "coming soon" info about Progress Steps on Pagination docs.
(mainly did this as a test branch to make sure my new laptop was set up correctly)

chore: add progress steps link to pagination docs

---

packages/paste-website/src/pages/patterns/empty-state/index.mdx

https://paste-docs-git-fix-error-pattern-link-typo-twilio.vercel.app/patterns/empty-state#error-states

fix: error pattern link typo

---

packages/paste-core/components/button/src/Button.tsx
packages/paste-core/components/button/src/types.ts
packages/paste-core/components/button/type-docs.json
packages/paste-core/components/file-picker/type-docs.json
packages/paste-core/components/menu/type-docs.json
packages/paste-core/components/minimizable-dialog/type-docs.json
packages/paste-core/components/popover/type-docs.json
packages/paste-core/components/side-modal/type-docs.json

A previous contribution broke:
- Typings on our Reset button variant
- Code formatting conventions
- Button Jest tests around link style buttons
This PR reverts the code changes but keeps the JSDoc improvements.

fix(button): fix recent issues

---

packages/paste-core/components/side-panel/stories/index.stories.tsx

Fix issues that occur with a11y color-contrast on Side Panel

chore(SidePanel): fix a11y contrast issue

---

packages/paste-website/src/pages/customization/creating-a-custom-theme.mdx
packages/paste-website/src/pages/customization/customization-provider.mdx
packages/paste-website/src/pages/inclusive-design/index.mdx

Typo fixes on these pages:
- [Creating a custom theme](https://paste-docs-git-choredocs-fix-typos-on-customization-docs-twilio.vercel.app/customization/creating-a-custom-theme)
- [Customization Provider](https://paste-docs-git-choredocs-fix-typos-on-customization-docs-twilio.vercel.app/customization/customization-provider)
And tidied up spacing here: https://paste-docs-git-choredocs-fix-typos-on-customization-docs-twilio.vercel.app/inclusive-design

chore(docs): fix typos on customization docs

---

packages/paste-website/src/pages/customization/customization-provider.mdx

https://paste-docs-git-featdocs-add-customization-warning-8adad6-twilio.vercel.app/customization/customization-provider

feat(docs): add warning to customization docs for twilio employees

---

packages/paste-website/src/pages/components/account-switcher/index.mdx

chore: small change for testing vercel

---

.changeset/smooth-gorillas-care.md
.eslintrc.js
packages/paste-core/components/badge/src/constants.ts
packages/paste-core/components/badge/src/styles.ts
packages/paste-core/components/badge/stories/index.stories.tsx
packages/paste-core/components/badge/type-docs.json
packages/paste-core/components/menu/type-docs.json
packages/paste-core/components/popover/type-docs.json
packages/paste-core/components/side-panel/type-docs.json
packages/paste-website/src/pages/components/badge/index.mdx

This pull request primarily introduces a new badge variant, `notification_counter`, to the badge component in `packages/paste-core/components/badge`. 
It uses the new design tokens for notifications

feat(badge): add notification variant

---

.changeset/khaki-rocks-fix.md
packages/paste-core/components/user-dialog/src/UserDialog.tsx

Updating the size of the Avatar element in UserDialog. The current size of the Avatar is slightly too large and looks a bit out of place.
No functional changes to the component have occurred.

avatar-size-user-dialog

---

packages/paste-website/src/pages/components/form/index.mdx

[DSYS-434](https://twilio-productivity.atlassian.net/browse/DS-434)

chore: add selection methods section to form docs

---

internal-docs/engineering/developing-locally.md
package.json

Added a new script into package.json to run a series of commands to resolve the typedoc issue when forking the repo.
After investigation I found that if you run the typedoc command before running the build command it will output incorrect typedocs and cause large unintended and incorrect changes to various typedoc files. What is more interesting is that these incorrect changes are different per machine.
The resolution is to clean the local NX cache and run the full build and typedocs scrips. Tested locally by forking the repo multiple times.
If we see this issue in collab PRs we can now ask them to just run this to resolve the issue instead of granting write access to our repo

chore(collaboration): added script to resolve typedoc issue

---

.changeset/small-turkeys-change.md
packages/paste-core/components/form-pill-group/src/FormPillButton.tsx
packages/paste-core/components/form-pill-group/src/PillCloseIcon.tsx
packages/paste-core/components/form-pill-group/stories/index.stories.tsx

Fix dismiss button position for large pill size

Pill large dismiss

---

.changeset/short-years-taste.md
packages/paste-core/components/checkbox/src/CheckboxDisclaimer.tsx
packages/paste-core/components/checkbox/stories/checkbox.stories.tsx
packages/paste-core/components/checkbox/type-docs.json

Fix a bug where using helpText on CheckboxDisclaimer would give typescript errors

fix(checkbox): expose helpText on CheckboxDisclaimer

---

apps/backend/package.json
apps/backend/supabase/schema.gen.ts
yarn.lock

Now use an exact package version which seems to work better with the CLI

fix(supabase): use exact package version

---

.github/workflows/on_merge_to_main_supabase.yml
.github/workflows/update_docs_embed.yml

Supbabase link commands are not working with prod. A support ticket has been raised but we can temporarily remove these.
The purpose of these are to detect changes in database structure and create and apply migrations to update the prod instance. These are things such as adding/removing columns, creating and removing tables.
The generate embedding issue should actually be resolved from this as we do not need to do any database maintenence but run a script using the javascript library to connect to the DB. This connects a different way than the CLI step that is breaking. I believe this Javascript script should still work as that is the same library used to connect to DB for search functionality in the site that is still working.

chore(ci): temporarily disable broken actions

---

.github/workflows/on_pull_request_package_size.yml
.github/workflows/on_pull_request_supabase.yml
.github/workflows/update_docs_embed.yml
nx.json

Remove the static NX token. It was a read only token for an open source project but flagged by internal security. 
The token was deleted from NX Cloud and another one is shared in team 1Password if needed for local development.
The token has been updated in GitHub variables and you can see it correctly connecting for this PR 4042:

fix(nx): remove access token. Sets via env variables

---

.changeset/healthy-cobras-whisper.md
packages/paste-core/components/combobox/src/ListboxPositioner.tsx
packages/paste-core/components/combobox/src/ListboxWrapper.tsx
packages/paste-core/components/combobox/src/multiselect/MultiselectCombobox.tsx
packages/paste-core/components/combobox/src/singleselect/Combobox.tsx
packages/paste-core/components/combobox/src/types.ts
packages/paste-core/components/combobox/stories/Combobox.stories.tsx
packages/paste-core/components/combobox/stories/MultiselectCombobox.stories.tsx
packages/paste-core/components/combobox/type-docs.json
packages/paste-website/src/component-examples/ComboboxExamples.ts
packages/paste-website/src/component-examples/MultiselectComboboxExamples.ts
packages/paste-website/src/pages/components/combobox/index.mdx
packages/paste-website/src/pages/components/multiselect-combobox/index.mdx

Fixes a bug where Comboboxes (Singleselect and Multiselect) can't be used when placed inside of Popovers. The bug was caused by the Combobox Listbox Portal interfering with the Popover Reakit Portal, and was preventing hover styles from being applied as well as closing the entire Popover on a selection of an item (Multiselect only). [See this CodeSandbox for a reproduction and more context](https://codesandbox.io/p/sandbox/combobox-in-popover-krzsgd).
This PR adds the `usePortal` prop to Combobox (which defaults to `true`). It should be used (and set to `false`) when Combobox is used in a Popover. When Combobox doesn't use a Portal, it uses an absolutely positioned Box to position the listbox and attach it to the input box. This means that the ListboxPositioner isn't used on these …

fix: combobox inside of popover bug

---

.changeset/curly-ants-report.md
packages/paste-core/components/toast/src/useToaster.ts

The issue with this was the useEffect hook. the return section is a cleanup, designed to be ran when the component is unmounting. The issue is, when passing a prop is added ot the dependency array the useEffect cleanup is ran for **every change**. So whenever a new toast was added/removed the cleanup was ran. This means teh timeouts for toasts that were already in the array were being cleared and the pop funciton was not being called for them.
This is consistent with the behavior we saw before as only the new toast was being cleared and the old toasts were not being dismissed.
[This article](https://reacttraining.com/blog/useEffect-cleanup) summarizes the issue well in the section `The other circumstance the cleanup gets called `
before: …

fix(toast): fix for multiple toast dismiss

---

packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderLogo.tsx
packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderSearch.tsx

- fixed horizontal scroll on mobile nav
- Change Paste logo to the default logo

fix(nav): docs site navigation

---

.changeset/modern-starfishes-matter.md
packages/paste-core/components/visual-picker/src/VisualPickerCheckbox.tsx

Fix Visual Picker Checkbox doesn't work in Firefox when checkbox is clicked on directly

---

.changeset/smooth-ads-admire.md
packages/paste-core/components/side-modal/src/SideModalFooterActions.tsx
packages/paste-core/components/side-modal/stories/customization.stories.tsx
packages/paste-core/components/side-modal/stories/index.stories.tsx
packages/paste-website/src/component-examples/SideModalExamples.ts

- updates the alignment of `SideModalFooterActions`
- updates the storybook

[Side Modal]!: Align Side Modal footer actions to left

---

.changeset/healthy-squids-cheat.md
packages/paste-core/components/code-block/src/CodeBlockTabList.tsx
packages/paste-core/components/code-block/src/utlis.ts
packages/paste-core/components/in-page-navigation/src/InPageNavigation.tsx
packages/paste-core/components/in-page-navigation/src/utils.ts
packages/paste-core/components/tabs/src/TabList.tsx
packages/paste-core/components/tabs/src/utils.ts

Fix the scroll logic so it's on the container itself and reduce the comparison threshold for right overflow button.
customer reported screen recording of not being able to completely scroll:
https://private-user-images.githubusercontent.com/10288627/383905054-3f987474-c635-46a6-b5f0-526d8d826e3c.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODQxNTMsIm5iZiI6MTczMTA4Mzg1MywicGF0aCI6Ii8xMDI4ODYyNy8zODM5MDUwNTQtM2Y5ODc0NzQtYzYzNS00NmE2LWI1ZjAtNTI2ZDhkODI2ZTNjLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE2MzczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dX …

fix(tabs): do not scroll to end in some instances

---

.changeset/nervous-rabbits-love.md
internal-docs/engineering/gotchas.md
packages/paste-core/components/progress-steps/src/ProgressSteps.tsx

Wrapped Progress steps in useMemo to avoid unnecessary re-renders. Note that this issue only occurs when a prop form the component is passed into the emotion styled.div that causes re-renders. If the option passed to this are static then there is no issue which is why only this component has changes as it is conditional on orientation.

fix(progress-steps): unnecessary re-renders

---

.changeset/hungry-countries-move.md
packages/paste-core/components/select/src/Select.tsx

https://paste-docs-git-fix-select-bg-twilio.vercel.app/components/select#disabled-select

fix(select): Disabled Select should use color-background

---

packages/paste-website/src/pages/sitemap.xml.tsx

Update how sitemap is populated to avoid using a compiled cache. After investigating it was found that sitemap was only being generated form the next cache of routes visited. This change dynamically generated the sitemap on build for all pages in the /src/pages directory of the website.
before:
after:

fix(docs): change sitemap generation

---

.changeset/selfish-bottles-argue.md
packages/paste-core/components/in-page-navigation/src/InPageNavigationItem.tsx

Changed `InPageNavigationItem` vertical styles to wrap text instead of using ellipsis

fix(in-page-navigation): modified code so vertical items wrap text

---

packages/paste-website/src/pages/sitemap.xml.tsx

After reading resources further a lot of references mention that the sitemap.xml should contain all canonical urls (ends with a "/").
I noticed not all of them do in the current deployed one.
preview [sitemap.xml](https://paste-docs-git-canconical-sitemap-urls-twilio.vercel.app/sitemap.xml)
Before:
After:

fix(sitemap): ensure all canonical URL

---

cypress/integration/sitemap-vrt/constants.ts
packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderSearch.tsx
packages/paste-website/src/hooks/useDarkMode.tsx
packages/paste-website/src/pages/_app.tsx
packages/paste-website/src/pages/blog/2023-06-12-paste-newsletter.mdx
packages/paste-website/src/pages/blog/2023-08-02-paste-newsletter.mdx
packages/paste-website/src/pages/components/description-list/index.mdx
packages/paste-website/src/pages/components/status-badge/index.mdx
packages/paste-website/src/pages/components/status-menu/index.mdx
packages/paste-website/src/pages/patterns/object-status/index.mdx

Revert 4025 fix theme flash

---

.changeset/great-frogs-grin.md
packages/paste-core/components/product-switcher/__tests__/ProductSwitcher.spec.tsx
packages/paste-core/components/product-switcher/src/ProductSwitcherItem.tsx
packages/paste-core/components/product-switcher/stories/ProductSwitcher.customization.stories.tsx
packages/paste-core/components/product-switcher/type-docs.json

Twilio teams (Twilio, Segment, and SendGrid) are updating the design of the unified identity product switcher. Currently, we're hacking in a solution by setting `productIcon={<></>}` or similar and passing custom styles to adjust the padding. This works for now, but ideally we should make this property optional for this new use-case.

fix: makes productIcon optional in ProductSwitcherItem
