twilio-labs/paste

packages/paste-website/gatsby-config.js, packages/paste-website/package.json, yarn.lock
- updated `gatsby-plugin-google-analytics` plugin
- added UA ID
=> fix(website): Update GA Tracking ID

packages/paste-design-tokens/tokens/aliases/z-index.yml
Update the z-index scale to use 10s as per @TheSisb's suggestion
=> feat: change the z-index scale to 10s

packages/paste-website/src/pages/index.tsx
Change Install Paste 0.1 to Get Started
=> docs(website): copy change

packages/paste-website/src/components/Heading.tsx, packages/paste-website/src/components/Typography.tsx, packages/paste-website/src/components/paste-mdx-provider/index.tsx, packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/components/table/index.tsx, packages/paste-website/src/components/tokens-example/index.tsx, packages/paste-website/src/components/tokens-list/index.tsx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/tokens/index.mdx, yarn.lock
Polish the tokens and typography components for better crosssite styling
=> fix: typography polish and Token page

packages/paste-website/src/components/sidebar/Navigation.tsx, packages/paste-website/src/pages/migrate/index.mdx
1. New nav item
2. Text covering migration guidance for console
3. General faq re: migration and contribution
4. tbd sections for sendgrid / flex
=> docs(website): basic migration guide

packages/paste-website/package.json, packages/paste-website/src/constants.ts, packages/paste-website/src/layouts/DefaultLayout.tsx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/tokens/index.mdx, packages/paste-website/src/pages/utilities/index.mdx, yarn.lock
=> chore(website): add page titles and descriptions

README.md
Just making the README a little more current for tomorrow.
=> chore(readme): update the README

packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/pages/components/anchor/index.mdx, packages/paste-website/src/pages/components/button/index.mdx, packages/paste-website/src/pages/components/index.mdx
Add docs to the button component 
=> fix(website): add button docs

packages/paste-website/src/components/Footer.tsx, packages/paste-website/src/components/SiteStickyHeader.tsx, packages/paste-website/src/components/StyledHr.tsx, packages/paste-website/src/components/site-wrapper/SiteFooter.tsx, packages/paste-website/src/components/site-wrapper/index.tsx, packages/paste-website/src/components/site-wrapper/styles.ts, packages/paste-website/src/constants.ts, packages/paste-website/src/pages/index.tsx
Footer for the Paste docs website.
=> feat(website): website footer

packages/paste-website/src/constants.ts, packages/paste-website/src/pages/index.tsx
- Changed intro copy to: Paste is an internal design system...
=> fix(website): change intro copy

packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/migrate/index.mdx
=> chore(website): remove internal links

packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/migrate/index.mdx
1. Added console react links to landing page
2. Added console react links to migration guide
=> Add Console React Component Links

packages/paste-website/src/components/component-overview-table/index.tsx, packages/paste-website/src/components/empty-state/InDevelopment.tsx, packages/paste-website/src/components/empty-state/NotBuilt.tsx, packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/utils/RouteUtils.ts
Simple tweak:
*Before*
*After*
=> chore(website): change casing of components in sidebar

packages/paste-website/src/components/Heading.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/roadmap/index.mdx, yarn.lock
=> feat(website): roadmap page

packages/paste-website/src/pages/tokens/how-to-compose-custom-ui-with-tokens.mdx, yarn.lock
Fix some broken links on the how-to compose with tokens page.
=> fix(website): correct the broken links on token pages

.circleci/config.yml, applitools.config.js, package.json
=> chore: setup applitools vrt

.eslintrc.js, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/principles/index.mdx, yarn.lock
- Added UX Principles to Paste
- Added Nav Item
=> docs(website): added principles

packages/paste-website/src/pages/components/button/index.mdx
Close #79
Separate the next paragraph from the 3rd bullet.
=> docs(website): fix bullets in about section of button component

packages/paste-website/gatsby-config.js, packages/paste-website/package.json, packages/paste-website/src/components/paste-mdx-provider/index.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/index.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/styles.ts, packages/paste-website/src/components/shortcodes/table-of-contents/types.ts, packages/paste-website/src/components/site-wrapper/index.tsx, packages/paste-website/src/pages/components/anchor/index.mdx, packages/paste-website/src/pages/components/button/index.mdx, packages/paste-website/src/pages/getting-started/design.mdx, packages/paste-website/src/pages/getting-started/engineering.mdx, packages/paste-website/src/pages/getting-started/index.mdx, packages/paste-website/src/pages/migrate/index.mdx, packages/paste-website/src/pages/principles/index.mdx, packages/paste-website/src/pages/roadmap/index.mdx, packages/paste-website/src/pages/tokens/design-tokens-package.mdx, packages/paste-website/src/pages/tokens/how-to-compose-custom-ui-with-tokens.mdx, packages/paste-website/src/pages/tokens/theme-package.mdx, packages/paste-website/src/pages/utilities/aspect-ratio/index.mdx, packages/paste-website/src/utils/RouteUtils.ts, yarn.lock
=> feat(website): Table of Contents Component

packages/paste-core/components/button/src/styles.ts
Resolves: https://github.com/twilio-labs/paste/issues/77
=> fix(button): border-color should transition with background-color

packages/paste-website/src/pages/utilities/box/index.mdx
Adding a table of contents to the Box documentation
=> docs(box): add table of contents

packages/paste-website/src/components/site-wrapper/SiteHeader.tsx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/migrate/index.mdx
=> chore: change http links to https

packages/paste-website/src/pages/index.tsx
=> fix(website): change home buttons back to links

.circleci/config.yml, applitools.config.js, package.json, yarn.lock
Try and get the Applitools GitHub checks running fully.
Goal is to see something like:
=> chore: get the applitools github checks API running

packages/paste-core/components/typography/__tests__/__snapshots__/paragraph.test.tsx.snap, packages/paste-core/utilities/absolute/stories/index.stories.tsx, packages/paste-core/utilities/box/src/index.tsx, packages/paste-core/utilities/box/stories/index.stories.tsx, packages/paste-core/utilities/media-object/stories/index.stories.tsx, packages/paste-core/utilities/screen-reader-only/stories/index.stories.tsx, packages/paste-core/utilities/text/__tests__/__snapshots__/text.spec.tsx.snap, packages/paste-core/utilities/text/__tests__/text.spec.tsx, packages/paste-core/utilities/text/src/index.tsx, packages/paste-core/utilities/text/stories/index.stories.tsx, packages/paste-core/utilities/truncate/stories/index.stories.tsx, packages/paste-icons/__IconList.tsx, packages/paste-icons/tools/listTemplate.js, packages/paste-types/src/style-props/font.ts, packages/paste-website/src/components/DoDont.tsx, packages/paste-website/src/components/Heading.tsx, packages/paste-website/src/components/callout/types.ts, packages/paste-website/src/components/empty-state/InDevelopment.tsx, packages/paste-website/src/components/empty-state/NotBuilt.tsx, packages/paste-website/src/components/empty-state/NotFound.tsx, packages/paste-website/src/components/site-wrapper/SiteFooter.tsx, packages/paste-website/src/components/tokens-example/index.tsx, packages/paste-website/src/components/tokens-list/index.tsx, yarn.lock
Polish the Text component for production.
=> feat: finalise the Text component

packages/paste-website/src/pages/getting-started/engineering.mdx, packages/paste-website/src/pages/index.tsx
Update the getting started page with core package an embedded code sandbox
=> feat: update getting started

.prettierignore, packages/paste-core/utilities/text/package.json, packages/paste-core/utilities/text/stories/index.stories.tsx, packages/paste-website/src/components/Heading.tsx, packages/paste-website/src/components/callout/index.tsx, packages/paste-website/src/pages/roadmap/index.mdx, packages/paste-website/src/pages/utilities/box/index.mdx, packages/paste-website/src/pages/utilities/text/index.mdx, yarn.lock
Adding the text component documentation to the website
=> docs: add the text component documentation

packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/utilities/index.mdx, yarn.lock
Quick one for better user experience and options if customers don't find components or utilities they need:
* Added a Callout Component to Component and Utility Overview Pages for better discoverability
=> feat(website): added callout with help for component and utility lists

packages/paste-core/components/button/src/index.tsx, packages/paste-website/src/pages/components/button/index.mdx
Updating the button docs to show the loading state and Icon only buttons (now that icons are fixed).
=> fix(website): update button docs with loading and icon states

packages/paste-website/src/pages/roadmap/index.mdx, yarn.lock
Quick PR to update confirmed release items for Roadmap.
=> docs(website): roadmap update for 0.4 and 0.5

packages/paste-design-tokens/tokens/aliases/color-palette.yml
=> fix(design-tokens): update lightest console color palette

packages/paste-core/components/anchor/__tests__/__snapshots__/anchor.test.tsx.snap
Tests were out of sync because my original PR was out of sync with master.
=> test(anchor): update test snapshots

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Adding an issue template for feature requests and bug reporting. It's pretty basic for now, we can expand it over time.
=> feat(repo): add simple issue template for features / bugs

packages/paste-core/components/paragraph/CHANGELOG.md, packages/paste-core/components/paragraph/package.json, packages/paste-website/src/pages/components/paragraph/index.mdx
Copy paste the paragraph component documentation into the doc site
=> docs: add the paragraph component documentation

packages/paste-website/src/pages/roadmap/index.mdx
=> feat: push toast component to release 0.6

package.json
Lets try and limit the concurrency of lerna when we build so that we stop hitting this out of memory exception on CircleCi
🤞
=> chore: limit concurrent tasks on build in CI

package.json
Bump the version number for the release
=> chore: release 0.4

.yarnrc
Updating the yarn version used by this repository.  See: https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli
=> chore: update repo yarn version

packages/paste-website/src/components/codeblock/index.tsx
=> fix: add height to styled code to prevent overflow

packages/paste-website/src/pages/index.tsx
=> docs(website): update intro

packages/paste-website/src/pages/index.tsx
=> docs(website): simplified intro page

packages/paste-icons/README.md, packages/paste-website/src/pages/icon-system/how-to-add-an-icon.mdx
Adding documentation from the engineering side on how to self-service icon additions.
=> chore: update docs on adding icons

packages/paste-website/package.json, packages/paste-website/src/components/Typography.tsx, packages/paste-website/src/components/empty-state/NotBuilt.tsx, packages/paste-website/src/components/paste-mdx-provider/index.tsx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/components/list/index.mdx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/utilities/index.mdx, yarn.lock
- Add the list component docs page
- Replace custom list components with the list package components
=> docs: add the list component docs and use it to replace custom lists

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/libraries/index.mdx, packages/paste-website/src/pages/paste-libraries/index.mdx
Adds a page to our website linking out to our standalone libraries.
=> chore(website): add Paste Libraries section

.jest/resolver.js, packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/alert/__tests__/index.spec.tsx, packages/paste-core/components/alert/package.json, packages/paste-core/components/alert/rollup.config.js, packages/paste-core/components/alert/src/index.tsx, packages/paste-core/components/alert/stories/index.stories.tsx, packages/paste-core/components/alert/tsconfig.build.json, packages/paste-core/components/alert/tsconfig.json, packages/paste-core/components/card/package.json, packages/paste-core/components/card/tsconfig.build.json, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/utilities/media-object/package.json, packages/paste-core/utilities/media-object/src/index.tsx, packages/paste-core/utilities/media-object/stories/index.stories.tsx, packages/paste-core/utilities/media-object/tsconfig.build.json, packages/paste-design-tokens/tokens/global/background-color.yml, packages/paste-design-tokens/tokens/global/border-color.yml, packages/paste-design-tokens/tokens/global/text-color.yml, packages/paste-design-tokens/tokens/themes/console/global/background-color.yml, packages/paste-design-tokens/tokens/themes/console/global/border-color.yml, packages/paste-design-tokens/tokens/themes/console/global/text-color.yml, packages/paste-design-tokens/tokens/themes/sendgrid/global/background-color.yml, packages/paste-design-tokens/tokens/themes/sendgrid/global/border-color.yml, packages/paste-design-tokens/tokens/themes/sendgrid/global/text-color.yml
- New status tokens to support the alert
- update media-object to use box so it can be used in alert
- create the alert component
- add alert to core package
=> feat(alert): create alert component

packages/paste-core/components/button/__tests__/__snapshots__/button.test.tsx.snap, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/spinner/src/index.tsx
Adds a nice fadeIn effect on Spinners with an added delay.  Helps resolve flashes of spinner in the case they are presented to the user for a fraction of a second.
=> chore(spinner): add fadein and delay effect

packages/paste-style-props/src/types/background.ts, packages/paste-style-props/src/types/border.ts, packages/paste-style-props/src/types/flexbox.ts, packages/paste-style-props/src/types/layout.ts, packages/paste-style-props/src/types/position.ts, packages/paste-style-props/src/types/shadow.ts, packages/paste-style-props/src/types/space.ts, packages/paste-style-props/src/types/typography.ts
Exports non-responsive typings so that we can properly type code, like this here https://github.com/twilio-labs/paste/pull/255/files#diff-065500df3a0119bd45665e09d97fe283R23
Helps unblock https://github.com/twilio-labs/paste/pull/255
=> fix(style-props): add non-responsive options

.github/workflows/publish.yml, package.json
- Use GitHub actions for publishing packages via lerna on merge to master
=> chore(ci): use github actions for publishing packages

packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/utilities/flex/src/index.tsx, packages/paste-core/utilities/grid/package.json, packages/paste-core/utilities/grid/rollup.config.js, packages/paste-core/utilities/grid/src/Column.tsx, packages/paste-core/utilities/grid/src/Grid.tsx, packages/paste-core/utilities/grid/src/index.tsx, packages/paste-core/utilities/grid/stories/index.stories.tsx, packages/paste-core/utilities/grid/tsconfig.build.json, packages/paste-core/utilities/grid/tsconfig.json
=> feat(grid): create grid component

packages/paste-website/src/pages/roadmap/index.mdx
Adding in some bullet points on the engineering side for next release
=> chore(website): update engineering releases on roadmap

packages/paste-core/utilities/grid/src/Column.tsx, packages/paste-core/utilities/grid/src/Grid.tsx, packages/paste-core/utilities/grid/src/helpers.tsx, packages/paste-core/utilities/grid/src/index.tsx, packages/paste-core/utilities/grid/src/types.ts
=> chore(grid): rename and move functions, move types

packages/paste-website/src/components/site-wrapper/SiteFooter.tsx
=> chore(website): change website date to get current year

packages/paste-core/utilities/grid/__tests__/__snapshots__/grid.test.tsx.snap, packages/paste-core/utilities/grid/__tests__/grid.test.tsx
=> test(grid): unit tests and snapshot tests

packages/paste-core/components/anchor/package.json, packages/paste-core/components/button/package.json, packages/paste-core/components/card/package.json
Button and Card are being bumped out of beta status because they're being used in prod.
=> chore: update some package statuses

packages/paste-core/components/list/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/list/__tests__/index.spec.tsx, packages/paste-core/components/list/src/index.tsx, packages/paste-core/components/list/stories/index.stories.tsx
=> fix(list): allow marginTop and marginBottom props

packages/paste-website/src/pages/components/list/index.mdx
=> docs(website): update list spec page

packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/pages/primitives/box/index.mdx, packages/paste-website/src/pages/primitives/text/index.mdx
=> chore(website): add primitives breadcrumb

packages/paste-style-props/src/types/layout.ts
=> fix(style-props): allow 100% as a width value

packages/paste-website/src/pages/primitives/box/index.mdx
Document the new width value for box
=> docs(box): add 100% as a width value to props table

packages/paste-design-tokens/tokens/themes/sendgrid/aliases/color-palette.yml, packages/paste-design-tokens/tokens/themes/sendgrid/global/border-color.yml
Changes only done in SG theme.
=> fix(design-tokens): change sg gray-70 and color-border-inpt

packages/paste-website/package.json, packages/paste-website/src/pages/utilities/grid/index.mdx
=> docs(grid): add grid spec to docs site

packages/paste-core/utilities/grid/package.json
=> chore(grid): update package description

packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/modal-dialog/CHANGELOG.md, packages/paste-core/primitives/modal-dialog/package.json, packages/paste-core/primitives/modal-dialog/rollup.config.js, packages/paste-core/primitives/modal-dialog/src/index.tsx, packages/paste-core/primitives/modal-dialog/stories/index.stories.tsx, packages/paste-core/primitives/modal-dialog/tsconfig.build.json, packages/paste-core/primitives/modal-dialog/tsconfig.json, yarn.lock
Adds the modal dialog primitive package.  
**Todo:**
=> feat(modal-dialog-primitive): add package

packages/paste-website/src/components/StatusLegend.tsx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/primitives/index.mdx, packages/paste-website/src/pages/roadmap/index.mdx, packages/paste-website/src/pages/utilities/index.mdx
=> docs(website): add status legend to roadmap and overview pages

packages/paste-website/src/pages/getting-started/engineering.mdx
=> fix(website): update engineering guide

packages/paste-website/src/components/BrowserSupport.tsx, packages/paste-website/src/pages/getting-started/index.mdx, packages/paste-website/src/pages/index.tsx, packages/paste-website/src/pages/migrate/index.mdx
=> feat(website): add browser support information

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/button/__tests__/__snapshots__/button.test.tsx.snap, packages/paste-core/components/button/src/styles.ts
=> fix(button): change borders to box-shadow

package.json, packages/paste-website/src/components/shortcodes/table-of-contents/styles.ts, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.styles.ts, yarn.lock
Address security vulnerability in acorn
=> chore: bump acorn version to 5.7.4

packages/paste-website/src/pages/roadmap/index.mdx
- Remove Component Lifecycle
- Simplify Roadmap Structure
- Update Content
=> docs(website): roadmap update

packages/paste-website/package.json, packages/paste-website/src/components/component-overview-table/index.tsx, packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/constants.ts, packages/paste-website/src/pages/form/input/index.mdx, packages/paste-website/src/utils/componentFilters.ts, packages/paste-website/src/utils/types.ts
=> feat(website): add input docs

packages/paste-core/components/form/__tests__/__snapshots__/formhelptext.test.tsx.snap, packages/paste-core/components/form/__tests__/formInput.test.tsx, packages/paste-core/components/form/__tests__/formTextarea.test.tsx, packages/paste-core/components/form/__tests__/formhelptext.test.tsx, packages/paste-core/components/form/src/FormHelpText.tsx, packages/paste-core/components/form/src/index.tsx, packages/paste-core/components/form/stories/index.stories.tsx, packages/paste-website/src/pages/form/input/index.mdx
=> fix(form): change FormHelperText to FormHelpText

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/constants.ts, packages/paste-website/src/pages/content/get-support.mdx, packages/paste-website/src/pages/content/index.mdx, packages/paste-website/src/pages/content/product-style-guide.mdx, packages/paste-website/src/pages/content/voice-and-tone.mdx, packages/paste-website/src/pages/content/writing-for-components.mdx
Creating content guidelines section
=> feat(website): creating content guidelines section

packages/paste-core/components/form/__tests__/formInput.test.tsx, packages/paste-core/components/form/src/FormInput.tsx, packages/paste-core/components/form/src/shared/FieldWrapper.tsx, packages/paste-core/components/form/src/shared/types.ts, packages/paste-core/components/form/stories/index.stories.tsx
=> fix(form): remove input type hidden box shadow

packages/paste-core/components/form/__tests__/__snapshots__/formInput.test.tsx.snap, packages/paste-core/components/form/__tests__/__snapshots__/formTextarea.test.tsx.snap, packages/paste-core/components/form/src/FormInput.tsx, packages/paste-core/components/form/src/FormTextArea.tsx, packages/paste-core/components/form/stories/index.stories.tsx
=> fix(form): remove box-shadow, inherit font family

packages/paste-core/components/form/stories/index.stories.tsx
stories for:
- input with placeholder
- textarea with value
=> chore(form): add missing stories for input and textarea

packages/paste-website/src/pages/form-elements/textarea/index.mdx
Fixed a couple minor text nits on the `textarea` doc page. See here:
- https://github.com/twilio-labs/paste/pull/364#pullrequestreview-388426612
- https://github.com/twilio-labs/paste/pull/364#pullrequestreview-388427449
=> fix(website): minor text changes for textarea doc

packages/paste-core/components/modal/package.json, packages/paste-core/components/modal/stories/index.stories.tsx, packages/paste-website/package.json, packages/paste-website/src/component-examples/ModalExamples.ts, packages/paste-website/src/components/shortcodes/live-preview/index.tsx, packages/paste-website/src/pages/components/modal/index.mdx
=> docs(website): add modal doc page

package.json
=> chore: update version number for 2020.04.09 release

packages/paste-website/src/components/tokens-list/index.tsx, packages/paste-website/src/pages/getting-started/engineering.mdx
Some folks not using Console, like internal tools, would like better instructions on how to load Whitney as it's not already installed. 
Include guidelines on how to  do this.
=> fix(website): include more details around loading the Whitney font

packages/paste-website/src/pages/tokens/index.mdx
Changing description on tokens to a more meaningful one based on @katieporter's recent doc.
=> docs(website): update token description

packages/paste-website/src/pages/getting-started/engineering.mdx
I realised we're missing a couple deps for getting started with Paste.
=> chore(website): add missing getting started deps

yarn.lock
Missed an update to the lockfile earlier today
=> chore: updating the lockfile

packages/paste-core/components/separator/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/separator/__tests__/index.spec.tsx, packages/paste-core/components/separator/package.json, packages/paste-core/components/separator/rollup.config.js, packages/paste-core/components/separator/src/index.tsx, packages/paste-core/components/separator/stories/index.stories.tsx, packages/paste-core/components/separator/tsconfig.build.json, packages/paste-core/components/separator/tsconfig.json, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/core-bundle/tools/generate.js, packages/paste-style-props/src/proptypes/layout.ts, packages/paste-style-props/src/types/layout.ts, packages/paste-website/package.json, packages/paste-website/src/components/StyledHr.tsx, packages/paste-website/src/components/paste-mdx-provider/index.tsx, packages/paste-website/src/pages/components/modal/index.mdx, packages/paste-website/src/pages/components/separator/index.mdx, packages/paste-website/src/pages/index.tsx
- Add ability to use `auto` in heights and widths
- create the separator package
- add the separator docs
- replace our custom style hr with our separator
=> feat(separator): create the separator component

packages/paste-website/src/pages/icon-system/index.mdx
=> fix(docs): remove todo callout in icons

packages/paste-core/components/modal/src/Modal.tsx, packages/paste-core/components/modal/src/ModalHeader.tsx
=> fix(modal): reset margin on heading, add zIndex to overlay

packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/layout/stack/__tests__/__snapshots__/stack.test.tsx.snap, packages/paste-core/layout/stack/__tests__/stack.test.tsx, packages/paste-core/layout/stack/package.json, packages/paste-core/layout/stack/rollup.config.js, packages/paste-core/layout/stack/src/index.tsx, packages/paste-core/layout/stack/stories/index.stories.tsx, packages/paste-core/layout/stack/tsconfig.build.json, packages/paste-core/layout/stack/tsconfig.json
=> feat(stack): add stack component package

packages/paste-core/components/alert/package.json
Bumping Alert component to production status
=> docs(website): promote alert to production status

packages/paste-website/src/pages/index.tsx
Removing links to legacy libraries
=> docs(website): remove links to legacy libraries

packages/paste-core/layout/stack/package.json, packages/paste-website/package.json, packages/paste-website/src/pages/layout/stack/index.mdx
=> feat(website): add stack doc page

packages/paste-core/components/form/src/FormInput.tsx, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/core-bundle/tsconfig.build.json, packages/paste-core/primitives/combobox/package.json, packages/paste-core/primitives/combobox/rollup.config.js, packages/paste-core/primitives/combobox/src/index.tsx, packages/paste-core/primitives/combobox/stories/index.stories.tsx, packages/paste-core/primitives/combobox/tsconfig.build.json, packages/paste-core/primitives/combobox/tsconfig.json, packages/paste-libraries/dropdown/package.json, packages/paste-libraries/dropdown/rollup.config.js, packages/paste-libraries/dropdown/src/index.tsx, packages/paste-libraries/dropdown/tsconfig.build.json, packages/paste-libraries/dropdown/tsconfig.json, yarn.lock
=> feat(combobox-primitive): add combobox-primitive package

packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx
Replace "(Link TBD)" with link to styled Modal in intro paragraph
https://paste-git-featmodal-primitive-docs-add-link-to-styled-modal.twilio-dsys.now.sh/primitives/modal-dialog-primitive
=> feat(Modal primitive docs): add link to styled Modal

packages/paste-libraries/animation/README.md, packages/paste-libraries/animation/package.json, packages/paste-libraries/animation/rollup.config.js, packages/paste-libraries/animation/src/index.tsx, packages/paste-libraries/animation/tsconfig.build.json, packages/paste-libraries/animation/tsconfig.json, yarn.lock
Adds react-spring v9 as our animation library of choice, as the `@twilio-paste/animation` library.  **Beta**, no docs until we're completely satisfied with this choice.
=> feat: add paste animation library

README.md
Tiny update to remove TODO link
=> docs(repo): Update readme

packages/paste-website/src/pages/getting-started/engineering.mdx, packages/paste-website/src/pages/principles/index.mdx
=> docs(website): trim extraneous content

packages/paste-libraries/animation/README.md, packages/paste-libraries/animation/package.json, yarn.lock
=> fix(animation-library): downgrade to v8, making package public

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/combobox/__tests__/index.spec.tsx, packages/paste-core/components/combobox/package.json, packages/paste-core/components/combobox/rollup.config.js, packages/paste-core/components/combobox/src/Combobox.tsx, packages/paste-core/components/combobox/src/ComboboxInputWrapper.tsx, packages/paste-core/components/combobox/src/ComboboxListbox.tsx, packages/paste-core/components/combobox/src/ComboboxListboxOption.tsx, packages/paste-core/components/combobox/src/index.tsx, packages/paste-core/components/combobox/stories/index.stories.tsx, packages/paste-core/components/combobox/tsconfig.build.json, packages/paste-core/components/combobox/tsconfig.json, packages/paste-core/components/form/src/FormInput.tsx, packages/paste-core/components/form/src/index.tsx, packages/paste-core/components/form/src/shared/FormControlWrapper.tsx, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/combobox/src/index.tsx, packages/paste-libraries/dropdown/src/index.tsx
=> feat(combobox): add combobox package

packages/paste-website/package.json, packages/paste-website/src/component-examples/DisclosurePrimitiveExamples.ts, packages/paste-website/src/pages/primitives/disclosure-primitive/index.mdx
Documenting the Disclosure Primitive on the Paste doc site.
=> feat(website): add disclosure primitive docs

packages/paste-core/components/form/__tests__/select/select.test.tsx, packages/paste-core/components/form/src/select/Select.tsx, packages/paste-core/components/form/stories/select.stories.tsx
- Fix right spacing
- Fix long text overflow
- Add data attribute to prevent console bootstrap seletize overrides
=> fix(select): bug fixes

package.json
=> chore: update Paste release version

packages/paste-website/src/component-examples/MenuExamples.ts, packages/paste-website/src/pages/components/heading/index.mdx, packages/paste-website/src/pages/components/list/index.mdx, packages/paste-website/src/pages/components/paragraph/index.mdx
=> docs(website): more component updates

packages/paste-core/primitives/tabs/stories/index.stories.tsx, packages/paste-website/package.json, packages/paste-website/src/component-examples/ComboboxPrimitiveExamples.ts, packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx
=> docs(website): combobox primitive docs

packages/paste-website/src/pages/form-elements/checkbox/index.mdx, packages/paste-website/src/pages/form-elements/select/index.mdx
1. Select Component
2. Checkbox Component
=> docs(website): update form components for content

packages/paste-website/src/component-examples/ModalExamples.ts, packages/paste-website/src/pages/form-elements/select/index.mdx
Small change to our doc site's examples. Simply changes a couple of the names in the examples.
=> chore(website): changing the names in some examples

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/combobox/src/Combobox.tsx, packages/paste-core/components/combobox/stories/index.stories.tsx, packages/paste-core/components/form/src/select/Select.tsx
=> fix(combobox): sync styles with Select styles

packages/paste-website/gatsby-config.js
Temporarily disabling the Algolia indexing until we figure out a better plan for indexing.
=> fix(website): disabled algolia indexing temporarily

packages/paste-website/src/pages/tokens/index.mdx
Shorten Tokens description so it's more scannable in the search box
=> feat(tokens docs): shorten description

packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/non-modal-dialog/package.json, packages/paste-core/primitives/non-modal-dialog/rollup.config.js, packages/paste-core/primitives/non-modal-dialog/src/index.tsx, packages/paste-core/primitives/non-modal-dialog/stories/index.stories.tsx, packages/paste-core/primitives/non-modal-dialog/tsconfig.build.json, packages/paste-core/primitives/non-modal-dialog/tsconfig.json, packages/paste-libraries/reakit/src/index.tsx
=> feat(non-modal-dialog-primitive): add non-modal dialog primitive package

packages/paste-website/src/component-examples/TabsExamples.ts, packages/paste-website/src/pages/components/tabs/index.mdx
Adding the docs for the alpha Tabs component.
=> docs(website): adding Tabs alpha component documentation

packages/paste-website/src/pages/content/get-support.mdx, packages/paste-website/src/pages/content/product-style-guide.mdx, packages/paste-website/src/pages/content/voice-and-tone.mdx
Replaces https://github.com/twilio-labs/paste/pull/445 after a really nasty update on master meant the rebase was just too difficult to do. So just replaced the changes on a totally clean branch off of master.
=> feat(website): updated content guidance

package.json, packages/paste-core/components/popover/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/popover/__tests__/index.spec.tsx, packages/paste-core/components/popover/package.json, packages/paste-core/components/popover/rollup.config.js, packages/paste-core/components/popover/src/Popover.tsx, packages/paste-core/components/popover/src/PopoverArrow.tsx, packages/paste-core/components/popover/src/PopoverButton.tsx, packages/paste-core/components/popover/src/PopoverContainer.tsx, packages/paste-core/components/popover/src/PopoverContext.tsx, packages/paste-core/components/popover/src/index.tsx, packages/paste-core/components/popover/stories/index.stories.tsx, packages/paste-core/components/popover/tsconfig.build.json, packages/paste-core/components/popover/tsconfig.json, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/non-modal-dialog/src/index.tsx, packages/paste-libraries/reakit/package.json, packages/paste-libraries/reakit/src/Popover/PopoverArrow.tsx, packages/paste-libraries/reakit/src/index.tsx, packages/paste-theme/src/index.tsx, yarn.lock
=> feat(popover): add popover package

README.md, package.json, tools/utils/link-local-packages.sh, tools/utils/unlink-local-packages.sh
=> chore: added linking scripts and updated readme

package.json
=> chore: remove styling library dep from main package.json

packages/paste-website/src/pages/components/spinner/index.mdx
Adding the docs page for the spinner
=> docs(spinner): add the spinner docs page

packages/paste-website/src/components/site-wrapper/SiteBody.tsx, packages/paste-website/src/components/site-wrapper/sidebar/index.tsx
=> fix(website): fix website scrolling

packages/paste-core/components/form/__tests__/select/option.test.tsx, packages/paste-core/components/form/__tests__/select/optiongroup.test.tsx, packages/paste-core/components/form/__tests__/select/select.test.tsx, packages/paste-core/primitives/modal-dialog/src/index.tsx, packages/paste-icons/tools/actions/convertNewAction.js, packages/paste-icons/tools/actions/listIconsAction.js, packages/paste-icons/tools/constants.js, packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx, packages/paste-website/src/pages/primitives/disclosure-primitive/index.mdx, packages/paste-website/src/pages/primitives/menu-primitive/index.mdx, packages/paste-website/src/pages/primitives/modal-dialog-primitive/index.mdx
uses blocklist/allowlist instead
=> chore: replace oppressive blacklist/whitelist

packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/tooltip/package.json, packages/paste-core/primitives/tooltip/rollup.config.js, packages/paste-core/primitives/tooltip/src/index.tsx, packages/paste-core/primitives/tooltip/stories/index.stories.tsx, packages/paste-core/primitives/tooltip/tsconfig.build.json, packages/paste-core/primitives/tooltip/tsconfig.json, packages/paste-libraries/reakit/src/Tooltip/TooltipArrow.tsx, packages/paste-libraries/reakit/src/index.tsx, packages/paste-website/package.json, packages/paste-website/src/component-examples/TooltipPrimitiveExamples.ts, packages/paste-website/src/pages/primitives/tooltip-primitive/index.mdx
TODO: Add changelog after initial package publish.
=> feat(tooltip-primitive): add tooltip-primitive package

packages/paste-website/src/pages/primitives/tooltip-primitive/index.mdx
=> docs(website): add tooltip-primitive changelog

packages/paste-website/src/pages/getting-started/engineering.mdx
Small typo on the eng guidelines page :)
=> chore(website): small typo, usings -> using

now-build.sh, packages/paste-core/components/disclosure/CHANGELOG.md, packages/paste-core/components/disclosure/__tests__/disclosure.test.tsx, packages/paste-core/components/disclosure/package.json, packages/paste-core/components/disclosure/rollup.config.js, packages/paste-core/components/disclosure/src/Disclosure.tsx, packages/paste-core/components/disclosure/src/DisclosureContent.tsx, packages/paste-core/components/disclosure/src/DisclosureHeading.tsx, packages/paste-core/components/disclosure/src/index.tsx, packages/paste-core/components/disclosure/stories/index.stories.tsx, packages/paste-core/components/disclosure/tsconfig.build.json, packages/paste-core/components/disclosure/tsconfig.json, packages/paste-core/components/heading/src/PropTypes.ts, packages/paste-core/components/heading/src/index.tsx, packages/paste-core/components/heading/src/types.ts, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/disclosure/src/index.tsx, packages/paste-libraries/reakit/src/index.tsx, packages/paste-website/package.json, packages/paste-website/src/pages/components/disclosure/index.mdx
=> feat(disclosure): Create and document the disclosure

.github/workflows/chromatic.yml, .github/workflows/publish.yml
=> chore: remove publish checks

packages/paste-website/src/pages/getting-started/design/index.mdx
=> Add design guidelines

packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/menu/__tests__/index.spec.tsx, packages/paste-core/components/menu/src/index.tsx, packages/paste-core/components/menu/stories/index.stories.tsx, packages/paste-website/src/component-examples/MenuExamples.ts, packages/paste-website/src/pages/components/menu/index.mdx
=> feat(menu): add MenuGroup component

packages/paste-core/components/disclosure/__tests__/disclosure.test.tsx, packages/paste-core/components/disclosure/src/Disclosure.tsx, packages/paste-core/components/disclosure/stories/index.stories.tsx, packages/paste-website/src/component-examples/DisclosureExamples.ts, packages/paste-website/src/pages/components/disclosure/index.mdx
=> feat(disclosure): add state prop

packages/paste-website/src/components/ThemeSwitcher.tsx, packages/paste-website/src/components/site-wrapper/SiteBody.tsx
1. Removed SendGrid from switcher
2. Changed Console to "Current" and Paste to "Preview"
3. Updated warning alert text
=> feat(web): updated theme switcher and alert text

packages/paste-website/src/components/site-wrapper/SiteBody.tsx
1. Renamed BLM specific naming to "PSA"
2. Changed content to tribute Rep. John Lewis
=> docs(web): update alert to a generic PSA and new content

packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
=> Remove release version

packages/paste-core/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, packages/paste-core/components/tabs/src/Tab.tsx, packages/paste-core/components/tabs/src/TabList.tsx, packages/paste-core/components/tabs/src/Tabs.tsx, packages/paste-core/components/tabs/src/TabsContext.tsx, packages/paste-core/components/tabs/src/types.ts, packages/paste-core/components/tabs/stories/index.stories.tsx, packages/paste-core/primitives/box/src/index.tsx, packages/paste-website/src/component-examples/TabsExamples.ts, packages/paste-website/src/pages/components/tabs/index.mdx
=> feat(tabs): fitted tabs and update styles

packages/paste-core/components/tooltip/src/TooltipArrow.tsx, packages/paste-core/components/tooltip/src/index.tsx, packages/paste-core/components/tooltip/stories/index.stories.tsx, packages/paste-design-tokens/tokens/aliases/box-shadow.yml, packages/paste-design-tokens/tokens/aliases/offset.yml, packages/paste-design-tokens/tokens/global/box-shadow.yml, packages/paste-design-tokens/tokens/themes/console/aliases/box-shadow.yml, packages/paste-design-tokens/tokens/themes/console/aliases/offset.yml, packages/paste-design-tokens/tokens/themes/console/global/box-shadow.yml, packages/paste-design-tokens/tokens/themes/sendgrid/aliases/box-shadow.yml, packages/paste-design-tokens/tokens/themes/sendgrid/global/box-shadow.yml, packages/paste-website/src/pages/components/tooltip/index.mdx
Update the design of tooltips for UDL. Includes introducing 2 new tokens.
- add color-background-body-inverse
- add shadow
- update elevation tokens for default theme
- update background
- update border
- update spacing
- update color
=> feat(tooltips): update tooltips design for UDL

packages/paste-website/src/pages/getting-started/engineering/index.mdx
=> fix(website): fix icons yarn install command

packages/paste-core/components/tabs/__tests__/tabs.test.tsx, packages/paste-core/components/tabs/src/Tabs.tsx, packages/paste-core/components/tabs/stories/index.stories.tsx, packages/paste-website/src/component-examples/TabsExamples.ts, packages/paste-website/src/pages/components/tabs/index.mdx
=> feat(tabs): add state prop

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/button/__tests__/__snapshots__/button.test.tsx.snap, packages/paste-core/components/button/package.json, packages/paste-core/components/button/src/DestructiveButton.tsx, packages/paste-core/components/button/src/DestructiveLinkButton.tsx, packages/paste-core/components/button/src/LinkButton.tsx, packages/paste-core/components/button/src/PrimaryButton.tsx, packages/paste-core/components/button/src/ResetButton.tsx, packages/paste-core/components/button/src/SecondaryButton.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/styles.ts, packages/paste-core/components/button/src/types.ts, packages/paste-core/components/button/stories/index.stories.tsx, packages/paste-core/components/button/tsconfig.build.json, packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/popover/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/layout/stack/src/index.tsx, packages/paste-core/primitives/box/src/BoxPropTypes.ts, packages/paste-core/primitives/box/src/PseudoPropStyles.ts, packages/paste-core/primitives/box/src/index.tsx, packages/paste-core/primitives/combobox/stories/index.stories.tsx, packages/paste-style-props/src/proptypes/background.ts, packages/paste-style-props/src/proptypes/border.ts, packages/paste-style-props/src/proptypes/typography.ts, packages/paste-style-props/src/types/background.ts, packages/paste-style-props/src/types/typography.ts
Button now uses Box under the hood
=> chore(button): convert to use Box

packages/paste-website/src/pages/content/product-style-guide/index.mdx, packages/paste-website/src/pages/content/voice-and-tone/index.mdx
Trialling *** to create section separation - change of date formatting and refinement of some other points following feedback
=> fix(website): sectioning and content edits

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/combobox/src/Combobox.tsx, packages/paste-core/components/combobox/stories/index.stories.tsx, packages/paste-core/components/form/__tests__/__snapshots__/formInput.test.tsx.snap, packages/paste-core/components/form/__tests__/__snapshots__/formhelptext.test.tsx.snap, packages/paste-core/components/form/__tests__/__snapshots__/formlabel.test.tsx.snap, packages/paste-core/components/form/__tests__/formlabel.test.tsx, packages/paste-core/components/form/src/Checkbox.tsx, packages/paste-core/components/form/src/FormHelpText.tsx, packages/paste-core/components/form/src/FormInput.tsx, packages/paste-core/components/form/src/FormLabel.tsx, packages/paste-core/components/form/src/FormTextArea.tsx, packages/paste-core/components/form/src/select/Select.tsx, packages/paste-core/components/form/src/shared/FormControlWrapper.tsx, packages/paste-core/components/form/src/shared/Prefix.tsx, packages/paste-core/components/form/src/shared/Suffix.tsx, packages/paste-core/components/form/stories/input.stories.tsx, packages/paste-core/components/form/stories/select.stories.tsx, packages/paste-core/components/form/stories/textarea.stories.tsx, packages/paste-website/src/component-examples/ComboboxExamples.ts, packages/paste-website/src/pages/components/combobox/index.mdx, packages/paste-website/src/pages/form-elements/input/index.mdx, packages/paste-website/src/pages/form-elements/select/index.mdx, packages/paste-website/src/pages/form-elements/textarea/index.mdx
=> feat(form): update form elements for UDL

packages/paste-core/components/avatar/__tests__/__snapshots__/avatar.test.tsx.snap, packages/paste-core/components/avatar/src/index.tsx, packages/paste-website/src/pages/components/avatar/index.mdx
Updating the Avatar design:
- change background color token to user
- change the font weight to bold
=> feat(avatar): change background and font weight for initials

packages/paste-website/src/pages/components/button/index.mdx
Remove example. Inverse, what inverse. Nothing to see here
=> docs(button): remove example

packages/paste-libraries/styling/package.json
Fixes https://github.com/twilio-labs/paste/discussions/659
=> chore(styling-library): types packages as deps  from devDeps

packages/paste-website/src/pages/getting-started/working-guide/index.mdx
=> fix(how to work with us): typo fixes

packages/paste-website/src/pages/content/voice-and-tone/index.mdx
Wording change 'right' > 'that works'
=> fix(website): wording change

packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/separator/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/separator/src/index.tsx
- Update border color to `color-border-light`
- Update border width to `border-width-10`
=> feat(separator): change color to border-light and width to width-10

packages/paste-core/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, packages/paste-core/components/tabs/package.json, packages/paste-core/components/tabs/src/Tab.tsx, packages/paste-core/components/tabs/tsconfig.build.json, packages/paste-website/src/pages/components/tabs/index.mdx
=> chore(tabs): update to UDL styles

README.md
=> chore: updating the README

packages/paste-core/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, packages/paste-core/components/tabs/src/Tab.tsx, packages/paste-website/gatsby-config.js, packages/paste-website/src/utils/algolia.js
=> chore(website): set up env based search indexing

packages/paste-website/src/pages/getting-started/working-guide/index.mdx
1. Fix broken slug
2. Update page content
=> docs(working-guide): fix broken slug and content

.codesandbox/ci.json, examples/create-react-app/.gitignore, examples/create-react-app/README.md, examples/create-react-app/package.json, examples/create-react-app/src/index.tsx, examples/create-react-app/src/react-app-env.d.ts, examples/create-react-app/src/serviceWorker.ts, examples/create-react-app/tsconfig.json, package.json
Allow testing the packages in codesandbox in PRs using a create react app example as the bootstrap for the sandbox.
=> chore: add codesandbox ci integration

packages/paste-website/gatsby-config.js, packages/paste-website/src/components/site-wrapper/SiteHeader.tsx
=> chore(website): comment out search

packages/paste-core/components/anchor/__tests__/__snapshots__/anchor.test.tsx.snap, packages/paste-core/components/anchor/__tests__/anchor.test.tsx, packages/paste-core/components/anchor/package.json, packages/paste-core/components/anchor/src/index.tsx, packages/paste-core/components/anchor/tsconfig.build.json, packages/paste-core/components/form/__tests__/__snapshots__/formlabel.test.tsx.snap, packages/paste-core/primitives/text/__tests__/__snapshots__/text.spec.tsx.snap, packages/paste-core/primitives/text/src/SafelySpreadProps.ts, packages/paste-core/primitives/text/src/index.tsx
=> chore(anchor): refactor to use Text

packages/paste-website/src/pages/getting-started/about-paste/index.mdx
=> docs(about): update about page

packages/paste-website/src/components/shortcodes/ChangelogRevealer.tsx, packages/paste-website/src/components/shortcodes/PageAside.tsx
Added a couple of IDs to content we need to remove from the DocSearch index.
=> chore(website): add ids for search indexing

packages/paste-website/src/pages/getting-started/about-paste/index.mdx
Small language shift on the About page to change "consistent" to "cohesive".
=> docs(about): update language

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/button/src/DestructiveLinkButton.tsx, packages/paste-core/components/button/src/InverseLinkButton.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/types.ts, packages/paste-core/components/button/stories/index.stories.tsx, packages/paste-website/src/pages/components/button/index.mdx
=> feat(button): add inverse_link button variant

.codesandbox/ci.json
=> chore: make codesandbox actually build and use core on PRs

packages/paste-website/src/pages/index.tsx
Small PR to tide us over to the new homepage
1. Added a What's New card
2. Refactored the page to use Grid.
3. Updated imports to use core
=> docs(homepage): add a whats new card

packages/paste-style-props/src/proptypes/typography.ts, packages/paste-style-props/src/types/typography.ts
Add the ability to inherit color and font-weight in the style-props
=> fix(style-props): add inherit to fontWeight to color

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/illustrations/index.mdx, packages/paste-website/src/pages/index.tsx
Create an illustration page that links to the brand repository.
=> docs(illos): create illustrations page

README.md
=> fix(README): typo in "Developing on Paste"

packages/paste-core/components/tooltip/__test__/index.spec.tsx, packages/paste-core/components/tooltip/src/index.tsx, packages/paste-core/components/tooltip/stories/index.stories.tsx, packages/paste-website/src/component-examples/TooltipExamples.ts, packages/paste-website/src/pages/components/tooltip/index.mdx
=> feat(tooltip): add state hook prop

package.json, packages/paste-website/package.json, yarn.lock
=> chore: bump lodash to 4.17.19

packages/paste-website/src/pages/components/alert/index.mdx
Remove the "click here" language from Do / Don't since it's not recommended.
=> docs(alert): update dos and dont's

packages/paste-website/src/pages/primitives/text/index.mdx
=> docs(text): typo in props table

packages/paste-core/components/truncate/package.json, packages/paste-website/src/pages/components/truncate/index.mdx
=> docs(truncate): add usage documentation

packages/paste-website/src/components/site-wrapper/SiteBody.tsx
Updated PSA Alert to tribute RBG
=> docs(psa): updated tribute to RBG

packages/paste-core/layout/media-object/package.json, packages/paste-website/src/pages/layout/media-object/index.mdx
1. Update Media Object Title
2. Update Package JSON
=> docs(media object): update description

packages/paste-core/components/anchor/__tests__/anchor.test.tsx, packages/paste-core/components/anchor/package.json, packages/paste-core/components/anchor/src/DefaultAnchor.tsx, packages/paste-core/components/anchor/src/InverseAnchor.tsx, packages/paste-core/components/anchor/src/index.tsx, packages/paste-core/components/anchor/src/types.ts, packages/paste-core/components/anchor/tsconfig.build.json
=> fix(anchor): allow layout and space props

packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/stories/index.stories.tsx, packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/popover/__tests__/__snapshots__/index.spec.tsx.snap
=> fix(button): center content within buttons

packages/paste-website/src/pages/components/avatar/index.mdx
=> fix(website): dead link on icons page

packages/paste-website/src/pages/content/writing-for-components/index.mdx
- [Y] I acknowledge that all my contributions will be made under the project's license.
=> fix(website): updating delivery estimate

packages/paste-core/components/combobox/src/Combobox.tsx
=> fix(combobox): hide chevron if set to autocomplete

.storybook/addons/theme-switcher-addon/index.js, .storybook/addons/theme-switcher-addon/register.js, packages/paste-website/src/components/ThemeSwitcher.tsx, packages/paste-website/src/components/site-wrapper/SiteBody.tsx, packages/paste-website/src/components/site-wrapper/SiteHeader.tsx, packages/paste-website/src/components/site-wrapper/sidebar/index.tsx, packages/paste-website/src/context/ActiveSiteThemeContext.tsx, packages/paste-website/src/pages/index.tsx
=> feat(website): switch the theme switcher to default to default

cypress/integration/e2e/sidebar-navigation/index.spec.ts, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/inclusive-design/index.mdx
Create a checklist for inclusive design and engineering practices. 
References:
- https://github.com/Heydon/inclusive-design-checklist
Tasks:
=> docs(website): start  inclusive design checklist

packages/paste-core/primitives/tabs/package.json, packages/paste-website/package.json, packages/paste-website/src/component-examples/TabsPrimitiveExamples.ts, packages/paste-website/src/pages/primitives/tabs-primitive/index.mdx
Add usage documentation to tabs primitive
=> docs(tabs-primitive): usage guides

packages/paste-core/components/breadcrumb/__tests__/breadcrumb.spec.tsx, packages/paste-core/components/breadcrumb/package.json, packages/paste-core/components/breadcrumb/rollup.config.js, packages/paste-core/components/breadcrumb/src/index.tsx, packages/paste-core/components/breadcrumb/stories/index.stories.tsx, packages/paste-core/components/breadcrumb/tsconfig.build.json, packages/paste-core/components/breadcrumb/tsconfig.json, packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/breadcrumb.tsx, packages/paste-core/core-bundle/src/index.tsx
=> feat(breadcrumb): add alpha component package

packages/paste-website/package.json, packages/paste-website/src/pages/components/breadcrumb/index.mdx
=> docs(breadcrumb): add doc page to website

packages/paste-core/components/button/__tests__/button.test.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/styles.ts, packages/paste-core/components/button/src/types.ts, packages/paste-core/components/button/stories/index.stories.tsx, packages/paste-website/src/pages/components/button/index.mdx
=> feat(button): add icon_small size

packages/paste-core/components/combobox/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/combobox/src/ComboboxListbox.tsx, packages/paste-core/components/combobox/stories/index.stories.tsx
=> fix(combobox): bump listbox zIndex token

packages/paste-website/src/pages/components/modal/index.mdx
=> docs(modal): update alert dialog link

packages/paste-website/src/components/site-wrapper-new/SiteBody.tsx, packages/paste-website/src/components/site-wrapper-new/SiteThemeProvider.tsx, packages/paste-website/src/components/site-wrapper-new/sidebar/index.tsx
Setup responsive structure for home page
=> feat(website): setup responsive home page structure

packages/paste-website/src/pages/getting-started/about-paste/index.mdx, packages/paste-website/src/pages/primitives/non-modal-dialog-primitive/index.mdx
- https://paste-git-fixwebsite-typos-on-non-modal-dialog-and-about.twilio-dsys.vercel.app/primitives/non-modal-dialog-primitive#styling-a-custom-non-modal-dialog
- https://paste-git-fixwebsite-typos-on-non-modal-dialog-and-about.twilio-dsys.vercel.app/getting-started/about-paste
=> fix(website): typo on non-modal dialog primitive docs

.vscode/component.code-snippets, .vscode/extensions.json, .vscode/settings.json
Thought I'd add some of my code snippets to the workspace and fix the recommened extensions for VS code
https://www.loom.com/share/27dab56d585449acad39b5ce95554c09
=> chore: add some workspace code snippets, fix recommended ext

.gitignore, packages/paste-core/components/anchor/src/InverseAnchor.tsx
[Design decision for reference.](https://app.abstract.com/projects/39ed9aa7-cca8-4e4f-8f16-d8f9d36d251a/branches/71b49dff-ba10-4c60-8a94-2b8b6b5cf72e/commits/2b802b2306c5b2697db890120b289fd6eb3924d6/files/6a521d86-90ac-4db8-83b6-9dbfd0c84e7f/layers/E646374D-CF7C-4115-A112-251F08B8695B)
=> fix(anchor): change hover, focus, active color for accessibility

packages/paste-website/src/components/homepage/Experiment.tsx, packages/paste-website/src/pages/index.tsx
=> feat(website): add experiment section

packages/paste-website/src/components/SlantedBackgroundGradient.tsx, packages/paste-website/src/components/homepage/GetStartedInclusive.tsx, packages/paste-website/src/components/homepage/GetStartedRunning.tsx, packages/paste-website/src/components/homepage/GetStartedWhy.tsx, packages/paste-website/src/components/homepage/NewComponentBanner.tsx, packages/paste-website/src/components/homepage/PopularComponentCard.tsx, packages/paste-website/src/components/site-wrapper/SiteBody.tsx, packages/paste-website/src/components/site-wrapper/sidebar/index.tsx, packages/paste-website/src/components/site-wrapper/site-footer/SiteFooterHeader.tsx, packages/paste-website/src/components/site-wrapper/site-footer/SiteFooterNav.tsx, packages/paste-website/src/components/site-wrapper/site-footer/index.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderDesktop.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderLogo.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderMobile.tsx
Unhide the hero from screen readers.
Update the document hierarchy with correct heading levels
Make a single nav in the footer
=> fix: new homepage a11y tweaks

packages/paste-website/src/components/icons-list/IconsList.tsx
Make the icon list page a little nicer on responsive screens
=> fix: new homepage icon list responsive

packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderMobile.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderMobileNavigation.tsx
Noticed the close button didn't have button text or label. 
Removed necessary label logic on the open button.
=> fix(website): mobile nav button text

packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderMobileSearch.tsx
=> docs(mobile search): added more cool links

packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/customization.tsx, packages/paste-customization/README.md, packages/paste-customization/__fixtures__/mockThemes.ts, packages/paste-customization/__tests__/CustomizationProvider.test.tsx, packages/paste-customization/__tests__/utils.test.ts, packages/paste-customization/package.json, packages/paste-customization/rollup.config.js, packages/paste-customization/src/CustomizationProvider.tsx, packages/paste-customization/src/index.tsx, packages/paste-customization/src/types.ts, packages/paste-customization/src/utils.ts, packages/paste-customization/stories/customization.stories.tsx, packages/paste-customization/tsconfig.build.json, packages/paste-customization/tsconfig.json, packages/paste-theme/src/index.tsx, packages/paste-theme/src/themeProvider.tsx
Allow ability to be able to provide a custom theme to a Paste app via the `CustomizationProvider`
=> feat: customization provider package

packages/paste-website/src/components/ContactUsMenu.tsx, packages/paste-website/src/components/SiteLink.tsx, packages/paste-website/src/components/ThemeSwitcher.tsx, packages/paste-website/src/components/homepage/Experiment.tsx, packages/paste-website/src/components/homepage/GetStartedCardLink.tsx, packages/paste-website/src/components/homepage/GetStartedInclusive.tsx, packages/paste-website/src/components/homepage/GetStartedRunning.tsx, packages/paste-website/src/components/homepage/GetStartedWhy.tsx, packages/paste-website/src/components/homepage/HomeHero.tsx, packages/paste-website/src/components/homepage/NewComponentBannerLink.tsx, packages/paste-website/src/components/homepage/PopularComponents.tsx, packages/paste-website/src/components/homepage/PopularPatterns.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarAnchor.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarDisclosureButton.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/components/site-wrapper/site-footer/SiteFooterNav.tsx, packages/paste-website/src/components/site-wrapper/site-header/GithubLink.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderLogo.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderSearch.tsx
Reference doc: https://docs.google.com/document/d/11HTG8gbDcX-zsHXW2RDETJBKq3tKRVz-3BINYBdJiSU/edit#
=> chore(website): add event tracking to home, nav, and footer

packages/paste-token-designer/components/layout/editor-wrapper/index.js, packages/paste-token-designer/components/preview/index.js
Adds a modal to copy paste the modified theme for use in your own app
=> feat(token-designer): add export functionality

packages/paste-theme/src/generateTokensFromTheme.ts, packages/paste-theme/src/index.tsx, packages/paste-theme/src/types/GenericTokenShape.ts, packages/paste-token-designer/components/layout/editor-wrapper/ExportModal.js, packages/paste-token-designer/components/layout/editor-wrapper/ImportModal.js, packages/paste-token-designer/components/layout/editor-wrapper/index.js, packages/paste-token-designer/components/preview/index.js, packages/paste-token-designer/components/token-option/ColorTokenInput.js, packages/paste-token-designer/components/token-option/FontTokenInput.js, packages/paste-token-designer/components/token-option/TextTokenInput.js, packages/paste-token-designer/components/token-option/UnitTokenInput.js, packages/paste-token-designer/components/token-option/index.js, packages/paste-token-designer/context/TokenContext.js, packages/paste-token-designer/package.json, packages/paste-token-designer/pages/_app.js
=> feat: add import theme button and modal

now.json
Test seeing if vercel still builds
=> chore: allow for multiple sites by removing build from now config

cypress.json, cypress/fixtures/example.json, cypress/integration/e2e/sidebar-navigation/index.spec.ts, cypress/integration/e2e/theme-switcher/index.spec.ts
Enable retries
Delay start of tests
=> chore: cypress flaky tests

packages/paste-website/src/components/SkipLinkContainer.tsx, packages/paste-website/src/components/site-wrapper/SiteBody.tsx, packages/paste-website/src/components/site-wrapper/index.tsx, packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderSearch.tsx, packages/paste-website/src/constants.ts
=> feat(website): add content and search skip links

packages/paste-core/components/table/__tests__/index.spec.tsx, packages/paste-core/components/table/package.json, packages/paste-core/components/table/src/TBody.tsx, packages/paste-core/components/table/src/TFoot.tsx, packages/paste-core/components/table/src/THead.tsx, packages/paste-core/components/table/src/Table.tsx, packages/paste-core/components/table/src/TableContext.tsx, packages/paste-core/components/table/src/Td.tsx, packages/paste-core/components/table/src/Th.tsx, packages/paste-core/components/table/src/Tr.tsx, packages/paste-core/components/table/src/constants.ts, packages/paste-core/components/table/src/types.ts, packages/paste-core/components/table/stories/index.stories.tsx
=> chore(table): borderless and striped, adjust styles, promote to beta

packages/paste-website/src/components/shortcodes/table-of-contents/index.tsx
=> chore(website): remove h4s from table of contents

packages/paste-core/components/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/menu/stories/index.stories.tsx, packages/paste-libraries/reakit/package.json, packages/paste-website/src/components/site-wrapper/sidebar/index.tsx, yarn.lock
=> chore(reakit-library): upgrade reakit

packages/paste-core/components/table/package.json, packages/paste-website/src/pages/components/table/index.mdx
=> docs(website): update table doc with beta content

.changeset/empty-carpets-pull.md, packages/paste-website/src/components/homepage/HomeHero.tsx, packages/paste-website/src/components/homepage/NewComponentBannerLink.tsx
Advertise the job ad on the homepage
=> feat(website): advertise eng manager job on homepage

.changeset/nervous-pugs-roll.md, .changeset/silly-dodos-love.md, packages/paste-core/components/input/__tests__/input.test.tsx, packages/paste-core/components/input/src/Input.tsx, packages/paste-core/components/input/stories/input.stories.tsx, packages/paste-website/src/pages/components/input/index.mdx
Reference discussion: https://github.com/twilio-labs/paste/discussions/1111
=> fix(input): remove required from value prop, fixed type imports

.storybook/preview-head.html, packages/paste-core/components/avatar/stories/index.stories.tsx, packages/paste-core/components/menu/stories/index.stories.tsx, packages/paste-core/components/popover/stories/index.stories.tsx, packages/paste-core/components/tooltip/stories/index.stories.tsx
Try and get Chromatic to pass all the time when you don't actually change anything in a component.
=> chore: delay some flakey chromatic snapshots

packages/paste-website/src/pages/getting-started/engineering/index.mdx
Added content to Engineering guidelines page about handling icon errors in Jest.
=> docs(website): add content about icon errors in jest

packages/paste-website/src/components/homepage/HomeHero.tsx
Changed new banner to link to UX Engineer job posting.
=> chore(website): add ux engineer job link

packages/paste-website/src/pages/patterns/index.mdx
Add status to Pattern backlog to indicate if a pattern is in progress or open for contribution
=> feat: add status to Pattern backlog

.changeset/silly-ears-begin.md, packages/paste-core/components/help-text/package.json, packages/paste-core/components/input/package.json, packages/paste-core/components/modal/package.json, packages/paste-core/components/screen-reader-only/package.json, packages/paste-core/components/separator/package.json, packages/paste-core/components/table/package.json, packages/paste-core/components/toast/package.json, packages/paste-core/components/truncate/package.json, packages/paste-core/layout/aspect-ratio/package.json, packages/paste-core/layout/flex/package.json, packages/paste-core/layout/grid/package.json, packages/paste-core/layout/stack/package.json, packages/paste-core/primitives/combobox/package.json, packages/paste-core/primitives/disclosure/package.json, packages/paste-core/primitives/menu/package.json, packages/paste-core/primitives/modal-dialog/package.json, packages/paste-core/primitives/non-modal-dialog/package.json, packages/paste-core/primitives/tooltip/package.json, packages/paste-website/src/components/StatusLegend.tsx
Bump some beta components to production.
Clarify the language around component status and how safe they are to use.
=> chore: package status bump and status clarifications

.github/workflows/slack-notification.yml
This workflow fires a Slack message when a new release is published
=> chore: add slack bot workflow on release published

.github/workflows/vrt_main.yml, .github/workflows/vrt_pull_request.yml, package.json, packages/paste-core/components/modal/stories/index.stories.tsx, packages/paste-libraries/uid/stories/index.stories.tsx, yarn.lock
=> chore: stop using applitools for story vrt

packages/paste-core/components/tabs/src/Tab.tsx
Related to https://github.com/twilio-labs/paste/discussions/1244 and https://github.com/twilio-labs/paste/discussions/1250.
=> fix(tabs): broadening type definition on Tab component

packages/paste-website/src/components/site-wrapper/site-header/SiteHeaderDesktop.tsx
Smol PR to update the subheader on our doc site.
=> chore(website): update subheader text

packages/paste-website/src/pages/patterns/contribute/index.mdx
Added link to previous specs and updated a sentence
=> chore(website): update pattern docs

packages/paste-core/components/button/package.json
=> chore(button): Update package description

.changeset/pretty-pianos-clean.md, packages/paste-core/components/disclosure/src/DisclosureHeading.tsx, packages/paste-core/components/disclosure/stories/index.stories.tsx
A light solution to https://github.com/twilio-labs/paste/discussions/1331
=> fix(disclosure): allow headers to truncate correctly

.changeset/happy-phones-bow.md, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/stories/index.stories.tsx, packages/paste-website/src/pages/components/button/index.mdx, packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx
=> fix(button): conditionally use external link icon for anchor buttons

packages/paste-website/src/pages/components/list/index.mdx
Adding Mario Gonzalez to list of people killed by police.
=> feat(list): add mario gonzalez

.changeset/lemon-dolphins-help.md, packages/paste-core/components/pagination/__tests__/index.spec.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationArrowButton.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationArrowIconWrapper.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationBackArrow.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationForwardArrow.tsx, packages/paste-core/components/pagination/src/PaginationArrow/index.tsx, packages/paste-core/components/pagination/src/PaginationEllipsis.tsx, packages/paste-core/components/pagination/src/PaginationNumbers.tsx, packages/paste-core/components/pagination/src/proptypes.ts, packages/paste-core/components/pagination/src/types.ts, packages/paste-core/components/pagination/stories/index.stories.tsx, packages/paste-website/package.json, packages/paste-website/src/component-examples/PaginationExamples.ts, packages/paste-website/src/pages/components/pagination/index.mdx
=> docs(website): add pagination doc page

.changeset/good-bikes-exercise.md, .changeset/hot-hairs-drop.md, packages/paste-core/primitives/box/src/index.tsx, packages/paste-style-props/src/types/typography.ts, packages/paste-style-props/src/typography.ts
https://github.com/twilio-labs/paste/discussions/1396
=> feat(box): add overflow-wrap prop

netlify.toml, packages/paste-website/package.json, packages/paste-website/src/components/icons-list/IconsList.tsx, yarn.lock
Remove those really annoying warnings from the gatsby build and dev.
Also remove the vercel dep
=> chore: remove icons warning from website remove vercel dep

packages/paste-website/src/pages/components/input/index.mdx, packages/paste-website/src/pages/components/select/index.mdx
* Resolves missing component reference that was breaking rendering of the Input page
=> fix(site-input-page): resolve breaking error on site input page

package.json, plopfile.js, tools/plop-templates/build.hbs, tools/plop-templates/component-index.hbs, tools/plop-templates/component-stories.hbs, tools/plop-templates/component-tests.hbs, tools/plop-templates/package.hbs, tools/plop-templates/tsconfig.hbs, yarn.lock
Added a create:package script that creates new package starter files based on handlebar templates using plop.js. See it in action: https://www.loom.com/share/7e0b7a52b7744090925b50c99d8a372f
=> feat: add create-package script and file templates

packages/paste-website/src/pages/components/disclosure/index.mdx
Fixes: https://github.com/twilio-labs/paste/discussions/1469
=> fix(website): align content in DisclosureHeading example

packages/paste-website/src/pages/layout/flex/index.mdx
The Selective build seems to not work all the time. I'm seeing some builds on branches that don't have changes to the docsite. I think I got the script the wrong way round.
Also add the Flex API props update as a test to prove it works.
=> fix: update Flex components props 

.changeset/dirty-plums-do.md, .changeset/smooth-flies-own.md, .codesandbox/ci.json, packages/paste-core/components/alert-dialog/__tests__/index.spec.tsx, packages/paste-core/components/alert-dialog/build.js, packages/paste-core/components/alert-dialog/package.json, packages/paste-core/components/alert-dialog/src/index.tsx, packages/paste-core/components/alert-dialog/stories/index.stories.tsx, packages/paste-core/components/alert-dialog/tsconfig.json, packages/paste-core/components/modal/src/Modal.tsx, packages/paste-core/components/modal/src/ModalBody.tsx, packages/paste-core/components/modal/src/ModalFooter.tsx, packages/paste-core/components/modal/src/ModalHeader.tsx, packages/paste-core/components/modal/src/index.tsx, packages/paste-core/components/modal/src/styles.tsx, packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/alert-dialog.tsx, packages/paste-core/core-bundle/src/index.tsx
Created a new package for Alert Dialog component. Includes package w/:
- component code
- dependencies (for Modal)
- stories
- tests
=> feat(alert-dialog): create package

packages/paste-website/src/pages/components/avatar/index.mdx
Updated avatar examples for consistency
=> feat(docs): update avatar examples

packages/paste-core/components/toast/src/ErrorToast.tsx, packages/paste-core/components/toast/src/NeutralToast.tsx, packages/paste-core/components/toast/src/SuccessToast.tsx, packages/paste-core/components/toast/src/Toast.tsx, packages/paste-core/components/toast/src/ToastContainer.tsx, packages/paste-core/components/toast/src/ToastPortal.tsx, packages/paste-core/components/toast/src/Toaster.tsx, packages/paste-core/components/toast/src/WarningToast.tsx, packages/paste-core/components/toast/src/propTypes.ts, packages/paste-core/components/toast/src/types.ts, packages/paste-core/components/toast/src/useToaster.ts
Fixes https://github.com/twilio-labs/paste/issues/1542
Bug: Toasts never displayed when the system was set to prefers reduced motion
=> fix(toast): toasts now render when prefersReducedMotion is enabled

.changeset/nervous-cougars-roll.md
Adds a changeset for the PR https://github.com/twilio-labs/paste/pull/1557
=> chore: add changeset for toast bug fix

packages/paste-core/components/alert-dialog/src/AlertDialogBody.tsx, packages/paste-core/components/alert-dialog/src/AlertDialogContent.tsx, packages/paste-core/components/alert-dialog/src/AlertDialogFooter.tsx, packages/paste-core/components/alert-dialog/src/AlertDialogHeader.tsx, packages/paste-core/components/alert-dialog/src/index.tsx, packages/paste-core/components/alert-dialog/stories/index.stories.tsx, packages/paste-core/components/modal/src/index.tsx, packages/paste-core/components/modal/stories/index.stories.tsx
- Added extra VRT stories for alert dialog and modal to test the individual parts
- Removed existing alert dialog and modal stories from the Chromatic screenshot flow
=> chore(modal): fix chromatic snapshots

packages/paste-website/src/components/homepage/HomeHero.tsx
=> chore(website): update new banner to point to date picker

.changeset/afraid-ducks-flow.md, cypress/integration/e2e/link-checker/index.spec.ts, packages/paste-core/components/label/package.json, packages/paste-website/package.json, packages/paste-website/src/pages/components/label/index.mdx
=> docs(website): add label package doc page

.changeset/tidy-dragons-tickle.md, packages/paste-core/components/pagination/src/PaginationArrow/PaginationArrowButton.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationArrowIconWrapper.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationBackArrow.tsx, packages/paste-core/components/pagination/src/PaginationArrow/PaginationForwardArrow.tsx, packages/paste-core/components/pagination/src/PaginationArrow/index.tsx, packages/paste-core/components/pagination/src/PaginationNumber.tsx, packages/paste-core/components/pagination/src/types.ts, packages/paste-website/src/pages/components/pagination/index.mdx
=> Pagination style updates

.changeset/dry-singers-play.md, packages/paste-core/components/popover/src/Popover.tsx
-make content padding space-80 for right/left and space-70 for top/bottom
-make x icon size-icon-10
=> chore(popover): increase padding and decrease icon size

.github/labeler.yml, .github/opened-pr-labeler.yml, .github/workflows/opened-pr-labeler.yml, .github/workflows/pr-labeler.yml
When a PR is opened use GitHub actions to automatically label them based on their area
=> chore: set up automatic PR labelling

.changeset/bright-papayas-collect.md, packages/paste-core/components/anchor/__tests__/anchor.test.tsx, packages/paste-core/components/anchor/src/DefaultAnchor.tsx, packages/paste-core/components/anchor/src/InverseAnchor.tsx, packages/paste-core/components/anchor/src/index.tsx, packages/paste-core/components/anchor/src/proptypes.ts, packages/paste-core/components/anchor/src/types.ts, packages/paste-core/components/anchor/stories/index.stories.tsx
Adds element customization to the Anchor component so it works with CustomizationProvider.
=> feat(anchor): add element customization

.changeset/angry-lizards-pump.md, packages/paste-core/components/avatar/__tests__/__snapshots__/avatar.test.tsx.snap, packages/paste-core/components/avatar/__tests__/avatar.test.tsx, packages/paste-core/components/avatar/src/index.tsx, packages/paste-core/components/avatar/src/types.ts, packages/paste-core/components/avatar/stories/index.stories.tsx
=> feat(avatar): add element customization 

.changeset/gorgeous-rivers-relate.md, packages/paste-core/layout/grid/__tests__/__snapshots__/grid.test.tsx.snap, packages/paste-core/layout/grid/__tests__/grid.test.tsx, packages/paste-core/layout/grid/src/Column.tsx, packages/paste-core/layout/grid/src/Grid.tsx, packages/paste-core/layout/grid/src/types.ts, packages/paste-core/layout/grid/stories/index.stories.tsx
- Adds element customization to the Grid and Column components so they work with CustomizationProvider.
- Refactored `Column` to use `Box`.
=> feat(grid): add element customization

.changeset/fuzzy-dragons-stare.md, .changeset/metal-pigs-guess.md, .changeset/olive-points-shave.md, .codesandbox/ci.json, cypress/integration/e2e/link-checker/index.spec.ts, packages/paste-core/components/badge/__tests__/index.spec.tsx, packages/paste-core/components/badge/build.js, packages/paste-core/components/badge/package.json, packages/paste-core/components/badge/src/hooks.tsx, packages/paste-core/components/badge/src/index.tsx, packages/paste-core/components/badge/src/types.ts, packages/paste-core/components/badge/src/utils.ts, packages/paste-core/components/badge/stories/index.stories.tsx, packages/paste-core/components/badge/tsconfig.json, packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/badge.tsx, packages/paste-core/core-bundle/src/index.tsx, packages/paste-core/primitives/box/__tests__/box.test.tsx, packages/paste-core/primitives/box/src/StyleFunctions.ts, packages/paste-core/primitives/box/src/types.ts, packages/paste-style-props/src/proptypes/index.ts, packages/paste-style-props/src/proptypes/space.ts, packages/paste-style-props/src/space.ts, packages/paste-style-props/src/types/space.ts
Please see discussion and review context here in [this closed pull request](https://github.com/twilio-labs/paste/pull/1690).
=> feat(badge): Add Badge component package 

packages/paste-website/src/pages/primitives/box/index.mdx
=> chore(website): add "column-gap" and "row-gap" to Box props table in docs

.changeset/popular-cheetahs-punch.md, packages/paste-core/components/separator/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/separator/__tests__/index.spec.tsx, packages/paste-core/components/separator/src/index.tsx, packages/paste-core/components/separator/stories/index.stories.tsx
=> feat(separator): add element customization

.changeset/lazy-pumas-reflect.md, .changeset/nervous-dingos-unite.md
=> fix: changesets for box and text to include core

.danger/__fixtures__/changeset/heavy-peaches-repeat.md, .danger/__fixtures__/changeset/pink-masks-walk.md, .danger/__fixtures__/changeset/popular-cheetahs-punch.md, .danger/__fixtures__/changeset/pretty-cameras-burn.md, .danger/__tests__/changesets-that-need-core-check.spec.ts, .danger/__tests__/missing-changesets-check.spec.ts, .danger/__tests__/package-json-check.spec.ts, .danger/__tests__/utils.spec.ts, .danger/changesets-that-need-core-check.ts, .danger/missing-changesets-check.ts, .danger/package-json-check.ts, .danger/types.ts, .danger/utils.ts, .eslintrc.js, .github/workflows/pull_request.yml, CONTRIBUTING.md, README.md, STANDARD_OPERATING_PROCEDURES.md, dangerfile.ts, package.json, tsconfig.json, yarn.lock
=> chore: add DangerJS to CI workflow

.changeset/moody-elephants-deliver.md, packages/paste-core/components/help-text/__tests__/helptext.test.tsx, packages/paste-core/components/help-text/package.json, packages/paste-core/components/help-text/src/HelpText.tsx, packages/paste-core/components/help-text/stories/input.stories.tsx, packages/paste-core/components/input/__tests__/input.test.tsx
- Enable customization for help text
- Add tests for html attribute and customization
- Add customization story
=> feat(help text): add customization

.changeset/clean-lemons-joke.md, packages/paste-core/components/tooltip/__test__/index.spec.tsx, packages/paste-core/components/tooltip/src/TooltipArrow.tsx, packages/paste-core/components/tooltip/src/index.tsx, packages/paste-core/components/tooltip/stories/index.stories.tsx
=> feat(tooltip): add element customization

.changeset/olive-lamps-sort.md, .changeset/stupid-icons-remember.md, packages/paste-core/components/alert/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-core/components/base-radio-checkbox/__tests__/base-radio-checkbox.test.tsx, packages/paste-core/components/base-radio-checkbox/src/BaseRadioCheckbox.tsx, packages/paste-core/components/button/__tests__/button.test.tsx, packages/paste-core/components/button/__tests__/customization.test.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/proptypes.ts, packages/paste-core/components/button/src/types.ts, packages/paste-core/components/button/stories/customization.stories.tsx
=> feat(button, base-radio-checkbox): add element customization

.changeset/empty-spiders-rest.md, .changeset/five-lobsters-juggle.md, .changeset/wicked-cups-rule.md, packages/paste-core/components/combobox/src/Combobox.tsx, packages/paste-core/components/input-box/__tests__/input-chevron-wrapper.test.tsx, packages/paste-core/components/input-box/src/InputChevronWrapper.tsx, packages/paste-core/components/select/__tests__/option.test.tsx, packages/paste-core/components/select/__tests__/optiongroup.test.tsx, packages/paste-core/components/select/__tests__/select.test.tsx, packages/paste-core/components/select/src/Option.tsx, packages/paste-core/components/select/src/OptionGroup.tsx, packages/paste-core/components/select/src/Select.tsx, packages/paste-core/components/select/src/types.ts, packages/paste-core/components/select/stories/select.stories.tsx
=> feat(select):  add element customization

.changeset/nasty-olives-burn.md, packages/paste-core/components/spinner/__tests__/index.test.tsx, packages/paste-core/components/spinner/src/index.tsx, packages/paste-core/components/spinner/stories/index.stories.tsx
=> chore(spinner): add element customization

.changeset/tame-dingos-exercise.md, packages/paste-core/components/breadcrumb/__tests__/breadcrumb.spec.tsx, packages/paste-core/components/breadcrumb/src/index.tsx, packages/paste-core/components/breadcrumb/stories/index.stories.tsx
=> feat(breadcrumb): add element customization

.changeset/angry-lemons-fetch.md, packages/paste-core/components/combobox/__tests__/customization.spec.tsx, packages/paste-core/components/combobox/src/Combobox.tsx, packages/paste-core/components/combobox/src/ComboboxItems.tsx, packages/paste-core/components/combobox/src/styles/ComboboxListbox.tsx, packages/paste-core/components/combobox/src/styles/ComboboxListboxGroup.tsx, packages/paste-core/components/combobox/src/styles/ComboboxListboxOption.tsx, packages/paste-core/components/combobox/src/types.ts, packages/paste-core/components/combobox/stories/customization.stories.tsx
=> feat(combobox): add element customization

netlify.toml, packages/paste-website/netlify.toml, packages/paste-website/src/components/homepage/GetStartedRunning.tsx, packages/paste-website/src/components/icons-list/IconCard.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/components/site-wrapper/site-footer/SiteFooterNav.tsx, packages/paste-website/src/pages/getting-started/engineering/index.mdx, packages/paste-website/src/pages/getting-started/manual-installation/index.mdx, packages/paste-website/src/pages/getting-started/quickstart/index.mdx, packages/paste-website/src/pages/icons/index.mdx
Separates out the Quick Start and Manual Installation content onto their own pages.
=> docs(website): Breaking up the Engineering Guidelines page

packages/paste-core/core-bundle/package.json, packages/paste-website/src/components/component-overview-table/index.tsx, packages/paste-website/src/components/component-status/PeerReviewStatus.tsx, packages/paste-website/src/components/shortcodes/component-header/index.tsx, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/constants.ts, packages/paste-website/src/pages/core/changelog.mdx, packages/paste-website/src/pages/core/index.mdx, packages/paste-website/src/pages/core/upgrade-guide.mdx
Created a docs page for Core and an Upgrade Guide for people to easily see differences between core versions.
=> chore(website): add docs page for Core and an Upgrade Guide

.changeset/four-dolphins-argue.md, packages/paste-core/components/button/src/index.tsx, packages/paste-website/src/components/shortcodes/feedback-popover/index.tsx, packages/paste-website/stories/feedback-popover.stories.tsx
Add `alignItems="center"` to Button children wrapper and add Feedback Popover stories for VRT
=> fix(button): center children for alignment

packages/paste-website/src/components/Roadmap/RoadmapAside.tsx, packages/paste-website/src/components/shortcodes/PageAside.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/TableOfContentsAnchor.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/TableOfContentsList.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/TableOfContentsListItem.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/index.tsx, packages/paste-website/src/components/shortcodes/table-of-contents/styles.ts, packages/paste-website/src/components/shortcodes/table-of-contents/types.ts, packages/paste-website/src/constants.ts, packages/paste-website/stories/table-of-contents.stories.tsx
Updates the TableOfContents component to the latest designs. Separates out the sub-components into their own files.
=> feat(website): Update TableOfContents styles

cypress/integration/e2e/layout/aspect-ratio.spec.ts, cypress/integration/e2e/layout/flex.spec.ts, cypress/integration/e2e/layout/grid.spec.ts, cypress/integration/e2e/layout/media-object.spec.ts, cypress/integration/e2e/layout/stack.spec.ts, cypress/integration/e2e/patterns/button-vs-anchor.spec.ts, cypress/integration/e2e/patterns/contribute.spec.ts, cypress/integration/e2e/patterns/create.spec.ts, cypress/integration/e2e/patterns/data-export.spec.ts, cypress/integration/e2e/patterns/delete.spec.ts, cypress/integration/e2e/patterns/empty-states.spec.ts, cypress/integration/e2e/patterns/notifications-and-feedback.spec.ts, cypress/integration/e2e/patterns/object-details.spec.ts, cypress/integration/e2e/patterns/status.spec.ts, cypress/integration/e2e/primitives/box.spec.ts, cypress/integration/e2e/primitives/combobox-primitive.spec.ts, cypress/integration/e2e/primitives/disclosure-primitive.spec.ts, cypress/integration/e2e/primitives/menu-primitive.spec.ts, cypress/integration/e2e/primitives/modal-dialog-primitive.spec.ts, cypress/integration/e2e/primitives/non-modal-dialog-primitive.spec.ts, cypress/integration/e2e/primitives/tabs-primitive.spec.ts, cypress/integration/e2e/primitives/text.spec.ts, cypress/integration/e2e/primitives/tooltip-primitive.spec.ts, tools/utils/cypress-test-generators/TEMPLATE.js, tools/utils/cypress-test-generators/createCypressTestSpec.js
=> chore(website): use template to add baseline tests for patterns, layout components, and primitives

package.json
=> fix(package.json): tsc echo message should be wrapped in quotes

packages/paste-website/src/components/callout/index.tsx, packages/paste-website/src/pages/components/button/index.mdx, packages/paste-website/src/pages/components/combobox/index.mdx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/components/input/index.mdx, packages/paste-website/src/pages/components/select/index.mdx, packages/paste-website/src/pages/components/textarea/index.mdx, packages/paste-website/src/pages/layout/index.mdx, packages/paste-website/src/pages/libraries/uid-library/index.mdx, packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx, packages/paste-website/src/pages/patterns/create/index.mdx, packages/paste-website/src/pages/patterns/index.mdx, packages/paste-website/src/pages/patterns/notifications-and-feedback/index.mdx, packages/paste-website/src/pages/patterns/object-details/index.mdx, packages/paste-website/src/pages/patterns/status/index.mdx, packages/paste-website/src/pages/primitives/combobox-primitive/index.mdx, packages/paste-website/src/pages/primitives/index.mdx, packages/paste-website/src/pages/primitives/text/index.mdx, packages/paste-website/stories/callout.stories.tsx
* Updates visual appearance
* Cleans up variant naming
=> feat(callout-update): update callout component UI

packages/paste-website/src/components/Typography.tsx, packages/paste-website/src/pages/core/upgrade-guide.mdx, packages/paste-website/stories/inline-code.stories.tsx
Update styles of inline code for mdx ([ticket](https://issues.corp.twilio.com/browse/DSYS-3128))
=> chore(website): update inline code design

packages/paste-website/src/components/codeblock/index.tsx, packages/paste-website/src/components/paste-mdx-provider/index.tsx, packages/paste-website/src/components/shortcodes/ArticleLayouts.tsx, packages/paste-website/src/components/shortcodes/PageAside.tsx, packages/paste-website/src/layouts/DefaultLayout.tsx, packages/paste-website/src/pages/articles/2021-07-26-pastes-path-to-a-transparent-package-categorization-system.mdx, packages/paste-website/src/pages/articles/index.mdx, packages/paste-website/src/pages/components/index.mdx, packages/paste-website/src/pages/layout/index.mdx, packages/paste-website/src/pages/primitives/index.mdx
* Updates spacing and sizing properties on the docs site to match updated comps.
=> feat(spacing-update): update spacing for site docs

packages/paste-website/gatsby-config.js, packages/paste-website/src/pages/roadmap/index.mdx
* Updates Airtable name for BPM table in Gatsby config
=> fix(airtable-update): update gastby refs to match updated airtable

packages/paste-website/src/component-examples/DatePickerExamples.ts, packages/paste-website/src/components/Roadmap/Roadmap.tsx, packages/paste-website/src/pages/components/date-picker/index.mdx, packages/paste-website/src/pages/components/time-picker/index.mdx
[ticket](https://issues.corp.twilio.com/browse/DSYS-3163)
=> chore: update roadmap table to use status pattern

packages/paste-design-tokens/tokens/global/background-color.yml
=> docs(token list): updating background color token descriptions

packages/paste-website/src/pages/components/heading/index.mdx
=> website(heading): add do/dont about case

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/introduction/contributing/components/index.mdx, packages/paste-website/src/pages/introduction/contributing/patterns/index.mdx
Added the content of [this doc](https://docs.google.com/document/d/1VQ5jXG-csE8_sfZ89V3lcazfDDfn-MpJ7QifdcbC93w/edit#heading=h.asc84qarao0u) to the docs site based on [this ticket](https://issues.corp.twilio.com/browse/DSYS-2970).
=> feat: add component contribution page

packages/paste-website/src/component-examples/PrivacyPatternExamples.tsx, packages/paste-website/src/pages/patterns/privacy/index.mdx
Add the Privacy Pattern page to the docs site based on [this ticket](https://issues.corp.twilio.com/browse/DSYS-2996).
=> feat: add privacy pattern page

packages/paste-website/src/components/homepage/HomeHero.tsx
Update the New banner for roles we are currently hiring for.
=> docs(website): update the New banner

.changeset/lucky-lies-travel.md, packages/paste-core/components/button/src/ResetButton.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/styles.ts
* Updates default size prop for Link buttons to 'default' from 'reset', to ensure proper font & line height sizing.
=> fix(link-button): updates default style for link buttons

.changeset/nervous-clouds-suffer.md, packages/paste-core/components/popover/__tests__/index.spec.tsx, packages/paste-core/components/popover/src/Popover.tsx, packages/paste-core/components/popover/stories/index.stories.tsx, packages/paste-website/src/component-examples/PopoverExamples.ts, packages/paste-website/src/pages/components/popover/index.mdx
=> feat(popover): add i18nDismissLabel prop

packages/paste-website/src/pages/customization/creating-a-custom-theme.mdx
Fixes a bug found by @sang-yeo in #2241 
=> fix: update theme designer link

packages/paste-website/src/pages/patterns/empty-state/index.mdx
=> chore(website): rename empty state pattern

packages/paste-libraries/data-visualization/stories/index.stories.tsx
* Adds Chromatic Delay for Data Visualization stories, to allow them to animate in before taking a snapshot
* Should resolve false positive VRT diffs with Data Viz stories in Chromatic
=> chore(chromatic): add chromatic delay to data-viz to allow load

packages/paste-website/src/pages/components/table/index.mdx
Updates Table docs page with information about Data Grid now that it's released.
=> chore(website): update table docs with data grid info

.changeset/neat-apples-boil.md, packages/paste-core/components/anchor/__tests__/anchor.test.tsx, packages/paste-core/components/anchor/src/index.tsx, packages/paste-core/components/anchor/src/proptypes.ts, packages/paste-core/components/anchor/src/types.ts, packages/paste-core/components/anchor/stories/index.stories.tsx, packages/paste-website/src/pages/components/anchor/index.mdx
=> feat(anchor): add i18n prop

.changeset/fluffy-toes-look.md, .changeset/weak-dots-pump.md, .codesandbox/ci.json, packages/paste-codemods/tools/.cache/mappings.json, packages/paste-core/components/chat-log/__tests__/customization.spec.tsx, packages/paste-core/components/chat-log/__tests__/index.spec.tsx, packages/paste-core/components/chat-log/build.js, packages/paste-core/components/chat-log/package.json, packages/paste-core/components/chat-log/src/ChatBubble.tsx, packages/paste-core/components/chat-log/src/ChatMessage.tsx, packages/paste-core/components/chat-log/src/index.tsx, packages/paste-core/components/chat-log/src/styles.ts, packages/paste-core/components/chat-log/src/types.ts, packages/paste-core/components/chat-log/stories/index.stories.tsx, packages/paste-core/components/chat-log/tsconfig.json, packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/chat-log.tsx, packages/paste-core/core-bundle/src/index.tsx, packages/paste-website/src/utils/componentFilters.ts, yarn.lock
=> feat: add ChatMessage and ChatBubble components

.changeset/soft-hats-move.md, packages/paste-core/primitives/menu/__tests__/__snapshots__/index.spec.tsx.snap, packages/paste-libraries/reakit/package.json, yarn.lock
Updates Reakit to fix this issue https://github.com/twilio-labs/paste/discussions/2336
=> chore(reakit-library): update reakit dependency version

cypress/integration/token-list/index.spec.ts, packages/paste-website/src/__tests__/tokensList.test.tsx, packages/paste-website/src/components/tokens-list/helpers.tsx, packages/paste-website/src/components/tokens-list/index.tsx, packages/paste-website/src/components/tokens-list/types.ts, packages/paste-website/src/utils/RouteUtils.ts
=> fix(website): fix buggy tokens list filter

.changeset/clever-needles-count.md
In our haste, we committed an incomplete changeset entry
=> chore: update hasty changeset description

packages/paste-website/src/pages/components/alert/index.mdx, packages/paste-website/src/pages/components/flex/index.mdx, packages/paste-website/src/pages/components/heading/index.mdx, packages/paste-website/src/pages/components/input/index.mdx, packages/paste-website/src/pages/components/spinner/index.mdx, packages/paste-website/src/pages/components/textarea/index.mdx
Fix the broken links on the following docs website pages:
=> fix(alert): fix storybook links on docsite

packages/paste-website/src/pages/components/flex/index.mdx
Quick PR to fix a bug on our Flex docs that someone filed on Issues (#2432)
=> fix(docs): update to valid flex basis value

.changeset/curly-onions-tie.md, .changeset/many-timers-kneel.md, .eslintrc.js, .gitignore, package.json, packages/paste-libraries/styling/package.json, packages/paste-website/package.json, packages/paste-website/src/components/ThemeObjectDisplay.tsx, packages/paste-website/src/components/tokens-list/helpers.tsx, packages/paste-website/tsconfig.json, tsconfig.json, turbo.json, yarn.lock
=> patch: fix emotion type build error 

internal-docs/engineering/runbooks/firehydrant.md, internal-docs/team/working-agreements.md
Add notes about Firehydrant and helper duty to our internal team documentation.
=> chore(internal-docs): add some notes on firehydrant and helper duty

netlify.toml, packages/paste-website/netlify.toml
=> chore: follow upgrade guide for gatsby netlify plugin

packages/paste-website/src/components/tokens-list/index.tsx, packages/paste-website/src/components/tokens-list/sectionIntros.tsx, packages/paste-website/stories/tokenSectionIntros.stories.tsx
* Adds Category Intro components for the new tokens page
* Adds Stories
=> feat(tokens-page): category intros

packages/paste-core/layout/aspect-ratio/__tests__/aspectRatio.spec.tsx
[Jira ticket.](https://issues.corp.twilio.com/browse/DSYS-3381)
Adds a unit test for the `handlePropValidation` function.
=> test(aspect-ratio): handlePropValidation

packages/paste-website/src/__tests__/tokenCard.test.tsx, packages/paste-website/src/components/tokens-list/index.tsx, packages/paste-website/src/components/tokens-list/token-card/index.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/BoxExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/IconSizeExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/LineHeightExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/SpacingExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/TextColorExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/TextExample.tsx, packages/paste-website/src/components/tokens-list/token-card/token-example/index.tsx, packages/paste-website/stories/TokenCard.stories.tsx
* Feature Branch Merge to website/new-tokens-page
* Adds support for inverse background colors on Token Previews for inverse tokens
* Adds test and stories
=> Tokens Page: Inverse Token Previews

packages/paste-website/src/component-examples/ChatLogExamples.ts, packages/paste-website/src/pages/components/alert/index.mdx, packages/paste-website/src/pages/components/chat-log/index.mdx, packages/paste-website/src/utils/componentFilters.ts
* add a new ChatLog docs page and examples
* update the sidebar filter so ChatLog is no longer removed from the sidebar
=> feat(website): add ChatLog docs page

cypress/integration/sitemap-vrt/constants.ts, packages/paste-website/src/pages/components/chat-log/index.mdx
=> docs(chat-log): fix componentHeaderName

.changeset/plenty-dingos-reflect.md, packages/paste-core/components/select/src/Select.tsx
=> fix(select): disabled background color

.danger/__fixtures__/changeset/tiny-robot-hands.md, .danger/__tests__/major-core-missing-upgrade-guide.spec.ts, .danger/major-core-missing-upgrade-guide.ts, packages/paste-website/src/pages/core/upgrade-guide.mdx
- docs: update the Paste Core upgrade guide with new major versions
- chore: danger check to ensure major upgrades have upgrade guides
=> chore: Paste Core upgrade guide update

.changeset/wild-weeks-agree.md, packages/paste-core/components/callout/package.json
Literally just changes the status in package.json, I edited the changeset so I wouldn't have to make a new one.
=> chore(callout): fix status in package.json

packages/paste-website/src/components/homepage/HomeHero.tsx
* Update docs site homepage callout to promote new tokens list page
=> chore: update docs site homepage New callout

packages/paste-core/components/combobox/src/styles/ComboboxListboxGroup.tsx, packages/paste-core/components/combobox/src/styles/ComboboxListboxOption.tsx
* Improved padding for group and item listboxes
* Improved selected and highlighted treatment for item listboxes
* Improved group listbox styling
=> chore: fix up styles for multiselect combobox

package.json
This PR aims to fix the tests failing
=> fix: react 16 tests failing

.changeset/shy-hotels-notice.md, .codesandbox/ci.json, packages/paste-codemods/tools/.cache/mappings.json, packages/paste-core/components/button-group/__tests__/index.spec.tsx, packages/paste-core/components/button-group/build.js, packages/paste-core/components/button-group/package.json, packages/paste-core/components/button-group/src/ButtonGroup.tsx, packages/paste-core/components/button-group/src/index.tsx, packages/paste-core/components/button-group/stories/index.stories.tsx, packages/paste-core/components/button-group/tsconfig.json, packages/paste-core/core-bundle/.gitignore, packages/paste-core/core-bundle/package.json, packages/paste-core/core-bundle/src/button-group.tsx, packages/paste-core/core-bundle/src/index.tsx, yarn.lock
A new branch [from the original PR here](https://github.com/twilio-labs/paste/pull/2675)
=> feat: add ButtonGroup component

packages/paste-core/components/button-group/stories/index.stories.tsx
Button group package is missing a story for toggle buttons. Here it is.
=> chore(button-group): add toggle button story

.changeset/cold-turkeys-stare.md, packages/paste-codemods/tools/.cache/mappings.json, packages/paste-core/components/button/package.json, packages/paste-core/components/button/src/SecondaryButton.tsx, packages/paste-core/components/button/src/index.tsx, packages/paste-core/components/button/src/styles.ts, packages/paste-core/components/radio-button-group/src/StyledRadioButtonLabel.tsx, yarn.lock
- fix(button): export ToggleButtonStyles from index correctly
- fix(radio-button-group): import ToggleButtonStyles from compiled package source
=> fix: radio button style import

cypress/integration/sitemap-vrt/constants.ts, packages/paste-core/components/avatar/package.json, packages/paste-website/src/component-examples/RadioButtonGroupExamples.ts, packages/paste-website/src/pages/components/avatar/index.mdx, packages/paste-website/src/pages/components/file-picker/index.mdx, packages/paste-website/src/pages/components/radio-button-group/index.mdx
Docs page for radio button group.
=> docs: radio button group

packages/paste-website/src/pages/blog/2022-10-18-danger-js-helping-paste-focus-on-paste.mdx
- Add new link to Twilio Blog post about Danger JS
=> chore(website): add dangerJS blog post to blog

packages/paste-website/src/pages/foundations/content/word-list/index.mdx
=> fix: bad copy paste page description

packages/paste-libraries/animation/package.json, yarn.lock
=> [AIONAPFMWK-170] Upgrade react spring

packages/paste-core/components/data-grid/src/utils/cell-management.ts, packages/paste-core/components/tooltip/__test__/index.spec.tsx, packages/paste-libraries/uid/src/index.tsx
=> fix: React 18 useUIDSeed and related tests

packages/paste-core/components/label/stories/label.stories.tsx, packages/paste-core/components/textarea/stories/textarea.stories.tsx
#2915 error see wrong removal here https://github.com/twilio-labs/paste/pull/2915/files#diff-9a811cabee647cf8f18e5bdeb453a554685233a0cd119dc3d0da5f4db121c574
=> fix: Missing imports

cypress/integration/sitemap-vrt/constants.ts, packages/paste-website/src/component-examples/FormExamples.ts, packages/paste-website/src/pages/components/form/index.mdx
=> docs: add Form component documentation page

.changeset/fast-kiwis-repair.md, packages/paste-core/components/form/package.json, packages/paste-core/core-bundle/package.json, yarn.lock
=> fix: released v1.0.0 of Form package when it should have been 8.0.0

.changeset/metal-mayflies-thank.md, .changeset/wicked-bananas-provide.md, packages/paste-libraries/styling/package.json, packages/paste-libraries/styling/src/index.tsx, packages/paste-theme/src/themeProvider.tsx, yarn.lock
Adds the ability to leverage emotion's CacheProvider with Paste, so a nonce can be set to get around CSP issues. https://emotion.sh/docs/@emotion/cache#nonce
=> feat(theme): ability to leverage emotion CacheProvider

packages/paste-website/src/components/homepage/HomeHero.tsx, packages/paste-website/src/pages/foundations/spacing-and-layout/index.mdx
**AC:**
- Add reference heading with this link: https://uxdesign.cc/ui-cheat-sheet-spacing-friendships-e37a6fccc407 should live At the very bottom of the page. "Reference: [Insert link]"
- Update  “related components” to be a heading
- Update new banner to promote spacing and layout guidelines
=> chore: update foundations page

packages/paste-website/src/components/images/EmptyStateImages.tsx, packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx, packages/paste-website/src/pages/patterns/create/index.mdx, packages/paste-website/src/pages/patterns/data-export/index.mdx, packages/paste-website/src/pages/patterns/delete/index.mdx, packages/paste-website/src/pages/patterns/empty-state/index.mdx, packages/paste-website/src/pages/patterns/filter-group/index.mdx, packages/paste-website/src/pages/patterns/notifications-and-feedback/index.mdx, packages/paste-website/src/pages/patterns/object-details/index.mdx, packages/paste-website/src/pages/patterns/privacy/index.mdx, packages/paste-website/src/pages/patterns/status/index.mdx
Updates all patterns pages to next js format.
=> chore: update pattern pages to nextjs

packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/foundations/colors/index.mdx, packages/paste-website/src/pages/foundations/content/content-checklist/index.mdx, packages/paste-website/src/pages/foundations/content/index.mdx, packages/paste-website/src/pages/foundations/content/product-style-guide/index.mdx, packages/paste-website/src/pages/foundations/content/voice-and-tone/index.mdx, packages/paste-website/src/pages/foundations/content/word-list/index.mdx, packages/paste-website/src/pages/foundations/data-visualization/index.mdx, packages/paste-website/src/pages/foundations/illustrations/index.mdx, packages/paste-website/src/pages/foundations/localization/index.mdx, packages/paste-website/src/pages/foundations/spacing-and-layout/index.mdx
^^ 
also adds the content overview page to the sidebar, because it was missing before apparently 🤷🏽 
=> chore: update foundations pages for nextjs

packages/paste-core/components/combobox/stories/Combobox.stories.tsx, packages/paste-core/components/input/stories/input.stories.tsx, packages/paste-core/components/select/stories/select.stories.tsx, packages/paste-core/components/textarea/stories/textarea.stories.tsx
- Updated implementation of preffix/suffix to increase color contrast
=> chore(input-box): fix disabled preffix/suffix

.changeset/nasty-files-notice.md, .changeset/wise-jars-do.md, packages/paste-core/components/callout/src/Callout.tsx, packages/paste-core/components/callout/src/CalloutHeading.tsx, packages/paste-core/components/heading/__tests__/heading.test.tsx, packages/paste-core/components/heading/src/index.tsx
=> chore(heading, callout): update styles for one twilio

.changeset/strange-trees-kiss.md, packages/paste-core/components/data-grid/stories/components/CustomizableDataGrid.tsx, packages/paste-core/components/table/src/TBody.tsx, packages/paste-core/components/table/src/TFoot.tsx, packages/paste-core/components/table/src/THead.tsx, packages/paste-core/components/table/src/Td.tsx, packages/paste-core/components/table/src/Th.tsx, packages/paste-core/components/table/stories/index.stories.tsx
=> Update table component

.changeset/cuddly-terms-grab.md, .changeset/funny-buckets-repair.md, packages/paste-core/components/breadcrumb/src/index.tsx, packages/paste-core/components/separator/src/index.tsx, packages/paste-website/src/pages/components/breadcrumb/index.mdx
- Style update for Separator
- Style updates for Breadcrumb package
=> chore(separator, breadcrumb): update styles

.changeset/witty-avocados-play.md, packages/paste-core/components/popover/__tests__/index.spec.tsx, packages/paste-core/components/popover/package.json, packages/paste-core/components/popover/src/Popover.tsx, packages/paste-core/components/popover/stories/index.stories.tsx, packages/paste-website/src/component-examples/PopoverExamples.ts, packages/paste-website/src/pages/components/popover/index.mdx
- updates styles to new One Twilio design language
- updates documentation
- add new props: initialFocusRef, width
- add tests for new props
=> feat: Update Popover to stage 2

.github/DISCUSSION_TEMPLATE/office-hours.yml, .github/DISCUSSION_TEMPLATE/request-icon.yml
The GH Discussion templates aren't working. I don't think there's any way to test the fix without merging the PR to see unfortunately
=> chore: fix OH discussion template

.github/workflows/on_pull_request.yml, package.json, yarn.lock
Test out [sharding](https://github.com/storybookjs/test-runner/pull/243) for Storybook test-runner.
=> ci: use sharding for test-runner

.changeset/tidy-tigers-marry.md
Changeset that was missing in #3051
=> fix: evergreen theme background overlay color

.changeset/wicked-dancers-exercise.md, .changeset/witty-papayas-move.md, packages/paste-core/components/display-heading/src/index.tsx, packages/paste-core/components/inline-code/src/index.tsx, packages/paste-core/components/inline-code/stories/index.stories.tsx, packages/paste-website/src/pages/components/inline-code/index.mdx
^ updates styles, add example of new minimal inline code variant on the docs page
=> feat: update inline code and display heading components

.changeset/lemon-rice-wave.md, packages/paste-core/components/minimizable-dialog/src/MinimizableDialog.tsx, packages/paste-core/components/minimizable-dialog/src/MinimizableDialogContainer.tsx, packages/paste-core/components/minimizable-dialog/src/MinimizableDialogContent.tsx, packages/paste-core/components/minimizable-dialog/src/MinimizableDialogContext.tsx, packages/paste-core/components/minimizable-dialog/src/MinimizableDialogHeader.tsx, packages/paste-core/components/minimizable-dialog/src/StyledMinimizableDialog.tsx, packages/paste-core/components/minimizable-dialog/stories/index.stories.tsx, packages/paste-website/src/component-examples/MinimizableDialogExamples.ts
=> feat: Minimizable Dialog updates

.changeset/silver-horses-reply.md, packages/paste-core/components/data-grid/src/table/Td.tsx, packages/paste-core/components/data-grid/src/table/Th.tsx, packages/paste-core/components/data-grid/src/table/Tr.tsx, packages/paste-core/components/data-grid/stories/components/SelectableRowsDataGrid.tsx, packages/paste-core/components/data-grid/stories/components/StickyHeaderDataGrid.tsx
Updates to the DataGrid to follow Table styles where we have some custom implementations of Table elements inside DataGrid.
=> feat(data-grid): update styles to align with new Paste Twilio theme

.changeset/eleven-donkeys-flash.md, packages/paste-core/components/combobox/src/singleselect/Combobox.tsx
Resolves https://github.com/twilio-labs/paste/issues/3128 and https://github.com/twilio-labs/paste/issues/3097
=> fix(combobox): correct dropdown position on scroll

.changeset/sharp-readers-hammer.md, packages/paste-core/components/combobox/__tests__/MultiselectCombobox.spec.tsx, packages/paste-core/components/combobox/src/multiselect/GrowingInput.tsx, packages/paste-core/components/combobox/src/multiselect/MultiselectCombobox.tsx
Resolves https://github.com/twilio-labs/paste/discussions/2994
=> fix(combobox): multiselect combobox now clears input value on select

apps/vs-code-intellisense/package.json, apps/vs-code-intellisense/src/extension.ts, apps/vs-code-intellisense/src/test/runTest.ts, apps/vs-code-intellisense/src/test/suite/utils/is-color-category.test.ts, apps/vs-code-intellisense/src/utils/get-color-preview.ts, apps/vs-code-intellisense/src/utils/index.ts, apps/vs-code-intellisense/src/utils/is-color-category.ts, yarn.lock
Taking over from https://github.com/twilio-labs/paste/pull/3150 just to run the full CI suite.
=> feat: add preview for color tokens

packages/paste-website/src/pages/components/tabs/index.mdx
Update tabs docs to use [the updated spec doc](https://docs.google.com/document/d/1lyOh-KMLiNH13YddY04qqhXn20pNCs47LPoluldJv78/edit#)
=> docs: update tabs spec

internal-docs/process/epic-template.md
=> feat(internal docs): revise peer review steps in epic template

apps/vs-code-intellisense/package.json
The release is done, this is just committing the output of that release.
=> chore: release vs code extension

packages/paste-core/primitives/listbox/src/ListboxPrimitiveItem.tsx, packages/paste-core/primitives/listbox/stories/index.stories.tsx, packages/paste-libraries/reakit/stories/composite.stories.tsx, packages/paste-website/src/component-examples/ListboxPrimitiveExamples.ts
We were having some confusion around how to use listbox-primitive, so I went through and fixed a broken example on the website and added more/fixes to the stories.
=> docs(listbox-primitive): add stories

.changeset/loud-berries-count.md, cypress/integration/sitemap-vrt/constants.ts, packages/paste-core/components/sidebar/src/navigation/SidebarNavigationItem.tsx, packages/paste-core/components/sidebar/src/navigation/styles.tsx, packages/paste-core/components/sidebar/stories/full-composition/console.stories.tsx, packages/paste-core/components/sidebar/stories/full-composition/flex.stories.tsx, packages/paste-core/components/sidebar/stories/navigation.stories.tsx, packages/paste-website/src/component-examples/SidebarNavigationExamples.ts, packages/paste-website/src/components/site-wrapper/sidebar/SidebarNavigation.tsx, packages/paste-website/src/pages/components/screen-reader-only/index.mdx, packages/paste-website/src/pages/components/sidebar-navigation/index.mdx
Add some docs for the navigation.
Make it easier to put a beta badge in a navigation item by controlling the layout for the consumer.
=> docs: creating the sidebar navigation docs

.changeset/cool-eyes-bow.md, packages/paste-core/components/list/__tests__/index.spec.tsx, packages/paste-core/primitives/text/src/CustomStyleProps.ts
Address https://github.com/twilio-labs/paste/discussions/3318 which should finally address https://github.com/twilio-labs/paste/issues/2954 because https://github.com/twilio-labs/paste/pull/2966 never actually worked.
Also write a test to prove it works and stays working.
=> fix: list style type

packages/paste-website/src/pages/components/input/index.mdx
Add i18n props to props table, add Internationalization section and example, remove outdated Anatomy section
=> docs(input): add missing number input docs

packages/paste-website/src/pages/components/aspect-ratio/index.mdx
https://deploy-preview-3340--paste-docs.netlify.app/components/aspect-ratio
=> fix(website): replace unavailable video in Aspect Ratio

packages/paste-website/src/pages/components/modal/index.mdx
Made minor changes to the documentation to account for broader error message content strategy
=> Modal error updates.mdx

.changeset/cool-yaks-destroy.md, packages/paste-libraries/react-spectrum/src/react-aria.tsx
Export the useProgressBar hook for use in our upcoming ProgressBar component
=> feat(react-spectrum): export useProgressBar and useMeter hooks

.changeset/giant-teachers-turn.md, packages/paste-theme-designer/components/token-option/UnitTokenInput.tsx, packages/paste-theme/src/types/GenericThemeShape.ts
Fixes #3239 
Also fixes a bug on Remix.
=> chore(theme): fix sizeIcon type

.changeset/lucky-colts-grow.md, packages/paste-core/components/combobox/src/ListboxPositioner.tsx, packages/paste-core/components/combobox/src/multiselect/MultiselectCombobox.tsx, packages/paste-core/components/combobox/src/singleselect/Combobox.tsx, packages/paste-core/components/combobox/stories/Combobox.stories.tsx, packages/paste-core/components/combobox/stories/MultiselectCombobox.stories.tsx, packages/paste-core/components/sidebar/stories/full-composition/components/Console.tsx, packages/paste-core/components/sidebar/stories/full-composition/components/Flex.tsx, packages/paste-core/components/sidebar/stories/full-composition/components/Segment.tsx, packages/paste-core/components/sidebar/stories/full-composition/docs.stories.tsx
Should resolve https://github.com/twilio-labs/paste/discussions/3448
=> chore(combobox): fix positioning

.changeset/curly-cameras-arrive.md, packages/paste-core/components/slider/src/Slider.tsx, packages/paste-website/src/pages/components/meter/index.mdx
Meter, Progress Bar, and Slider designs are all aligned.
=> chore(slider): move min and max value labels below slider track

internal-docs/engineering/ci.md, packages/paste-website/src/components/customization-landing-page/ReactCard.tsx, packages/paste-website/src/pages/introduction/for-engineers/quickstart/index.mdx
We removed the template and start kit as CRA is deprecated.
=> chore: remove mention of create react app

.changeset/little-llamas-swim.md, packages/paste-core/primitives/non-modal-dialog/__tests__/NonModalDialogPrimitive.tsx, packages/paste-core/primitives/non-modal-dialog/src/index.tsx
Fix to always use portal, even when using state hooks
=> fix(non-modal-dialog-primitive): always use portal

.github/workflows/update_docs_embed.yml
=> fix: embedding openai secret for CI

.github/workflows/on_discussion_create.yml
=> fix: discussions secrets

packages/paste-website/src/pages/api/ai.ts, tools/github/autoresponder.ts
Reverts twilio-labs/paste#3568
=> Revert "chore: improve github autoresponder"

.changeset/ninety-masks-report.md, packages/paste-core/components/topbar/src/Topbar.tsx, packages/paste-core/components/topbar/src/TopbarActions.tsx, packages/paste-core/components/topbar/stories/topbar.stories.tsx, packages/paste-core/components/topbar/type-docs.json
=> chore(topbar): add justify center to topbar actions

.changeset/curvy-eels-tie.md, packages/paste-customization/__tests__/CustomizationProvider.test.tsx, packages/paste-customization/stories/customization.stories.tsx
=> chore: fix customization tests

.changeset/hip-colts-invite.md, packages/paste-core/components/form/src/FormSectionDescription.tsx, packages/paste-website/src/component-examples/page-templates/SettingsExamples.ts, packages/paste-website/src/component-examples/page-templates/WizardExamples.ts, packages/paste-website/src/components/ingredients/WizardIngredients.tsx, packages/paste-website/src/pages/page-templates/wizard/index.mdx, packages/paste-website/stories/PageTemplates.stories.tsx
=> chore: add wizard page template docs

.changeset/quiet-dodos-act.md, .changeset/quiet-dodos-act1.md, .changeset/quiet-dodos-act2.md, .changeset/quiet-dodos-act3.md, .changeset/quiet-dodos-act4.md, .changeset/quiet-dodos-act5.md, .changeset/quiet-dodos-act6.md, .changeset/quiet-dodos-act7.md, .changeset/thick-lamps-knock.md, .changeset/thick-lamps-knock1.md, .changeset/thick-lamps-knock10.md, .changeset/thick-lamps-knock11.md, .changeset/thick-lamps-knock12.md, .changeset/thick-lamps-knock13.md, .changeset/thick-lamps-knock14.md, .changeset/thick-lamps-knock15.md, .changeset/thick-lamps-knock16.md, .changeset/thick-lamps-knock17.md, .changeset/thick-lamps-knock2.md, .changeset/thick-lamps-knock3.md, .changeset/thick-lamps-knock4.md, .changeset/thick-lamps-knock5.md, .changeset/thick-lamps-knock6.md, .changeset/thick-lamps-knock7.md, .changeset/thick-lamps-knock8.md, .changeset/thick-lamps-knock9.md, .changeset/wild-oranges-unite.md
=> chore: minor changeset details for better changelogs

packages/paste-website/src/pages/introduction/for-designers/design-guidelines/index.mdx
https://deploy-preview-3619--paste-docs.netlify.app/introduction/for-designers/design-guidelines
=> feat(website): add customer info in design guidelines

packages/paste-website/package.json, packages/paste-website/src/components/assistant/AssistantMessage.tsx, packages/paste-website/src/components/assistant/EnterKeySubmitPlugin.tsx, packages/paste-website/src/components/assistant/SendButtonPlugin.tsx, packages/paste-website/src/components/assistant/ThreadList.tsx, packages/paste-website/src/components/assistant/UserMessage.tsx, packages/paste-website/src/pages/api/paste-assistant-message.ts, packages/paste-website/src/pages/api/paste-assistant-messages/[tid].ts, packages/paste-website/src/pages/api/paste-assistant-thread/[tid].ts, packages/paste-website/src/pages/api/paste-assistant-thread/index.ts, packages/paste-website/src/pages/assistant.tsx, packages/paste-website/src/utils/formatTimestamp.ts, yarn.lock
=> chore: ai assistant apis

.github/workflows/on_deployment_status_cypress.yml
=> chore: finally get cypress tests right

.github/workflows/on_deployment_status_cypress.yml, .github/workflows/on_pull_request_cypress.yml, cypress.config.e2e.ts, cypress.config.ts, cypress/integration/api/ai.spec.ts, cypress/integration/api/discussions-search.spec.ts, cypress/integration/api/docs-search.spec.ts, cypress/integration/api/og-image.spec.ts, cypress/integration/api/paste-assistant-message.spec.ts, cypress/integration/api/paste-assistant-thread.spec.ts
To prove they work on the preview deployments before we merge, and to make sure we don't break them in the future.
=> test: add tests for the api routes

renovate.json
=> chore: ignore eslint from renovate updates

renovate.json
=> chore: update renovate schedule and deps

packages/paste-website/src/pages/api/paste-assistant-message.ts
This pull request includes changes to the `handler` function in the `paste-assistant-message.ts` file. The changes aim to improve error handling by checking if `slackThreadID` is null and adding a try-catch block around the code that posts a new message to the Slack thread.
Here are the most important changes:
* [`packages/paste-website/src/pages/api/paste-assistant-message.ts`](diffhunk://#diff-1624283f8b7ba4cde3e08aed336a7643cab8a4d876cd1c2e8268717401679dcaL150-R155): Added a null check for `slackThreadID` in the if condition to handle the case when `slackThreadID` is null. This will prevent any further execution and log an error.
* [`packages/paste-website/src/pages/api/paste-assistant-message.ts`](diffhunk://#diff-1624283f8b7ba4cde3e08aed336a7643cab8a4d876cd1c2e8268717401679dcaR175-R17 …
=> fix: better assistant error handling for older threads

internal-docs/engineering/doc-site/docsearch.md, internal-docs/engineering/doc-site/paste-assistant.md, internal-docs/engineering/environment-variables.md
This pull request includes changes that primarily focus on the documentation and environment variable configuration for the internal engineering team. The most important changes include the addition of a new document explaining the Paste Assistant, updates to the `docsearch.md` file to include information about production and previews, and changes to the `environment-variables.md` file to reflect updated environment variable requirements.
Documentation updates:
* [`internal-docs/engineering/doc-site/docsearch.md`](diffhunk://#diff-1ab1389acc11e674acfc841d7d9200220964f15b6ffa877429ef106cd7e0f16eR21-R31): Added information about production and previews, and updated the API route details. This allows the team to test changes to the search index without affecting production.
* …
=> chore: update internal docs

packages/paste-icons/__test__/__snapshots__/icons.spec.tsx.snap, packages/paste-icons/src/ProductAIAssistantsIcon.tsx, packages/paste-website/src/pages/introduction/contributing/icons/index.mdx
Small fast-follow for https://github.com/twilio-labs/paste/pull/3820 to address a snapshot test and fix deploys.
=> test(icons): fix snapshot test

.changeset/fluffy-grapes-prove.md, packages/paste-libraries/reakit/src/Popover/PopoverArrow.tsx
Fixes https://github.com/twilio-labs/paste/issues/3828
=> fix(reakit-library): fix popoverarrow rendering

.changeset/small-lamps-flow.md, packages/paste-core/components/code-block/src/CopyButton.tsx
Fixes https://github.com/twilio-labs/paste/issues/3839
Issue was [introduced in React v18](https://github.com/reactwg/react-18/discussions/21) but went unnoticed as it is a warning in most cases.
=> fix(codeblock): fix flushsync error

.changeset/stupid-hats-check.md, packages/paste-core/components/spinner/src/Spinner.tsx, packages/paste-core/components/spinner/src/keyframes.tsx, packages/paste-core/components/spinner/src/styled.tsx
=> chore: fix safari spinner bug

.changeset/thin-lobsters-pretend.md, packages/paste-core/components/modal/src/ModalBody.tsx, packages/paste-core/components/modal/src/ModalFooter.tsx
Fixes https://github.com/twilio-labs/paste/issues/3845
=> fix(modal): improve padding on ModalBody and ModalFooter

packages/paste-website/src/pages/components/toast/index.mdx
Adds some missing spaces to the callout on Toast https://paste-docs-git-chore-docs-add-space-to-toast-callout-twilio.vercel.app/components/toast#accessibility
=> chore(docs): add space to callout in Toast

.changeset/yellow-rabbits-tie.md, packages/paste-core/components/side-modal/src/index.tsx, packages/paste-website/src/component-examples/TooltipPrimitiveExamples.ts, packages/paste-website/src/pages/primitives/tooltip-primitive/index.mdx
Fixes https://github.com/twilio-labs/paste/discussions/3883
=> fix(side-modal): fix position when using state hook

packages/paste-website/src/pages/introduction/contributing/icons/index.mdx
https://paste-docs-git-feat-add-icon-request-batching-docs-twilio.vercel.app/introduction/contributing/icons#finding-an-icon
=> feat(website): add icon request batching info

packages/paste-website/src/component-examples/TooltipPrimitiveExamples.ts
Fixes follow-up comment on https://github.com/twilio-labs/paste/issues/3882
=> Adds text color to Tooltip Primitive example

packages/paste-website/src/component-examples/MultiselectComboboxExamples.ts
=> chore: fix scroll down behavior

.changeset/three-terms-teach.md, packages/paste-core/primitives/box/type-docs.json, packages/paste-core/primitives/sibling-box/type-docs.json, packages/paste-core/primitives/text/type-docs.json, packages/paste-design-tokens/__tests__/__snapshots__/index.test.tsx.snap, packages/paste-design-tokens/tokens/global/background-color.yml, packages/paste-design-tokens/tokens/global/box-shadow.yml
Add new notification tokens:
- color-background-notification
- shadow-border-notification
- shadow-border-bottom-notification-stronger
=> feat(tokens): add notification tokens

cypress/integration/api/ai.spec.ts, packages/paste-website/src/components/site-wrapper/site-header/index.tsx
=> chore: remove assistant temporarily

.changeset/tame-games-hammer.md, packages/paste-core/components/ai-chat-log/stories/aiChatLog.stories.tsx, packages/paste-core/components/button-group/src/ButtonGroup.tsx, packages/paste-core/components/button-group/stories/index.stories.tsx, packages/paste-core/components/button-group/type-docs.json, packages/paste-website/src/pages/experiences/artificial-intelligence/index.mdx
https://twilio-productivity.atlassian.net/browse/DS-445
=> feat(button-group): add justifyContent prop, use flex

packages/paste-website/src/component-examples/filter/components/CustomDateFilterGroup.tsx, packages/paste-website/src/component-examples/filter/components/DefaultFilter.tsx, packages/paste-website/src/component-examples/filter/components/ExtendedDataGrid.tsx, packages/paste-website/src/component-examples/filter/components/FilterPill.tsx, packages/paste-website/src/component-examples/filter/components/SampleDataGrid.tsx, packages/paste-website/src/component-examples/filter/components/filters/AddFilters.tsx, packages/paste-website/src/component-examples/filter/components/filters/CustomFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/DepartmentFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/HostNameFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/PlatformFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/RoomSidFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/RoomTypeFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/StatusFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/TagsFilter.tsx, packages/paste-website/src/component-examples/filter/components/filters/UniqueNameFilter.tsx, packages/paste-website/src/component-examples/filter/constants.ts, packages/paste-website/src/component-examples/filter/helpers.ts, packages/paste-website/src/component-examples/filter/types.ts, packages/paste-website/src/pages/patterns/filter/index.mdx, packages/paste-website/stories/Filter.stories.tsx
- Update storybook with new example that implements Add filters
- Update paste website with Add filters implementation example
=> Implement 'Add Filters' example for filter pattern

packages/paste-website/src/pages/components/corner-ornament/index.mdx
Fix a issue in corner ornament docs
=> fix(corner-ornament): copy issue

packages/paste-website/src/pages/page-templates/object-details/index.mdx, packages/paste-website/src/pages/page-templates/objects-list/index.mdx, packages/paste-website/src/pages/page-templates/settings/index.mdx, packages/paste-website/src/pages/page-templates/wizard/index.mdx, packages/paste-website/stories/PageTemplates.stories.tsx
Update the objects list page template to use the new filter pattern guidance
=> chore: update objects list template to use filter pattern

packages/paste-website/src/pages/components/combobox/index.mdx
https://paste-docs-git-feat-combobox-docs-no-chevron-twilio.vercel.app/components/combobox#autocomplete-combobox
=> feat(combobox docs): add no-chevron reasoning

cypress/integration/sidebar-navigation/index.spec.ts
Fix an issue where the Vercel overlay was causing a test to fail. Changed the test case to inspect css element changes to determine if visible.
=> fix(cypress): fix issue with cypress and vercel previews

packages/paste-website/src/component-examples/ObjectStatusPatternExamples.tsx, packages/paste-website/src/component-examples/StatusPatternExamples.tsx, packages/paste-website/src/pages/patterns/object-status/index.mdx, packages/paste-website/src/pages/patterns/status/index.mdx
Updates doc: https://docs.google.com/document/d/1kDSWZrUBIR0ZrliM80_IjKCM8rMIDiISuxHTlQ-1xvs/edit?tab=t.0
=> chore: update status pattern

.changeset/warm-pots-rush.md, packages/paste-core/components/progress-steps/src/ProgressStepError.tsx, packages/paste-core/components/progress-steps/src/ProgressStepIncomplete.tsx
=> [Progress Steps]: remove unnecessary space

.changeset/dull-panthers-develop.md
Fix changeset package name to resolve pipeline issues on main
=> chore(ci): fix changeset package name

packages/paste-website/src/components/site-search/SearchForm.tsx, packages/paste-website/src/components/tokens-list/TokensListFilter.tsx
=> chore(website): small fixes

packages/paste-website/src/pages/index.tsx
Added a meta tag to the site to verify that we own the site to become an owner of the Google Search Console (GSC) for this site
=> chore(docs): add GSC verification
